import csv
from xml.sax.saxutils import escape

MANIFEST = "/mnt/d/Luke/dev/Rimworld/design/Jawa/worldbuilding/data/beast_norm_manifest.csv"
OUT = "/mnt/d/Luke/dev/Rimworld/src/RimStarWars/BeastNorm/Patches/BeastNorm_Law3.xml"

with open(MANIFEST) as f:
    rows = list(csv.DictReader(f))

ops = []
skipped = 0
for r in rows:
    if r["exempt"]:
        skipped += 1
        continue
    d = escape(r["defName"])
    i = r["best_tool_index"]
    power = r["new_power"]
    cd = r["new_cooldown"]

    tool_xpath = f'/Defs/ThingDef[defName="{d}"]/tools/li[{int(i)+1}]'
    op = f'''  <Operation Class="PatchOperationConditional">
    <xpath>{tool_xpath}/power</xpath>
    <match Class="PatchOperationSequence">
      <operations>
        <li Class="PatchOperationReplace">
          <xpath>{tool_xpath}/power</xpath>
          <value>
            <power>{power}</power>
          </value>
        </li>
        <li Class="PatchOperationReplace">
          <xpath>{tool_xpath}/cooldownTime</xpath>
          <value>
            <cooldownTime>{cd}</cooldownTime>
          </value>
        </li>
      </operations>
    </match>
  </Operation>'''
    ops.append(op)

    if r["raise_revenge"] == "True":
        dmg = r["manhunterOnDamageChance_new"]
        tame = r["manhunterOnTameFailChance_new"]
        race_xpath = f'/Defs/ThingDef[defName="{d}"]/race'

        if r["manhunterOnDamageChance_present"] == "True":
            op = f'''  <Operation Class="PatchOperationConditional">
    <xpath>{race_xpath}/manhunterOnDamageChance</xpath>
    <match Class="PatchOperationReplace">
      <xpath>{race_xpath}/manhunterOnDamageChance</xpath>
      <value>
        <manhunterOnDamageChance>{dmg}</manhunterOnDamageChance>
      </value>
    </match>
  </Operation>'''
        else:
            op = f'''  <Operation Class="PatchOperationConditional">
    <xpath>{race_xpath}/manhunterOnDamageChance</xpath>
    <nomatch Class="PatchOperationAdd">
      <xpath>{race_xpath}</xpath>
      <value>
        <manhunterOnDamageChance>{dmg}</manhunterOnDamageChance>
      </value>
    </nomatch>
  </Operation>'''
        ops.append(op)

        if r["manhunterOnTameFailChance_present"] == "True":
            op = f'''  <Operation Class="PatchOperationConditional">
    <xpath>{race_xpath}/manhunterOnTameFailChance</xpath>
    <match Class="PatchOperationReplace">
      <xpath>{race_xpath}/manhunterOnTameFailChance</xpath>
      <value>
        <manhunterOnTameFailChance>{tame}</manhunterOnTameFailChance>
      </value>
    </match>
  </Operation>'''
        else:
            op = f'''  <Operation Class="PatchOperationConditional">
    <xpath>{race_xpath}/manhunterOnTameFailChance</xpath>
    <nomatch Class="PatchOperationAdd">
      <xpath>{race_xpath}</xpath>
      <value>
        <manhunterOnTameFailChance>{tame}</manhunterOnTameFailChance>
      </value>
    </nomatch>
  </Operation>'''
        ops.append(op)

header = f'''<?xml version="1.0" encoding="utf-8"?>
<!-- generated by Transient/gen_beastnorm_patch.py from design/Jawa/worldbuilding/data/beast_norm_manifest.csv -->
<!-- Law 3 danger pass: best-hit tool power/cooldown per bs, revenge knobs on big herbivores -->
<!-- see design/Jawa/worldbuilding/beast_normalization_spec.md and items/BEAST_DANGER_NORMALIZATION_1.md -->
<Patch>
'''
footer = "\n</Patch>\n"

import os
os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w") as f:
    f.write(header)
    f.write("\n\n".join(ops))
    f.write(footer)

print(f"{len(ops)} operations for {len(rows) - skipped} beasts ({skipped} exempt bs<1) -> {OUT}")
