import csv
from xml.sax.saxutils import escape

MANIFEST = "/mnt/d/Luke/dev/Rimworld/design/Jawa/worldbuilding/data/seas_waterline_manifest.csv"
OUT = "/mnt/d/Luke/dev/Rimworld/src/RimStarWars/SeasWaterline/Patches/Waterline_Lane1.xml"

with open(MANIFEST) as f:
    rows = list(csv.DictReader(f))

def set_biome_op(wb_xpath, biome, value):
    child_xpath = f"{wb_xpath}/{biome}"
    return f'''  <Operation Class="PatchOperationConditional">
    <xpath>{child_xpath}</xpath>
    <match Class="PatchOperationReplace">
      <xpath>{child_xpath}</xpath>
      <value>
        <{biome}>{value}</{biome}>
      </value>
    </match>
    <nomatch Class="PatchOperationAdd">
      <xpath>{wb_xpath}</xpath>
      <value>
        <{biome}>{value}</{biome}>
      </value>
    </nomatch>
  </Operation>'''

ops = []
for r in rows:
    d = escape(r["defName"])
    wb_xpath = f'/Defs/ThingDef[defName="{d}"]/race/wildBiomes'
    ops.append(set_biome_op(wb_xpath, "Lake", r["Lake_new"]))
    ops.append(set_biome_op(wb_xpath, "Ocean", r["Ocean_new"]))
    if r["misplaced_biome"]:
        ops.append(set_biome_op(wb_xpath, r["misplaced_biome"], "0"))

header = '''<?xml version="1.0" encoding="utf-8"?>
<!-- generated by Transient/gen_seas_patch.py from design/Jawa/worldbuilding/data/seas_waterline_manifest.csv -->
<!-- SEAS_WATERLINE_PASS_1 Lane 1: give the 7 SW aquatics plus 5 license-cleared -->
<!-- borrowed fish/crabs their first Lake/Ocean commonality, and zero KwazelMaw's -->
<!-- and Mott's fire-desert placement (some other mod's compat patch, not this -->
<!-- file's own declaration, hence this mod is positioned late in ModsConfig). -->
<!-- see design/Jawa/worldbuilding/the_seas.md Lane 1, items/SEAS_WATERLINE_PASS_1.md -->
<Patch>
'''
footer = "\n</Patch>\n"

import os
os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w") as f:
    f.write(header)
    f.write("\n\n".join(ops))
    f.write(footer)

print(f"{len(ops)} operations for {len(rows)} beasts -> {OUT}")
