#!/usr/bin/env python3
"""PreToolUse/Bash hook — BLOCKS the four commits that would corrupt the ledger.

WHY A HOOK AND NOT A PARAGRAPH
==============================
This project has already proved twice that a `PreToolUse` hook changes behaviour where
prose does not. `git add -A` was forbidden in writing for two days and kept happening;
a hook stopped it the same afternoon.

⚠️ Everything here is about a NEW failure surface that did not exist before 2026-08-20.
Until then `queue/*.md` was hand-written and editing it was the job. Now it is rendered
from `infrastructure/state/ledger/events.jsonl`, and the same edit that used to be the
work is now a silent no-op — overwritten by the next `rimflow render`, with the effort
gone and nobody told.

WHAT IT BLOCKS
==============
1. **Committing an edit to a generated queue view.** The file says DO NOT EDIT at the
   top; this makes that true instead of hopeful.
2. **WRITING `events.jsonl` by any route that is not `rimflow`.** ⛔ The ledger's
   `flock` is ADVISORY — it protects writers that take it, and a shell redirect or an
   editor takes nothing. On this repo's 9p mount, concurrent writes without the lock
   lose five of every six events. `model.append()` is the only safe writer.

   🔴 **This is enforced at the WRITE, and it used to be enforced at the COMMIT. That
   was a defect, and it cost the project 358 events sitting on one disk.** Committing a
   changed ledger IS the normal case — every `rimflow` verb changes it — so a rule that
   denied "a commit naming the ledger while the ledger differs from HEAD" fired on every
   legitimate commit and never on the hand-edit it was aimed at. `git diff` cannot tell
   an append from an editor write; the tool call that made it can.
   ⚠️ Mentioning the path is not writing it. `grep`, `cat`, `sed -n`, `wc` and a commit
   pathspec all name the ledger and are all allowed — only redirects, in-place editors,
   copies over it and `open(..., 'w'|'a')` are refused. Over-blocking here is not the
   safe direction: a hook that wedges correct work gets disabled, and then nothing is
   guarded at all.
3. **Editing `items/<ID>.md` for an item another seat owns.** Filing work FOR another
   seat is normal and encouraged; changing their work is not, and four seats share one
   working tree so it is easy to do by accident.
4. **A new root-level `.md` that is not `TRANSIENT_*`.** The repo root is shared and
   already carries 342 markdown files; the naming rule is what keeps scratch findable
   and sweepable.

WHAT IT ONLY WARNS ABOUT
========================
`design/INDEX.md` drift. ⚠️ It is generated by `doc_roster.py --write`, and the plan
asked for a hook that REGENERATES it on commit. ⛔ That would be wrong: a PreToolUse
hook that writes files changes the tree underneath a `git commit` whose pathspec is
already fixed, so the regenerated index would NOT be in the commit — leaving the repo
dirty and the author believing it was handled. Warn, name the command, let a human run
it.

🔴 AND ONE THING THE PLAN ASKED FOR THAT IS DELIBERATELY NOT DONE
=================================================================
§8 says to make `warn_unclosed_queue_item.py` **block**. It must not. The owner ruled
2026-08-15 that it warns and never gates: *"a hook that refuses a commit costs more
than the miscount it prevents, and a seat that hits it mid-flow will work around it."*
That ruling has not been reversed, so the hook exits 1 — visible, non-blocking — and
the plan is corrected rather than obeyed.

FAIL-OPEN, STDLIB ONLY
======================
Blocks via `permissionDecision: deny` on stdout with exit 0, the same mechanism as
`block_blanket_git_stage.py`, so a crash can never gate a commit.

    python3 .claude/hooks/selftest_queue_lint.py
"""
import json
import os
import re
import subprocess
import sys

STATE = "infrastructure/state/"
LEDGER = STATE + "ledger/events.jsonl"
ITEMS = STATE + "items/"
QUEUE = STATE + "queue/"
GENERATED = "generated by rimflow render"
SEATS = ("DECIDE", "BUILD", "CHECK", "REP", "OWNER")


# 🔴 EVERY refusal ends with this, because a refusal that looks PARTIAL is worse than
# one that looks total. Measured 2026-08-21: REP appended to queue/HUMAN.md and committed
# in ONE Bash call, the commit half was refused, and the APPEND never happened either —
# caught only by grepping HEAD afterwards and nearly reported as done. A PreToolUse hook
# fires before the shell does, so there is no "the first half went through".
ATOMIC = (
    "\n\n⚠️  NOTHING IN THAT COMMAND RAN — including anything BEFORE the part that "
    "was\nrefused. A PreToolUse hook fires before the shell, so a compound command is "
    "refused\nwhole. If you chained a file write to a commit with `;` or `&&`, the write "
    "did not\nhappen either. Re-run the write on its own."
)


def deny(reason):
    print(json.dumps({"hookSpecificOutput": {
        "hookEventName": "PreToolUse",
        "permissionDecision": "deny",
        "permissionDecisionReason": reason + ATOMIC}}))
    return 0


def git(root, *args):
    try:
        p = subprocess.run(["git", "-C", root, *args], capture_output=True,
                           text=True, timeout=8)
    except (OSError, subprocess.SubprocessError):
        return None
    return p.stdout if p.returncode == 0 else None


LEDGER_MSG = (
    "Blocked: %s is being written by something that is not `rimflow`.\n\n"
    "The ledger is APPEND-ONLY and `rimflow` is its only writer. Its lock is ADVISORY "
    "— it protects writers that take it, and a shell redirect or an editor takes "
    "nothing. On this repo's 9p mount, concurrent writes without that lock lost five "
    "of every six events and tore hundreds of lines in half (measured 2026-08-20).\n\n"
    "To change what the ledger says, add an event:\n"
    "    python3 src/RimMandrake/rimflow/cli.py <verb> …\n"
    "To correct one that is already in it, the OWNER appends an `admin` event. "
    "Nothing is ever removed.\n\n"
    "✅ COMMITTING the ledger is fine and is not what this refused — commit it after "
    "every turn, and push. Reading it with grep, cat or sed -n is fine too.")

VIEW_MSG = (
    "Blocked: %s is a GENERATED VIEW and you are editing it by hand.\n\n"
    "It is rendered from infrastructure/state/ledger/events.jsonl, so this edit is not "
    "a small mistake — it is invisible. The next render overwrites it, the work is "
    "gone, and nobody is told.\n\n"
    "What you probably meant:\n"
    "  change an item's STATE   -> rimflow claim|start|block|close <ID>\n"
    "  change its PROSE         -> edit infrastructure/state/items/<ID>.md\n"
    "  file something new       -> rimflow file --for <SEAT> …\n"
    "  regenerate the view      -> python3 src/RimMandrake/rimflow/render.py "
    "--overwrite-queues\n\n"
    "\u26a0\ufe0f  The flag is part of that command. Bare `render.py` writes a PREVIEW and "
    "leaves\nthis file exactly as stale as it already was.\n"
    "\u2705 These four views are gitignored, so there is nothing to commit either way.")

# 🔴 Refused at the WRITE so no work is ever created that cannot be landed. The commit
# is refused too (rule 3) — but by then the edit is already stranded in a shared tree.
#
# 🔑 The route it hands over is not a consolation prize: `file --for <them>` leaves the
# new item UNCLAIMED, and `owners(root, "unclaimed_filers")` exempts the FILER, so the
# correcting seat may write AND commit the new item's own file. The correction ends up
# durable, in git, addressed to the right seat — which is everything the stranded edit
# was not.
ITEM_OWNED_MSG = (
    "\u26d4 Blocked at the WRITE, not at the commit \u2014 and that is deliberate.\n\n"
    "    %(iid)s belongs to %(holder)s.\n\n"
    "If you write this and the commit bounces, your correction exists ONLY in a working "
    "tree\nfour seats share, where the next `git checkout` erases it and nothing tells "
    "%(holder)s it\nwas ever there. That happened twice, and both were found by luck the "
    "next morning. So\nthe refusal moved here, to the moment the work would be created.\n\n"
    "\u2705 SEND the correction instead. Two commands, and the work ends up in git:\n\n"
    "  1. File it against them \u2014 this leaves it UNCLAIMED, which is what lets you "
    "write it:\n\n"
    "     python3 src/RimMandrake/rimflow/cli.py file %(new)s \\\n"
    "       --for %(holder)s --kind task --caused-by %(iid)s \\\n"
    "       --title \"<what is wrong with %(iid)s, in one line>\"\n\n"
    "  2. Write the correction into ITS file \u2014 yours to write and yours to commit:\n\n"
    "     infrastructure/state/items/%(new)s.md\n"
    "       ## Spec        the correction IN FULL. This is the deliverable.\n"
    "       ## Verify      how %(holder)s confirms it landed\n"
    "       ## Criteria    what done looks like\n\n"
    "     git commit infrastructure/state/items/%(new)s.md -m \"<subject>\"\n\n"
    "\U0001f511 Write the WHOLE correction into `## Spec`. %(holder)s should be able to "
    "apply it\nwithout reconstructing anything you already worked out.\n\n"
    "\u26a0\ufe0f  Genuinely urgent, or %(holder)s is wrong on the merits? Say so in\n"
    "infrastructure/state/queue/HUMAN.md \u2014 any seat may write that one."
)


LEDGER_PATH_RE = re.compile(r"[\w./\\-]*ledger/events\.jsonl")
# A redirect must land on the ledger IMMEDIATELY. ⚠️ "somewhere earlier in the command"
# is not good enough and was a false deny: `wc -l 2>/dev/null <ledger>` has a `>` before
# the path, and that `>` already has its own target.
REDIRECT_RE = re.compile(r">>?\s*['\"]?$")
# These take the file as an ARGUMENT, so anywhere in the same shell word-run counts.
# `dd of=` is spelled out because the path attaches to the operand, not the command.
ARG_WRITER_RE = re.compile(
    r"(?:\b(?:tee|cp|mv|rm|install|shred|truncate|ln)\b|\bof=|"
    r"\bsed\b[^|;&]*?\s-i)[^|;&]*$")
# python3 -c "open('…/events.jsonl', 'w')" — the mode sits AFTER the path.
WRITE_AFTER_RE = re.compile(r"^\s*['\"]?\s*,\s*['\"][wax]")


def ledger_write_target(cmd):
    """-> the ledger path this command WRITES, or None if it only mentions it.

    ⚠️ The distinction is the whole point. `git commit …/events.jsonl`, `grep x
    …/events.jsonl` and a path quoted inside a report all mention it; none of them
    write it. Blocking on mention is what broke this hook the first time.
    """
    for m in LEDGER_PATH_RE.finditer(cmd):
        before = cmd[max(0, m.start() - 80):m.start()]
        if REDIRECT_RE.search(before) or ARG_WRITER_RE.search(before):
            return m.group(0)
        if WRITE_AFTER_RE.match(cmd[m.end():m.end() + 12]):
            return m.group(0)
    return None


# ⚠️ A COMMIT MESSAGE IS NOT A PATHSPEC, and treating it as one refused four
# legitimate commits on 2026-08-21 — including one whose only sin was quoting the path
# of the file it was fixing, and one whose body contained the string "REP.md". The old
# rule was `re.findall(r"[\w./-]+\.(?:md|jsonl)", cmd)` over the whole command.
_MSG_FLAG_RE = re.compile(r"""(?x)
    (?:^|\s) -(?:m|F|c|C|-message|-file|-reedit-message|-reuse-message)
    (?:=|\s+)
    (?: "(?:[^"\\]|\\.)*"? | '[^']*'? | \S+ )
""")
_HEREDOC_RE = re.compile(r"<<-?\s*['\"]?(\w+)['\"]?.*?^\1", re.S | re.M)
_PATH_RE = re.compile(r"[\w./-]+\.(?:md|jsonl)")


def commit_pathspec(cmd):
    """-> the .md/.jsonl paths this `git commit` actually names as a PATHSPEC.

    Message bodies, heredocs and `--flag=value` text are stripped first. What survives
    is a bare word-run that git itself would read as a path.

    🔑 Over-stripping is the SAFE direction here. A missed pathspec means a rule does
    not fire; a phantom one from prose means correct work is refused, and a hook that
    refuses correct work gets disabled — after which nothing is guarded at all.
    """
    stripped = _HEREDOC_RE.sub(" ", cmd)
    stripped = _MSG_FLAG_RE.sub(" ", stripped)
    # Anything still inside quotes is a message body the flag regex could not pair up.
    stripped = re.sub(r"\"(?:[^\"\\]|\\.)*\"|'[^']*'", " ", stripped)
    return _PATH_RE.findall(stripped)


def is_generated(path):
    try:
        with open(path, encoding="utf-8", errors="replace") as fh:
            return GENERATED in fh.read(400)
    except OSError:
        return False


def my_seat(root):
    """-> the seat this window is, or None. ⚠️ None means DO NOT ENFORCE ownership.

    Guessing a seat here would block the wrong person's legitimate commit, and a hook
    that blocks correct work is one that gets disabled. Unknown seat = skip rule 3.
    """
    s = os.environ.get("RIMFLOW_SEAT") or os.environ.get("AGENT_SEAT")
    if s and s.strip().upper() in SEATS:
        return s.strip().upper()
    return None


def owners(root, want=None):
    """-> {item_id: owning_seat} from the ledger. {} if it cannot be read.

    `want="unclaimed_filers"` instead returns {item_id: filing_seat} for items NOBODY
    has claimed yet. 🔑 `rimflow file --for X` TELLS the filer to write the spec, so
    refusing the filer's later corrections to it made the instruction impossible to
    follow — the first commit only worked because `git diff` does not list untracked
    files. A claim is the handover; before it there is nothing to protect.
    """
    out = {}
    filed_by, claimed = {}, set()
    path = os.path.join(root, LEDGER)
    try:
        with open(path, encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    ev = json.loads(line)
                except ValueError:
                    return {}            # torn ledger: say nothing rather than guess
                if ev.get("event") == "file" and ev.get("id"):
                    out[ev["id"]] = ev.get("for")
                    filed_by[ev["id"]] = ev.get("seat")
                elif ev.get("event") == "spawn" and ev.get("name"):
                    out[ev["name"]] = ev.get("for")
                    filed_by[ev["name"]] = ev.get("seat")
                elif ev.get("event") == "reassign" and ev.get("id"):
                    out[ev["id"]] = ev.get("to")
                    claimed.add(ev["id"])
                elif ev.get("event") in ("claim", "start") and ev.get("id"):
                    claimed.add(ev["id"])
    except OSError:
        return {}
    if want == "unclaimed_filers":
        return {k: v for k, v in filed_by.items() if v and k not in claimed}
    return out


def changed(root, paths):
    """Which of `paths` differ from HEAD in the WORKING TREE.

    ⚠️ The working tree, not the index: `git commit <path>` commits the tree at that
    path regardless of what is staged, which is the whole reason this repo commits by
    pathspec. Checking the index would miss exactly the case that matters.
    """
    out = git(root, "diff", "HEAD", "--name-only", "--", *paths)
    return [l.strip() for l in (out or "").splitlines() if l.strip()]


def main():
    try:
        ev = json.load(sys.stdin)
    except Exception:
        return 0
    ti = ev.get("tool_input") or {}

    # ---- 2. the ledger is append-only and tool-only, enforced at the WRITE ---
    # An editing tool names its target outright, so there is nothing to infer.
    if (ev.get("tool_name") or "") in ("Write", "Edit", "MultiEdit", "NotebookEdit"):
        fp = (ti.get("file_path") or ti.get("notebook_path") or "").replace("\\", "/")
        if fp.rstrip("/").endswith("ledger/events.jsonl"):
            return deny(LEDGER_MSG % fp)
        # A generated queue view: refuse the EDIT, which is the moment the work is
        # wasted. `render` writes these with open(), not through a tool call, so it is
        # unaffected — which is the whole reason this belongs here and not at commit.
        if QUEUE in fp and is_generated(fp if os.path.isabs(fp) else os.path.join(
                os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd(), fp)):
            return deny(VIEW_MSG % fp)
        # ---- 3a. another seat's ITEM FILE — refused HERE, at the write ------
        #
        # 🔴 THE ASYMMETRY THAT MANUFACTURED STRANDED WORK — owner's ruling, 2026-08-22.
        # Rule 3 refused the COMMIT and this branch permitted the WRITE, so a seat could
        # spend a whole turn writing a correction into another seat's item, be refused
        # only at the end, and be left holding work that existed in nothing but a shared
        # working tree. DECIDE reported it twice: *"the edit sits in the working tree
        # where the next git checkout would erase it. Both were still sitting there this
        # morning."* Nothing routed them; it noticed by luck, both times.
        #
        # 🔑 A guard that blocks at commit but permits the write ALWAYS produces this.
        # The write is the moment the work is created, so it is the moment to refuse.
        if ITEMS in fp and fp.endswith(".md"):
            root = os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd()
            seat = my_seat(root)
            iid = os.path.basename(fp)[:-3]
            holder = owners(root).get(iid) if seat else None
            if (holder and seat and holder != seat and seat != "OWNER"
                    and owners(root, "unclaimed_filers").get(iid) != seat):
                bits = [b for b in iid.split("_") if not b.isdigit()][:2]
                return deny(ITEM_OWNED_MSG % {
                    "iid": iid, "holder": holder,
                    "new": "_".join(["CORRECT"] + bits + ["1"])})
        return 0                          # rule 4 is about commits, not edits

    cmd = ti.get("command") or ""
    hit = ledger_write_target(cmd)
    if hit:
        return deny(LEDGER_MSG % hit)

    if "git" not in cmd or "commit" not in cmd:
        return 0
    root = os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd()
    paths = commit_pathspec(cmd)
    if not paths:
        return 0

    # ---- 1. a generated view is not a place to write ------------------------
    # 🔴 ENFORCED AT THE WRITE, not here — see the Write/Edit branch above, and the
    # same correction the ledger rule got. A REGENERATED view is byte-different from
    # HEAD every single time, so a commit-time rule fired on `render --overwrite-queues`
    # (the correct, required action) and never on the hand-edit it was aimed at. The
    # four views are now gitignored as the derived artifacts they are — `derived/` was
    # already ignored for exactly this reason. Kept as dead code? No: deleted. This
    # comment is the record.
    for p in ():
        if QUEUE in p and is_generated(os.path.join(root, p)) and changed(root, [p]):
            return deny(
                "Blocked: %s is a GENERATED VIEW and you are committing an edit to "
                "it.\n\n"
                "It is rendered from infrastructure/state/ledger/events.jsonl, so this "
                "edit is not a small mistake — it is invisible. The next "
                "`rimflow render` overwrites it, the work is gone, and nobody is "
                "told.\n\n"
                "What you probably meant:\n"
                "  change an item's STATE   -> rimflow claim|start|block|close <ID>\n"
                "  change its PROSE         -> edit infrastructure/state/items/<ID>.md\n"
                "  file something new       -> rimflow file --for <SEAT> …\n"
                "  regenerate the view      -> python3 src/RimMandrake/rimflow/render.py "
                "--overwrite-queues\n"
                "\n"
                "\u26a0\ufe0f  The flag is part of that command. Bare `render.py` writes a "
                "PREVIEW\nand leaves this file exactly as stale as it already was. "
                "Corrected 2026-08-21."
                % p)

    # ---- 3. you may file for any seat; you may change only what you own -----
    seat = my_seat(root)
    if seat:
        own = owners(root)
        may_finish = owners(root, "unclaimed_filers")
        # ⚠️ `git diff HEAD --` with an EMPTY pathspec lists the whole working tree, so
        # this used to refuse a commit because some OTHER seat was mid-edit on an item
        # that appeared in neither the pathspec nor the diff. Four seats share one tree;
        # it fired constantly. Measured 2026-08-21.
        want = [p for p in paths if ITEMS in p]
        mine = changed(root, want) if want else []
        bad = []
        for p in mine:
            iid = os.path.basename(p)[:-3]
            holder = own.get(iid)
            if holder and holder != seat and seat != "OWNER":
                if may_finish.get(iid) == seat:
                    continue             # you filed it and nobody has claimed it yet
                bad.append((iid, holder))
        if bad:
            return deny(
                "Blocked: %s is editing %d item(s) owned by another seat.\n\n%s\n\n"
                "Filing work FOR another seat is normal and encouraged. Changing their "
                "work is refused — four seats share one working tree, so this is easy "
                "to do by accident and impossible to notice afterwards.\n\n"
                "File instead:  rimflow file --for %s --title \"…\" --kind task <ID>\n"
                "Or, if the owner is genuinely wrong, say so in "
                "infrastructure/state/queue/HUMAN.md."
                % (seat, len(bad),
                   "\n".join("    %-44s belongs to %s" % (i, h) for i, h in bad),
                   bad[0][1]))

    # ---- 4. the repo root is shared -----------------------------------------
    # ⚠️ Scope the check to THIS repo. `git commit SKILL.md` run from another
    # checkout on the same machine reaches this hook with a bare path, and
    # without the existence test it is judged against Rimworld's root — which
    # refuses a legitimate commit in a repo this guard has no authority over.
    # Measured 2026-08-21 on a sibling skill repo.
    tracked = set((git(root, "ls-files") or "").split())
    for p in paths:
        if "/" in p or not p.endswith(".md"):
            continue
        if not os.path.exists(os.path.join(root, p)):
            continue                      # not a file in this repo at all
        if p in tracked or os.path.basename(p).startswith("TRANSIENT_"):
            continue
        if p.isupper() or p in ("README.md", "CLAUDE.md"):
            continue
        return deny(
            "Blocked: %s is a new markdown file at the repo root and is not named "
            "TRANSIENT_*.\n\n"
            "The root already carries 342 markdown files. The naming rule is what "
            "keeps scratch findable and sweepable — `rimflow sweep --transient` lists "
            "stale ones, and a file outside the convention is invisible to it "
            "forever.\n\n"
            "  scratch, analysis, a one-off report  ->  TRANSIENT_%s\n"
            "  a design document                    ->  design/…\n"
            "  project state                        ->  infrastructure/state/…" % (p, p))

    # ---- warn only: the generated index drifts ------------------------------
    if any(p.startswith("design/") for p in paths):
        try:
            r = subprocess.run(
                [sys.executable, os.path.join(root, "src/RimMandrake/Utils/doc_roster.py")],
                capture_output=True, text=True, cwd=root, timeout=30)
            if r.returncode:
                print("⚠ design/INDEX.md is out of sync with design/.", file=sys.stderr)
                print("  python3 src/RimMandrake/Utils/doc_roster.py --write",
                      file=sys.stderr)
                print("  (not done for you: a hook that writes during PreToolUse "
                      "changes the tree under a commit whose pathspec is already "
                      "fixed, so the regenerated index would not be IN the commit.)",
                      file=sys.stderr)
        except Exception:
            pass
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception:
        sys.exit(0)                      # fail open, in code, never gating on a crash
