#!/usr/bin/env python3
"""PreToolUse/Bash hook — BLOCKS the four commits that would corrupt the ledger.

WHY A HOOK AND NOT A PARAGRAPH
==============================
This project has already proved twice that a `PreToolUse` hook changes behaviour where
prose does not. `git add -A` was forbidden in writing for two days and kept happening;
a hook stopped it the same afternoon.

⚠️ Everything here is about a NEW failure surface that did not exist before 2026-08-20.
Until then `queue/*.md` was hand-written and editing it was the job. Now it is rendered
from `infrastructure/state/ledger/events.jsonl`, and the same edit that used to be the
work is now a silent no-op — overwritten by the next `rimflow render`, with the effort
gone and nobody told.

WHAT IT BLOCKS
==============
1. **Committing an edit to a generated queue view.** The file says DO NOT EDIT at the
   top; this makes that true instead of hopeful.
2. **WRITING `events.jsonl` by any route that is not `rimflow`.** ⛔ The ledger's
   `flock` is ADVISORY — it protects writers that take it, and a shell redirect or an
   editor takes nothing. On this repo's 9p mount, concurrent writes without the lock
   lose five of every six events. `model.append()` is the only safe writer.

   🔴 **This is enforced at the WRITE, and it used to be enforced at the COMMIT. That
   was a defect, and it cost the project 358 events sitting on one disk.** Committing a
   changed ledger IS the normal case — every `rimflow` verb changes it — so a rule that
   denied "a commit naming the ledger while the ledger differs from HEAD" fired on every
   legitimate commit and never on the hand-edit it was aimed at. `git diff` cannot tell
   an append from an editor write; the tool call that made it can.
   ⚠️ Mentioning the path is not writing it. `grep`, `cat`, `sed -n`, `wc` and a commit
   pathspec all name the ledger and are all allowed — only redirects, in-place editors,
   copies over it and `open(..., 'w'|'a')` are refused. Over-blocking here is not the
   safe direction: a hook that wedges correct work gets disabled, and then nothing is
   guarded at all.
3. **Editing `items/<ID>.md` for an item another seat owns.** Filing work FOR another
   seat is normal and encouraged; changing their work is not, and four seats share one
   working tree so it is easy to do by accident.
4. **A new root-level `.md` that is not `TRANSIENT_*`.** The repo root is shared and
   already carries 342 markdown files; the naming rule is what keeps scratch findable
   and sweepable.

WHAT IT ONLY WARNS ABOUT
========================
`design/INDEX.md` drift. ⚠️ It is generated by `doc_roster.py --write`, and the plan
asked for a hook that REGENERATES it on commit. ⛔ That would be wrong: a PreToolUse
hook that writes files changes the tree underneath a `git commit` whose pathspec is
already fixed, so the regenerated index would NOT be in the commit — leaving the repo
dirty and the author believing it was handled. Warn, name the command, let a human run
it.

🔴 AND ONE THING THE PLAN ASKED FOR THAT IS DELIBERATELY NOT DONE
=================================================================
§8 says to make `warn_unclosed_queue_item.py` **block**. It must not. The owner ruled
2026-08-15 that it warns and never gates: *"a hook that refuses a commit costs more
than the miscount it prevents, and a seat that hits it mid-flow will work around it."*
That ruling has not been reversed, so the hook exits 1 — visible, non-blocking — and
the plan is corrected rather than obeyed.

FAIL-OPEN, STDLIB ONLY
======================
Blocks via `permissionDecision: deny` on stdout with exit 0, the same mechanism as
`block_blanket_git_stage.py`, so a crash can never gate a commit.

    python3 .claude/hooks/selftest_queue_lint.py
"""
import json
import os
import re
import subprocess
import sys

STATE = "infrastructure/state/"
LEDGER = STATE + "ledger/events.jsonl"
ITEMS = STATE + "items/"
QUEUE = STATE + "queue/"
GENERATED = "generated by rimflow render"
SEATS = ("DECIDE", "BUILD", "CHECK", "REP", "OWNER")


def deny(reason):
    print(json.dumps({"hookSpecificOutput": {
        "hookEventName": "PreToolUse",
        "permissionDecision": "deny",
        "permissionDecisionReason": reason}}))
    return 0


def git(root, *args):
    try:
        p = subprocess.run(["git", "-C", root, *args], capture_output=True,
                           text=True, timeout=8)
    except (OSError, subprocess.SubprocessError):
        return None
    return p.stdout if p.returncode == 0 else None


LEDGER_MSG = (
    "Blocked: %s is being written by something that is not `rimflow`.\n\n"
    "The ledger is APPEND-ONLY and `rimflow` is its only writer. Its lock is ADVISORY "
    "— it protects writers that take it, and a shell redirect or an editor takes "
    "nothing. On this repo's 9p mount, concurrent writes without that lock lost five "
    "of every six events and tore hundreds of lines in half (measured 2026-08-20).\n\n"
    "To change what the ledger says, add an event:\n"
    "    python3 src/RimMandrake/rimflow/cli.py <verb> …\n"
    "To correct one that is already in it, the OWNER appends an `admin` event. "
    "Nothing is ever removed.\n\n"
    "✅ COMMITTING the ledger is fine and is not what this refused — commit it after "
    "every turn, and push. Reading it with grep, cat or sed -n is fine too.")

LEDGER_PATH_RE = re.compile(r"[\w./\\-]*ledger/events\.jsonl")
# A redirect must land on the ledger IMMEDIATELY. ⚠️ "somewhere earlier in the command"
# is not good enough and was a false deny: `wc -l 2>/dev/null <ledger>` has a `>` before
# the path, and that `>` already has its own target.
REDIRECT_RE = re.compile(r">>?\s*['\"]?$")
# These take the file as an ARGUMENT, so anywhere in the same shell word-run counts.
# `dd of=` is spelled out because the path attaches to the operand, not the command.
ARG_WRITER_RE = re.compile(
    r"(?:\b(?:tee|cp|mv|rm|install|shred|truncate|ln)\b|\bof=|"
    r"\bsed\b[^|;&]*?\s-i)[^|;&]*$")
# python3 -c "open('…/events.jsonl', 'w')" — the mode sits AFTER the path.
WRITE_AFTER_RE = re.compile(r"^\s*['\"]?\s*,\s*['\"][wax]")


def ledger_write_target(cmd):
    """-> the ledger path this command WRITES, or None if it only mentions it.

    ⚠️ The distinction is the whole point. `git commit …/events.jsonl`, `grep x
    …/events.jsonl` and a path quoted inside a report all mention it; none of them
    write it. Blocking on mention is what broke this hook the first time.
    """
    for m in LEDGER_PATH_RE.finditer(cmd):
        before = cmd[max(0, m.start() - 80):m.start()]
        if REDIRECT_RE.search(before) or ARG_WRITER_RE.search(before):
            return m.group(0)
        if WRITE_AFTER_RE.match(cmd[m.end():m.end() + 12]):
            return m.group(0)
    return None


def is_generated(path):
    try:
        with open(path, encoding="utf-8", errors="replace") as fh:
            return GENERATED in fh.read(400)
    except OSError:
        return False


def my_seat(root):
    """-> the seat this window is, or None. ⚠️ None means DO NOT ENFORCE ownership.

    Guessing a seat here would block the wrong person's legitimate commit, and a hook
    that blocks correct work is one that gets disabled. Unknown seat = skip rule 3.
    """
    s = os.environ.get("RIMFLOW_SEAT") or os.environ.get("AGENT_SEAT")
    if s and s.strip().upper() in SEATS:
        return s.strip().upper()
    return None


def owners(root):
    """-> {item_id: owning_seat} from the ledger. {} if it cannot be read."""
    out = {}
    path = os.path.join(root, LEDGER)
    try:
        with open(path, encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    ev = json.loads(line)
                except ValueError:
                    return {}            # torn ledger: say nothing rather than guess
                if ev.get("event") == "file" and ev.get("id"):
                    out[ev["id"]] = ev.get("for")
                elif ev.get("event") == "spawn" and ev.get("name"):
                    out[ev["name"]] = ev.get("for")
                elif ev.get("event") == "reassign" and ev.get("id"):
                    out[ev["id"]] = ev.get("to")
    except OSError:
        return {}
    return out


def changed(root, paths):
    """Which of `paths` differ from HEAD in the WORKING TREE.

    ⚠️ The working tree, not the index: `git commit <path>` commits the tree at that
    path regardless of what is staged, which is the whole reason this repo commits by
    pathspec. Checking the index would miss exactly the case that matters.
    """
    out = git(root, "diff", "HEAD", "--name-only", "--", *paths)
    return [l.strip() for l in (out or "").splitlines() if l.strip()]


def main():
    try:
        ev = json.load(sys.stdin)
    except Exception:
        return 0
    ti = ev.get("tool_input") or {}

    # ---- 2. the ledger is append-only and tool-only, enforced at the WRITE ---
    # An editing tool names its target outright, so there is nothing to infer.
    if (ev.get("tool_name") or "") in ("Write", "Edit", "MultiEdit", "NotebookEdit"):
        fp = (ti.get("file_path") or ti.get("notebook_path") or "").replace("\\", "/")
        if fp.rstrip("/").endswith("ledger/events.jsonl"):
            return deny(LEDGER_MSG % fp)
        return 0                          # rules 1/3/4 are about commits, not edits

    cmd = ti.get("command") or ""
    hit = ledger_write_target(cmd)
    if hit:
        return deny(LEDGER_MSG % hit)

    if "git" not in cmd or "commit" not in cmd:
        return 0
    root = os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd()
    paths = re.findall(r"[\w./-]+\.(?:md|jsonl)", cmd)
    if not paths:
        return 0

    # ---- 1. a generated view is not a place to write ------------------------
    for p in paths:
        if QUEUE in p and is_generated(os.path.join(root, p)) and changed(root, [p]):
            return deny(
                "Blocked: %s is a GENERATED VIEW and you are committing an edit to "
                "it.\n\n"
                "It is rendered from infrastructure/state/ledger/events.jsonl, so this "
                "edit is not a small mistake — it is invisible. The next "
                "`rimflow render` overwrites it, the work is gone, and nobody is "
                "told.\n\n"
                "What you probably meant:\n"
                "  change an item's STATE   -> rimflow claim|start|block|close <ID>\n"
                "  change its PROSE         -> edit infrastructure/state/items/<ID>.md\n"
                "  file something new       -> rimflow file --for <SEAT> …\n"
                "  regenerate the view      -> python3 src/RimMandrake/rimflow/render.py"
                % p)

    # ---- 3. you may file for any seat; you may change only what you own -----
    seat = my_seat(root)
    if seat:
        own = owners(root)
        mine = [p for p in changed(root, [p for p in paths if ITEMS in p])]
        bad = []
        for p in mine:
            iid = os.path.basename(p)[:-3]
            holder = own.get(iid)
            if holder and holder != seat and seat != "OWNER":
                bad.append((iid, holder))
        if bad:
            return deny(
                "Blocked: %s is editing %d item(s) owned by another seat.\n\n%s\n\n"
                "Filing work FOR another seat is normal and encouraged. Changing their "
                "work is refused — four seats share one working tree, so this is easy "
                "to do by accident and impossible to notice afterwards.\n\n"
                "File instead:  rimflow file --for %s --title \"…\" --kind task <ID>\n"
                "Or, if the owner is genuinely wrong, say so in "
                "infrastructure/state/queue/HUMAN.md."
                % (seat, len(bad),
                   "\n".join("    %-44s belongs to %s" % (i, h) for i, h in bad),
                   bad[0][1]))

    # ---- 4. the repo root is shared -----------------------------------------
    tracked = set((git(root, "ls-files") or "").split())
    for p in paths:
        if "/" in p or not p.endswith(".md"):
            continue
        if p in tracked or os.path.basename(p).startswith("TRANSIENT_"):
            continue
        if p.isupper() or p in ("README.md", "CLAUDE.md"):
            continue
        return deny(
            "Blocked: %s is a new markdown file at the repo root and is not named "
            "TRANSIENT_*.\n\n"
            "The root already carries 342 markdown files. The naming rule is what "
            "keeps scratch findable and sweepable — `rimflow sweep --transient` lists "
            "stale ones, and a file outside the convention is invisible to it "
            "forever.\n\n"
            "  scratch, analysis, a one-off report  ->  TRANSIENT_%s\n"
            "  a design document                    ->  design/…\n"
            "  project state                        ->  infrastructure/state/…" % (p, p))

    # ---- warn only: the generated index drifts ------------------------------
    if any(p.startswith("design/") for p in paths):
        try:
            r = subprocess.run(
                [sys.executable, os.path.join(root, "src/RimMandrake/Utils/doc_roster.py")],
                capture_output=True, text=True, cwd=root, timeout=30)
            if r.returncode:
                print("⚠ design/INDEX.md is out of sync with design/.", file=sys.stderr)
                print("  python3 src/RimMandrake/Utils/doc_roster.py --write",
                      file=sys.stderr)
                print("  (not done for you: a hook that writes during PreToolUse "
                      "changes the tree under a commit whose pathspec is already "
                      "fixed, so the regenerated index would not be IN the commit.)",
                      file=sys.stderr)
        except Exception:
            pass
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception:
        sys.exit(0)                      # fail open, in code, never gating on a crash
