#!/usr/bin/env python3
"""Selftest for queue_lint.py — run after ANY change to it.

This hook BLOCKS, which makes both failure directions expensive and opposite:

  FALSE ALLOW   an edit to a generated view is committed, then silently overwritten by
                the next render. The work is gone and nobody is told — the exact
                failure the hook exists to prevent.
  FALSE DENY    a seat is wedged mid-task on a legitimate commit. Noticed in seconds,
                and then the hook gets disabled, which converts it into a false allow
                for everything, forever.

⚠️ So the ALLOW cases below matter at least as much as the DENY ones, and several exist
only to pin behaviour that would otherwise drift into over-blocking: an UNCHANGED
generated file, a hand-written archive, an item you own, an already-tracked root file.

Every case runs against a real throwaway git repo, because the hook's whole job is
reading `git diff HEAD` — a test that stubbed that out would not exercise it.

    python3 .claude/hooks/selftest_queue_lint.py
"""
import json
import os
import shutil
import subprocess
import sys
import tempfile

HOOK = os.path.join(os.path.dirname(os.path.abspath(__file__)), "queue_lint.py")
DENY, ALLOW = "deny", "allow"

GEN = ("<!-- generated by rimflow render — derived, do not edit -->\n"
       "# BUILD — generated queue view\n\n## SANDSTORM_WEATHER_TUNING_1 t\nstate: ready\n")
HAND = "# DECIDE archive\n\n## D55 A legacy item\nstate: done\n"
LEDGER = (
    '{"ts":"t","seat":"DECIDE","event":"file","id":"MINE_ITEM_HERE_1",'
    '"title":"t","kind":"task","for":"BUILD"}\n'
    '{"ts":"t","seat":"DECIDE","event":"file","id":"THEIRS_ITEM_HERE_1",'
    '"title":"t","kind":"task","for":"CHECK"}\n')

BASE = {
    "infrastructure/state/queue/BUILD.md": GEN,
    "infrastructure/state/queue/DECIDE_ARCHIVE.md": HAND,
    "infrastructure/state/ledger/events.jsonl": LEDGER,
    "infrastructure/state/items/MINE_ITEM_HERE_1.md": "## spec\nx\n",
    "infrastructure/state/items/THEIRS_ITEM_HERE_1.md": "## spec\nx\n",
    "TRANSIENT_notes.md": "scratch\n",
    "README.md": "# repo\n",
}


def git(root, *a):
    subprocess.run(["git", "-C", root, *a], capture_output=True, text=True, check=True)


def run(edits, cmd, seat="BUILD", new_files=None):
    root = tempfile.mkdtemp(prefix="selftest_ql_")
    try:
        for rel, body in BASE.items():
            full = os.path.join(root, rel)
            os.makedirs(os.path.dirname(full) or root, exist_ok=True)
            open(full, "w", encoding="utf-8").write(body)
        git(root, "init", "-q")
        git(root, "config", "user.email", "t@t")
        git(root, "config", "user.name", "t")
        git(root, "add", "-A")
        git(root, "commit", "-qm", "base")
        for rel, body in (edits or {}).items():
            full = os.path.join(root, rel)
            os.makedirs(os.path.dirname(full) or root, exist_ok=True)
            open(full, "w", encoding="utf-8").write(body)
        for rel in (new_files or []):
            open(os.path.join(root, rel), "w", encoding="utf-8").write("new\n")
        env = dict(os.environ, CLAUDE_PROJECT_DIR=root)
        env.pop("AGENT_SEAT", None)
        if seat:
            env["RIMFLOW_SEAT"] = seat
        else:
            env.pop("RIMFLOW_SEAT", None)
        p = subprocess.run([sys.executable, HOOK],
                           input=json.dumps({"tool_input": {"command": cmd}}),
                           capture_output=True, text=True, env=env, cwd=root,
                           timeout=30)
        out = p.stdout.strip()
        if out:
            try:
                d = json.loads(out)["hookSpecificOutput"]
                return d["permissionDecision"], d["permissionDecisionReason"]
            except Exception:
                pass
        return ALLOW, p.stderr
    finally:
        shutil.rmtree(root, ignore_errors=True)


Q = "infrastructure/state/queue"
L = "infrastructure/state/ledger/events.jsonl"
I = "infrastructure/state/items"

CASES = [
    # ---- 1. a generated view is not a place to write -----------------------
    ("DENY  editing a generated queue view", DENY, "render",
     {Q + "/BUILD.md": GEN + "\n## MY_HAND_EDIT_1 x\nstate: ready\n"},
     "git commit %s/BUILD.md -m x" % Q, "BUILD", None),
    ("ALLOW an UNCHANGED generated view in the pathspec", ALLOW, None,
     {}, "git commit %s/BUILD.md -m x" % Q, "BUILD", None),
    ("ALLOW editing a hand-written ARCHIVE — still the source", ALLOW, None,
     {Q + "/DECIDE_ARCHIVE.md": HAND + "\n## D56 x\nstate: ready\n"},
     "git commit %s/DECIDE_ARCHIVE.md -m x" % Q, "BUILD", None),

    # ---- 2. the ledger is append-only and tool-only ------------------------
    ("DENY  hand-editing events.jsonl", DENY, "append-only",
     {L: LEDGER + '{"ts":"t","seat":"BUILD","event":"note","id":"X_Y_1","text":"z"}\n'},
     "git commit %s -m x" % L, "BUILD", None),
    ("ALLOW committing an UNCHANGED ledger alongside other work", ALLOW, None,
     {}, "git commit %s -m x" % L, "BUILD", None),

    # ---- 3. file for any seat; change only what you own --------------------
    ("DENY  editing another seat's item file", DENY, "belongs to",
     {I + "/THEIRS_ITEM_HERE_1.md": "## spec\nedited\n"},
     "git commit %s/THEIRS_ITEM_HERE_1.md -m x" % I, "BUILD", None),
    ("ALLOW editing your OWN item file", ALLOW, None,
     {I + "/MINE_ITEM_HERE_1.md": "## spec\nedited\n"},
     "git commit %s/MINE_ITEM_HERE_1.md -m x" % I, "BUILD", None),
    ("ALLOW the OWNER editing anyone's item", ALLOW, None,
     {I + "/THEIRS_ITEM_HERE_1.md": "## spec\nedited\n"},
     "git commit %s/THEIRS_ITEM_HERE_1.md -m x" % I, "OWNER", None),
    # ⚠️ Unknown seat must NOT enforce ownership. Guessing would block the wrong
    # person's correct commit, and a hook that blocks correct work gets disabled.
    ("ALLOW when the seat is unknown — never guess and block", ALLOW, None,
     {I + "/THEIRS_ITEM_HERE_1.md": "## spec\nedited\n"},
     "git commit %s/THEIRS_ITEM_HERE_1.md -m x" % I, None, None),

    # ---- 4. the repo root is shared ---------------------------------------
    ("DENY  a new root .md that is not TRANSIENT_*", DENY, "TRANSIENT",
     {}, "git commit analysis.md -m x", "BUILD", ["analysis.md"]),
    ("ALLOW a new TRANSIENT_ root file", ALLOW, None,
     {}, "git commit TRANSIENT_new.md -m x", "BUILD", ["TRANSIENT_new.md"]),
    ("ALLOW an already-tracked root file", ALLOW, None,
     {"README.md": "# repo edited\n"}, "git commit README.md -m x", "BUILD", None),

    # ---- not our business --------------------------------------------------
    ("ALLOW a normal src commit", ALLOW, None,
     {}, "git commit src/foo.py -m x", "BUILD", None),
    ("ALLOW anything that is not a commit", ALLOW, None,
     {L: LEDGER + '{"x":1}\n'}, "git status --porcelain", "BUILD", None),
]


def main():
    fails = 0
    for name, want, needle, edits, cmd, seat, new in CASES:
        got, reason = run(edits, cmd, seat, new)
        ok = got == want and (not needle or needle.lower() in (reason or "").lower())
        print("%-5s %s" % ("ok" if ok else "FAIL", name))
        if not ok:
            fails += 1
            print("        got=%s want=%s\n        %s"
                  % (got, want, (reason or "")[:300].replace("\n", "\n        ")))
    print("\n%d/%d passed" % (len(CASES) - fails, len(CASES)))
    return 1 if fails else 0


if __name__ == "__main__":
    sys.exit(main())
