#!/usr/bin/env python3
"""PreToolUse/Bash hook — warn when a commit removes a queue item with no `Closes:`.

WHY
===
Measured 2026-08-14: 124 item IDs had ever existed, 51 were still filed, and
`state: done` had been written three times in the whole project history. Items
did not get closed, they got deleted or renumbered, so the board's numerator
could never rise while its denominator shrank. `derive_matrix.py` now counts
closed work from a `Closes: <ID>` trailer instead — read back out of the closing
commit's parent, where the item still exists.

That only works if the trailer is actually written. A commit that removes an
item heading and forgets it loses the record permanently: the next commit's
parent no longer holds the item, so nothing can recover its row afterwards.

WARN, NOT BLOCK — owner's call, 2026-08-15
==========================================
The standing order is to commit and push the moment an item is done. A hook that
refuses a commit costs more than the miscount it prevents, and a seat that hits
it mid-flow will work around it. So this never gates.

⚠️ Revised 2026-08-20: it now exits 1, not 0. In Claude Code a PreToolUse hook
blocks on exit 2 and ONLY on 2; exit 1 is a non-blocking error whose stderr is
shown to the user in red and then the command runs anyway. At exit 0 with the old
`2>/dev/null || true` wrapper in settings.json, this warning was discarded twice
over and no one had ever seen it. Warn-not-gate is intact; silence was not the
ruling. The wrapper is gone and the fail-open lives in `__main__` instead, which
also guarantees a crash can never exit 2 by accident.

WHAT IT CHECKS
==============
For `git commit` naming a path under infrastructure/state/queue/, diff the
working tree against HEAD, collect every `## <ID>` heading being REMOVED, and
warn about any whose ID does not appear in a `Closes:` trailer in the -m text.

A heading that is removed AND re-added — a retitle — is not a removal and does
not warn. `state: dropped` needs no exemption: dropping keeps the item in the
queue with a reason line, so its heading is never removed at all.
"""
import json
import os
import re
import subprocess
import sys

QUEUE = "infrastructure/state/queue/"
# ⚠️ The character class MUST match `derive_matrix.py`'s CLOSES_RE, which is what
# actually counts closures. It did not: this file said `[A-Z][A-Z0-9-]*` while the
# board said `[A-Za-z][A-Za-z0-9._-]*`, so from the 2026-08-20 rename to
# THREE_DESCRIPTIVE_WORDS_# every ID stopped matching here — `INHABITED_DISPLACED_
# POOL_1` has a word character on both sides of each `_`, so the trailing `\b`
# never fired and the heading was not seen as removed at all. The hook went
# silent on exactly the IDs it was rewritten to protect. Keep the two classes
# identical; if one changes, change both.
ID = r"[A-Za-z][A-Za-z0-9._-]*"
HEADING = re.compile(r"^([+-])## (%s)" % ID)
CLOSES = re.compile(r"^Closes:\s*(%s)\s*$" % ID, re.M)


GENERATED = "generated by rimflow render"


def _is_generated(path):
    try:
        with open(path, encoding="utf-8", errors="replace") as fh:
            return GENERATED in fh.read(400)
    except OSError:
        return False                        # unreadable: treat as hand-written, warn


def git(root, *args):
    try:
        p = subprocess.run(["git", "-C", root, *args],
                           capture_output=True, text=True, timeout=8)
    except (OSError, subprocess.SubprocessError):
        return None
    return p.stdout if p.returncode == 0 else None


def main():
    try:
        ev = json.load(sys.stdin)
    except Exception:
        return 0
    cmd = (ev.get("tool_input") or {}).get("command") or ""
    if "git" not in cmd or "commit" not in cmd:
        return 0

    root = os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd()
    paths = [p for p in re.findall(r"[\w./-]+\.md", cmd) if QUEUE in p]
    # 🔴 A GENERATED VIEW IS NOT A RECORD, so a heading leaving one loses nothing.
    # From 2026-08-20 the truth is `infrastructure/state/ledger/events.jsonl` and most
    # of `queue/*.md` is rendered from it. This hook's whole premise — "the item is
    # about to leave the queue and nothing else holds it" — is false for those files:
    # every render legitimately removes and re-adds headings, and the first render
    # after the migration named 18 items at once.
    # ⚠️ Left unfixed it would fire on every render commit, and a warning that is
    # always wrong is a warning people learn to ignore — which would silence it for
    # the ARCHIVES, where it is still the only thing standing between a deleted item
    # and a permanently unrecoverable row.
    paths = [p for p in paths if not _is_generated(os.path.join(root, p))]
    if not paths:
        return 0

    # The tree, not the index: `git commit <path>` commits the working tree at
    # that path regardless of what is staged.
    diff = git(root, "diff", "HEAD", "--", *paths)
    if not diff:
        return 0
    removed, added = set(), set()
    for ln in diff.splitlines():
        m = HEADING.match(ln)
        if m:
            (removed if m.group(1) == "-" else added).add(m.group(2))
    gone = removed - added                      # a retitle is not a removal
    if not gone:
        return 0

    # `state: dropped` needs no exemption: dropping KEEPS the item in the queue
    # with a reason line, so its heading never appears as a removal here.
    missing = sorted(gone - set(CLOSES.findall(cmd)))
    if not missing:
        return 0

    print("⚠ queue item(s) removed with no `Closes:` trailer: %s"
          % ", ".join(missing), file=sys.stderr)
    print("  The item is about to leave the queue. Without the trailer the board",
          file=sys.stderr)
    print("  cannot count it and its row cannot be recovered later.", file=sys.stderr)
    print("  Add to the commit message:  Closes: %s" % missing[0], file=sys.stderr)
    print("  Dropping it instead? Set `state: dropped` with one line of why.",
          file=sys.stderr)
    # Exit 1, NOT 2. In Claude Code a PreToolUse hook blocks on 2 and only on 2;
    # 1 is a non-blocking error whose stderr is shown to the user in red and then
    # the command runs anyway. So this stays the owner's warn-not-gate (2026-08-15)
    # while actually being SEEN — at exit 0 the message was swallowed by the
    # `2>/dev/null || true` wrapper in settings.json and nobody ever read it.
    return 1


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception:
        # Fail open, in code rather than in the shell wrapper: a hook that
        # crashes must never cost a commit, and must never exit 2 by accident.
        sys.exit(0)
