#!/usr/bin/env python3
"""Turn the naming table in creature_names_ashkarr.md into a label patch.

⚠️ The DOC is the single source. This reads it rather than carrying its own copy, so the
two cannot drift.
🔴 Only `<label>` is touched. defNames are referenced by quests, incidents and other mods'
patches; renaming one breaks them silently and there is no error.
"""
import csv, os, re, sys
FA = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(FA)))
DOC = os.path.join(ROOT, 'design', 'Jawa', 'worldbuilding', 'creature_names_ashkarr.md')
OUT = os.path.join(FA, 'CreatureNames_Ashkarr.xml')

def main():
    # label -> defName, from the cast. Two distinct creatures can share a label
    # (the cast's `label` column is not unique) — track every collision so an
    # ambiguous rename is refused and reported, never silently applied to
    # whichever defName happened to appear first in the CSV.
    lab2def = {}
    collisions = {}
    for r in csv.DictReader(open(os.path.join(FA, 'cast_assignment.csv'), encoding='utf-8')):
        if r['label']:
            key = r['label'].strip().lower()
            entry = (r['defName'], r['mod'])
            if key in lab2def and lab2def[key][0] != entry[0]:
                collisions.setdefault(key, {lab2def[key][0]}).add(entry[0])
            lab2def.setdefault(key, entry)

    pairs, unmatched, ambiguous = [], [], []
    for line in open(DOC, encoding='utf-8'):
        m = re.match(r'\|\s*([^|]+?)\s*\|\s*\*\*([a-z]+)\*\*\s*\|', line)
        if not m:
            continue
        old, new = m.group(1).strip(), m.group(2).strip()
        if old.lower() in collisions:
            ambiguous.append((old, sorted(collisions[old.lower()]))); continue
        hit = lab2def.get(old.lower())
        if not hit:
            unmatched.append(old); continue
        pairs.append((hit[0], old, new, hit[1]))

    parts = ['<?xml version="1.0" encoding="utf-8"?>', '<Patch>',
             '  <!-- GENERATED by design/Jawa/fauna/gen_name_patch.py from',
             '       design/Jawa/worldbuilding/creature_names_ashkarr.md - do not hand-edit.',
             '',
             '       Owner 2026-08-22: replace the Latin binomials with Star Wars-register names.',
             '       Coined against Alien_Bestiary.md section 1 - clade roots, so related creatures',
             '       share morphemes and the ecosystem reads as evolved rather than assembled.',
             '',
             '       🔴 LABEL ONLY. No defName is touched. -->', '']
    # 🔴 CONDITIONAL, NOT A BARE REPLACE - CREATURE_NAMES_APPLY_1, BUILD 2026-08-22.
    # A PatchOperationReplace whose xpath matches nothing is a RED ERROR every launch,
    # not a silent no-op, so 41 bare ones is 41 errors the day a donor mod drops a
    # creature or is switched off.
    # ⚠️ No MayRequire is emitted and none is wanted: the conditional tests the DEF
    # rather than the mod, which is strictly stronger. A mod can be installed and
    # still have renamed or removed the creature - `MayRequire` passes on intent,
    # this passes on reality.
    # 🔑 No <nomatch>: a creature that is not there needs no name.
    for dn, old, new, mod in sorted(pairs):
        xp = f'/Defs/ThingDef[defName="{dn}"]/label'
        parts.append(f'  <Operation Class="PatchOperationConditional">')
        parts.append(f'    <xpath>{xp}</xpath>')
        parts.append(f'    <match Class="PatchOperationReplace">')
        parts.append(f'      <xpath>{xp}</xpath>')
        parts.append(f'      <value><label>{new}</label></value>')
        parts.append(f'    </match>')
        parts.append(f'  </Operation>   <!-- was "{old}" - {mod} -->')
        parts.append('')
    parts.append('</Patch>')
    open(OUT, 'w', encoding='utf-8').write('\n'.join(parts))
    print(f"wrote {OUT}: {len(pairs)} renames")
    if unmatched:
        print(f"⚠️ {len(unmatched)} table rows matched no cast creature: {unmatched}")
        print("   These are NOT missing defs. They are names authored against an older cast:")
        print("   the cast was re-run after the naming doc was written (density scaling, then")
        print("   diet constraints) and these creatures fell out of it. The names are held in")
        print("   reserve - if the creature returns to a cast, its name is already coined.")
        print("   🔴 If this list is ever non-empty, RE-READ the doc against the cast before")
        print("      assuming a def is broken.")
    if ambiguous:
        print(f"🔴 {len(ambiguous)} table row(s) refused — the old label is shared by more than")
        print("   one defName in the cast, and there is no way to tell which one the doc means:")
        for old, defnames in ambiguous:
            print(f"     {old!r} -> {defnames}")
        print("   Rename one side in the CSV or the doc so the label is unique, then re-run.")

if __name__ == '__main__':
    main()
