#!/usr/bin/env python3
"""Turn the naming table in creature_names_ashkarr.md into a label patch.

⚠️ The DOC is the single source. This reads it rather than carrying its own copy, so the
two cannot drift.
🔴 Only `<label>` is touched. defNames are referenced by quests, incidents and other mods'
patches; renaming one breaks them silently and there is no error.
"""
import csv, os, re, sys
FA = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(FA)))
DOC = os.path.join(ROOT, 'design', 'Jawa', 'worldbuilding', 'creature_names_ashkarr.md')
OUT = os.path.join(FA, 'CreatureNames_Ashkarr.xml')

def main():
    # label -> defName, from the cast
    lab2def = {}
    for r in csv.DictReader(open(os.path.join(FA, 'cast_assignment.csv'), encoding='utf-8')):
        if r['label']:
            lab2def.setdefault(r['label'].strip().lower(), (r['defName'], r['mod']))

    pairs, unmatched = [], []
    for line in open(DOC, encoding='utf-8'):
        m = re.match(r'\|\s*([^|]+?)\s*\|\s*\*\*([a-z]+)\*\*\s*\|', line)
        if not m:
            continue
        old, new = m.group(1).strip(), m.group(2).strip()
        hit = lab2def.get(old.lower())
        if not hit:
            unmatched.append(old); continue
        pairs.append((hit[0], old, new, hit[1]))

    parts = ['<?xml version="1.0" encoding="utf-8"?>', '<Patch>',
             '  <!-- GENERATED by design/Jawa/fauna/gen_name_patch.py from',
             '       design/Jawa/worldbuilding/creature_names_ashkarr.md - do not hand-edit.',
             '',
             '       Owner 2026-08-22: replace the Latin binomials with Star Wars-register names.',
             '       Coined against Alien_Bestiary.md section 1 - clade roots, so related creatures',
             '       share morphemes and the ecosystem reads as evolved rather than assembled.',
             '',
             '       🔴 LABEL ONLY. No defName is touched. -->', '']
    # 🔴 CONDITIONAL, NOT A BARE REPLACE - CREATURE_NAMES_APPLY_1, BUILD 2026-08-22.
    # A PatchOperationReplace whose xpath matches nothing is a RED ERROR every launch,
    # not a silent no-op, so 41 bare ones is 41 errors the day a donor mod drops a
    # creature or is switched off.
    # ⚠️ No MayRequire is emitted and none is wanted: the conditional tests the DEF
    # rather than the mod, which is strictly stronger. A mod can be installed and
    # still have renamed or removed the creature - `MayRequire` passes on intent,
    # this passes on reality.
    # 🔑 No <nomatch>: a creature that is not there needs no name.
    for dn, old, new, mod in sorted(pairs):
        xp = f'/Defs/ThingDef[defName="{dn}"]/label'
        parts.append(f'  <Operation Class="PatchOperationConditional">')
        parts.append(f'    <xpath>{xp}</xpath>')
        parts.append(f'    <match Class="PatchOperationReplace">')
        parts.append(f'      <xpath>{xp}</xpath>')
        parts.append(f'      <value><label>{new}</label></value>')
        parts.append(f'    </match>')
        parts.append(f'  </Operation>   <!-- was "{old}" - {mod} -->')
        parts.append('')
    parts.append('</Patch>')
    open(OUT, 'w', encoding='utf-8').write('\n'.join(parts))
    print(f"wrote {OUT}: {len(pairs)} renames")
    if unmatched:
        print(f"⚠️ {len(unmatched)} table rows matched no cast creature: {unmatched}")

if __name__ == '__main__':
    main()
