"""Slow every warhead in the galaxy: the torpedo rule (L13c).

Measured: missile/rocket projectiles travel at speed 50 -- exactly the speed of
a blaster bolt, and the median of all 537 projectiles. A warhead indistinguish-
able from a bullet is the hypersonic missile L13b says this galaxy never built.

Slowing them is what makes them fit:
  * slow enough to pass a deflector screen  (L6: screens stop FAST things)
  * slow enough to see, dodge, or shoot down -- the counterplay that makes a
    weapon with no hard counter (L13) tolerable
  * so only worth firing at something that CANNOT dodge: vehicles, emplacements,
    shield generators, VAST creatures

A colonist moves ~4.6 cells/sec. At speed 50 a warhead crosses 20 cells in 0.4s
-- no reaction possible. At 14 it takes 1.4s and the target can cover ~6 cells.
That is the difference between a cutscene and a decision.

Blast values are deliberately NOT touched. Explosions are meant to stay
devastating against every form of protection (L13); what was wrong was the
delivery, not the warhead.
"""
import collections
import io
import os
import sys

sys.path.insert(0, r"G:\My Drive\Personal\Rimworld\Utils")
from def_diff import iter_live_defs
from def_inventory import build as build_offline, D_CONFIG, D_WORKSHOP, D_LOCAL, D_DATA

DUMP = (r"C:\Users\Mandrake\AppData\LocalLow\Ludeon Studios"
        r"\RimWorld by Ludeon Studios\DefDump\defs\ThingDef.json")
OUT = (r"G:\My Drive\Personal\Rimworld\custom_patches\Jawa_Armoury\Patches"
       r"\Armoury_TorpedoSpeed.xml")

MARKERS = ("rocket", "missile", "torpedo")
# Anything already this slow is left alone -- some mods (whistling birds,
# seekers) already got it right, and there is no reason to overwrite good work.
ALREADY_SLOW = 26
HEAVY = 12      # anti-vehicle / anti-emplacement: ponderous and unmistakable
LIGHT = 18      # personal launchers, wrist rockets: quicker but still duckable

targets = {}
for d in iter_live_defs(DUMP):
    f = d.get("fields") or {}
    pr = f.get("projectile")
    if not isinstance(pr, dict):
        continue
    dn = d.get("defName") or ""
    b = dn.lower()
    if not any(m in b for m in MARKERS):
        continue
    sp = pr.get("speed")
    if not isinstance(sp, (int, float)) or sp <= ALREADY_SLOW:
        continue
    rad = pr.get("explosionRadius") or 0
    # Big blast == heavy weapon == slowest. Small blast == personal == quicker.
    targets[dn] = (sp, HEAVY if rad >= 2.5 else LIGHT, d.get("modName") or "?")

print("warheads to slow: %d" % len(targets))

ds = build_offline(D_CONFIG, D_WORKSHOP, D_LOCAL, D_DATA, types=("ThingDef",))


def declarer(defname):
    """Patches hit raw XML before inheritance: aim at whoever declares speed."""
    rec = ds.get("ThingDef", defname)
    if rec is None:
        return None, None
    if rec.own.find("projectile/speed") is not None:
        return defname, "defName"
    seen, pn = set(), rec.parentName
    while pn and pn not in seen:
        seen.add(pn)
        pel = ds.by_name.get(pn)
        pel = getattr(pel, "own", pel)
        if pel is None:
            return None, None
        if pel.find("projectile/speed") is not None:
            return pn, "Name"
        pn = pel.get("ParentName")
    return None, None


NL = "\n"
by_mod, skipped = collections.defaultdict(list), []
for dn, (old, new, mod) in sorted(targets.items()):
    owner, attr = declarer(dn)
    if owner is None:
        skipped.append(dn)
        continue
    sel = '[defName="%s"]' % owner if attr == "defName" else '[@Name="%s"]' % owner
    by_mod[mod].append(
        '        <!-- %s : speed %s -> %d -->' % (dn, old, new) + NL +
        '        <li Class="PatchOperationReplace">' + NL +
        '          <xpath>/Defs/ThingDef' + sel + '/projectile/speed</xpath>' + NL +
        '          <value><speed>%d</speed></value>' % new + NL +
        '        </li>' + NL)

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with io.open(OUT, "w", encoding="utf-8") as fh:
    fh.write('<?xml version="1.0" encoding="utf-8"?>' + NL)
    fh.write('<!-- Torpedoes: warheads drift, so they can be dodged (L13c).' + NL)
    fh.write('     GENERATED by custom_patches/Jawa_Armoury/Source/gen_torpedo_speed.py. Do not hand-edit.' + NL)
    fh.write('     Blast is deliberately untouched: explosions stay devastating' + NL)
    fh.write('     against every protection (L13). Only the delivery changes. -->' + NL)
    fh.write('<Patch>' + NL)
    for mod, ops in sorted(by_mod.items()):
        fh.write(NL + '  <Operation Class="PatchOperationFindMod">' + NL)
        fh.write('    <mods><li>' + mod + '</li></mods>' + NL)
        fh.write('    <match Class="PatchOperationSequence">' + NL)
        fh.write('      <operations>' + NL)
        for o in ops:
            fh.write(o)
        fh.write('      </operations>' + NL)
        fh.write('    </match>' + NL + '  </Operation>' + NL)
    fh.write(NL + '</Patch>' + NL)

print("ops %d across %d mods" % (sum(len(v) for v in by_mod.values()), len(by_mod)))
if skipped:
    print("skipped (speed not declared anywhere findable): %d %s"
          % (len(skipped), skipped[:5]))
for dn, (old, new, mod) in sorted(targets.items(), key=lambda kv: kv[1][1])[:12]:
    print("   %-40s %3s -> %2d   %s" % (dn[:40], old, new, mod[:22]))
