#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""gen_creature_explorer.py — the ANY-AXIS creature scatter explorer.

Writes design/Jawa/worldbuilding/review/viz/creature_explorer.html: a single
self-contained offline page where the owner picks ANY two register fields as
axes, colors/filters by mod/kind/biome/cut, hovers to see the creature's actual
sprite (relative path into ../creature_art/), and CLICKS to collect creatures
into a basket he can copy out as JSON for filing queue items.

This is the review-sheet counterpart for DISTRIBUTIONS: the register sheet
answers "is this one creature right?", this page answers "which creatures are
where in parameter space, and who is the outlier?". It captures no decisions —
the basket is a collection aid, persisted only in localStorage — so it is NOT a
decisions-file artifact and carries no lock.

Known reference laws are drawn automatically when the axis pair matches:
  meatAmount  vs bodySize : engine linear 140·bs + doctrine quadratic 140·bs²
  bestHit     vs bodySize : Law-3 band (12–15 × bodySize)
  drawSizeMax vs bodySize : vanilla sprite law 1.9·√bs

Data honesty: every number is copied verbatim from creature_register_rows.json
(see gen_creature_register.py for provenance); derived fields (bestHit,
biomeSpread, kPerBS) state their formula in the axis label. Missing = null,
never 0; null rows drop out of the plot for that axis pair and the drop count
is shown.

Run from repo root:
  python3 design/Jawa/worldbuilding/review/gen_creature_explorer.py
Then open (Windows):
  D:\\Luke\\dev\\Rimworld\\design\\Jawa\\worldbuilding\\review\\viz\\creature_explorer.html
"""
import json, os, html

HERE = os.path.dirname(os.path.abspath(__file__))
ROWS = os.path.join(HERE, "creature_register_rows.json")
OUT = os.path.join(HERE, "viz", "creature_explorer.html")

D = json.load(open(ROWS))


def slim(r):
    tools = r.get("tools") or []
    best = max((t.get("power") or 0) for t in tools) if tools else None
    ds = r.get("drawSize")
    art = r.get("art") or {}
    return dict(
        d=r["defName"], l=r.get("label"), m=r.get("mod"), g=r.get("group"),
        k=r.get("kindOf"),
        bs=r.get("bodySize"), hs=r.get("healthScale"), sp=r.get("moveSpeed"),
        wd=r.get("wildness"), tr=r.get("trainability"),
        mt=r.get("meatAmount"), lt=r.get("leatherAmount"),
        ar=r.get("armorSharp"),
        dw=(max(v for v in ds if isinstance(v, (int, float)))
            if isinstance(ds, (list, tuple)) and any(isinstance(v, (int, float)) for v in ds) else None),
        bh=best, tc=r.get("topCommonality"),
        nb=sum(1 for b in r.get("biomes") or [] if (b.get("commonality") or 0) > 0),
        bio=sorted({b["biomeDef"] for b in r.get("biomes") or [] if (b.get("commonality") or 0) > 0}),
        cut=bool(r.get("cut")), zz=bool(r.get("commonalityZeroed")),
        px=art.get("pxPerCell"), sprite=art.get("detail"),
    )


data = [slim(r) for r in D["rows"]]
meta = dict(built=D["meta"]["builtUtc"], dumpMods=D["meta"]["dumpMods"], n=len(data))

TEMPLATE = r"""<!-- GENERATED by gen_creature_explorer.py — edit the generator, not this file -->
<title>Creature Explorer</title>
<style>
:root { --bg:#f4f2ec; --panel:#fff; --ink:#222; --mut:#777; --acc:#3b6fb5; --ban:#c0392b; }
body { background:var(--bg); color:var(--ink); font:13px/1.45 system-ui,sans-serif; margin:0; }
#wrap { display:flex; height:100vh; }
#side { width:270px; min-width:270px; padding:10px 12px; overflow-y:auto; background:var(--panel); border-right:1px solid #ddd; }
#main { flex:1; display:flex; flex-direction:column; min-width:0; }
#plotbox { flex:1; position:relative; min-height:0; }
canvas { position:absolute; inset:0; }
h1 { font-size:15px; margin:2px 0 8px; }
h2 { font-size:12px; margin:12px 0 4px; text-transform:uppercase; letter-spacing:.05em; color:var(--mut); }
select, input[type=text] { width:100%; box-sizing:border-box; padding:3px; margin:1px 0 5px; font-size:12px; }
label.inline { display:inline-flex; align-items:center; gap:4px; margin-right:8px; font-size:12px; }
#tip { position:absolute; pointer-events:none; background:#fff; border:1px solid #999; border-radius:4px;
       padding:6px 8px; font-size:12px; max-width:270px; box-shadow:0 2px 8px rgba(0,0,0,.18); display:none; z-index:5; }
#tip img { max-width:96px; max-height:96px; image-rendering:auto; display:block; margin-bottom:4px; background:#eee; }
#tip .nm { font-weight:600; } #tip .mut { color:var(--mut); }
#basket { border-top:1px solid #ddd; background:var(--panel); padding:6px 12px; max-height:170px; overflow-y:auto; font-size:12px; }
#basket .item { display:inline-block; background:#eef3fa; border:1px solid #c6d6ea; border-radius:3px;
                padding:1px 6px; margin:2px; cursor:pointer; }
#basket .item:hover { background:#f8dcd6; border-color:var(--ban); }
button { font-size:12px; padding:3px 8px; margin-right:6px; }
#status { padding:3px 12px; font-size:11.5px; color:var(--mut); background:var(--panel); border-top:1px solid #eee; }
.note { font-size:11px; color:var(--mut); }
</style>
<div id="wrap">
<div id="side">
  <h1>Creature Explorer</h1>
  <div class="note">__META_NOTE__<br>Hover a point for the sprite; click to add to the basket; click a basket chip to remove.</div>
  <h2>Axes</h2>
  X <select id="ax"></select>
  <label class="inline"><input type="checkbox" id="axlog"> log X</label>
  <div style="height:4px"></div>
  Y <select id="ay"></select>
  <label class="inline"><input type="checkbox" id="aylog"> log Y</label>
  <label class="inline"><input type="checkbox" id="laws" checked> reference laws (when the pair has one)</label>
  <h2>Color by</h2>
  <select id="colorby">
    <option value="k">creature kind</option>
    <option value="m">source mod (top 12)</option>
    <option value="cut">cut status</option>
  </select>
  <h2>Filters</h2>
  <label class="inline"><input type="checkbox" id="liveonly" checked> live only (not cut / zeroed)</label>
  <div style="height:4px"></div>
  biome <select id="fbiome"><option value="">— any —</option></select>
  kind <select id="fkind"><option value="">— any —</option></select>
  mod <select id="fmod"><option value="">— any —</option></select>
  search <input type="text" id="fsearch" placeholder="defName or label…">
  <h2>Legend</h2>
  <div id="legend" class="note"></div>
</div>
<div id="main">
  <div id="plotbox"><canvas id="cv"></canvas><div id="tip"></div></div>
  <div id="status"></div>
  <div id="basket">
    <b>Basket</b> (<span id="bcount">0</span>)
    <button id="bcopy">copy defNames JSON</button>
    <button id="bclear">clear</button>
    <span class="note">persists in this browser only (localStorage) — copy out anything you want to keep</span>
    <div id="bitems"></div>
  </div>
</div>
</div>
<script>
const DATA = __DATA__;
const AXES = {
  bs:  {label:'bodySize', log:1},
  dw:  {label:'drawSize (max dimension, cells)', log:1},
  hs:  {label:'healthScale', log:1},
  sp:  {label:'moveSpeed (cells/s)', log:0},
  wd:  {label:'wildness (0–1)', log:0},
  mt:  {label:'meatAmount (resolved)', log:1},
  lt:  {label:'leatherAmount (resolved)', log:1},
  ar:  {label:'armorSharp (0–2)', log:0},
  bh:  {label:'bestHit = max melee tool power', log:1},
  kbs: {label:'K = bestHit ÷ bodySize (derived)', log:0},
  hbs: {label:'healthScale ÷ bodySize (derived)', log:1},
  mbs: {label:'meat ÷ bodySize (derived)', log:1},
  tc:  {label:'topCommonality', log:1},
  nb:  {label:'biome spread (count of spawn biomes)', log:0},
  px:  {label:'art px/cell (sprite resolution)', log:0},
};
function val(r, a) {
  if (a==='kbs') return (r.bh!=null && r.bs>0) ? r.bh/r.bs : null;
  if (a==='hbs') return (r.hs!=null && r.bs>0) ? r.hs/r.bs : null;
  if (a==='mbs') return (r.mt!=null && r.bs>0) ? r.mt/r.bs : null;
  const v = r[a]; return (v==null) ? null : v;
}
const KINDCOL = {animal:'#3b6fb5', insectoid:'#b58a3b', mechanoid:'#7a7a7a', vehicle:'#4aa3a0',
                 entity:'#8e44ad', dryad:'#2e7d4f', leviathan:'#c0392b'};
const PAL = ['#3b6fb5','#d97706','#2e7d4f','#c0392b','#8e44ad','#4aa3a0','#b58a3b','#d4649a',
             '#5b7a2a','#666666','#2255aa','#a0522d','#118899'];
const cv = document.getElementById('cv'), ctx = cv.getContext('2d');
const tip = document.getElementById('tip');
const $ = id => document.getElementById(id);
let pts = [];       // screen-space points after render: {x,y,r(row)}
let basket = [];
try { basket = JSON.parse(localStorage.getItem('creature_basket')||'[]'); } catch(e) {}

for (const [k,a] of Object.entries(AXES)) {
  $('ax').add(new Option(a.label, k)); $('ay').add(new Option(a.label, k));
}
$('ax').value='bs'; $('ay').value='mt'; $('axlog').checked=true; $('aylog').checked=true;
const biomes=[...new Set(DATA.flatMap(r=>r.bio))].sort();
biomes.forEach(b=>$('fbiome').add(new Option(b,b)));
[...new Set(DATA.map(r=>r.k))].sort().forEach(k=>$('fkind').add(new Option(k,k)));
[...new Set(DATA.map(r=>r.m))].sort().forEach(m=>$('fmod').add(new Option(m,m)));

function filtered() {
  const lo=$('liveonly').checked, fb=$('fbiome').value, fk=$('fkind').value,
        fm=$('fmod').value, fs=$('fsearch').value.trim().toLowerCase();
  return DATA.filter(r =>
    (!lo || (!r.cut && !r.zz)) &&
    (!fb || r.bio.includes(fb)) &&
    (!fk || r.k===fk) &&
    (!fm || r.m===fm) &&
    (!fs || r.d.toLowerCase().includes(fs) || (r.l||'').toLowerCase().includes(fs)));
}
function colorOf(r, mode, topmods) {
  if (mode==='k') return KINDCOL[r.k] || '#999';
  if (mode==='cut') return r.cut ? '#c0392b' : (r.zz ? '#d97706' : '#3b6fb5');
  const i = topmods.indexOf(r.m); return i>=0 ? PAL[i%PAL.length] : '#bbb';
}
function draw() {
  const W = cv.clientWidth, H = cv.clientHeight, dpr = window.devicePixelRatio||1;
  cv.width=W*dpr; cv.height=H*dpr; ctx.setTransform(dpr,0,0,dpr,0,0);
  ctx.fillStyle='#fbfaf7'; ctx.fillRect(0,0,W,H);
  const ax=$('ax').value, ay=$('ay').value, lx=$('axlog').checked, ly=$('aylog').checked;
  const rows = filtered();
  const good = rows.map(r=>({r, x:val(r,ax), y:val(r,ay)}))
                   .filter(p=>p.x!=null && p.y!=null && (!lx||p.x>0) && (!ly||p.y>0));
  const dropped = rows.length - good.length;
  const mode=$('colorby').value;
  const modCount={}; rows.forEach(r=>modCount[r.m]=(modCount[r.m]||0)+1);
  const topmods=Object.entries(modCount).sort((a,b)=>b[1]-a[1]).slice(0,12).map(e=>e[0]);
  const M={l:62,r:16,t:14,b:44};
  if (!good.length) { $('status').textContent='no points for this axis pair / filter'; pts=[]; return; }
  const tx = v => lx?Math.log10(v):v, ty = v => ly?Math.log10(v):v;
  let x0=Math.min(...good.map(p=>tx(p.x))), x1=Math.max(...good.map(p=>tx(p.x)));
  let y0=Math.min(...good.map(p=>ty(p.y))), y1=Math.max(...good.map(p=>ty(p.y)));
  if (x0===x1){x0-=1;x1+=1;} if (y0===y1){y0-=1;y1+=1;}
  const padx=(x1-x0)*0.04, pady=(y1-y0)*0.06; x0-=padx;x1+=padx;y0-=pady;y1+=pady;
  const SX = v => M.l + (tx(v)-x0)/(x1-x0)*(W-M.l-M.r);
  const SY = v => H-M.b - (ty(v)-y0)/(y1-y0)*(H-M.t-M.b);
  // grid + ticks
  ctx.strokeStyle='#e3e0d8'; ctx.fillStyle='#666'; ctx.font='11px system-ui';
  ctx.lineWidth=1;
  const ticks=(a,b,isLog)=>{ const out=[]; if(isLog){ for(let e=Math.ceil(a);e<=Math.floor(b);e++) out.push(e);}
    else { const s=Math.pow(10,Math.floor(Math.log10((b-a)/5))); const st=[1,2,5,10].map(m=>m*s).find(st=>(b-a)/st<=8)||s*10;
      for(let v=Math.ceil(a/st)*st; v<=b+1e-9; v+=st) out.push(v);} return out; };
  ticks(x0,x1,lx).forEach(v=>{ const px=M.l+(v-x0)/(x1-x0)*(W-M.l-M.r);
    ctx.beginPath();ctx.moveTo(px,M.t);ctx.lineTo(px,H-M.b);ctx.stroke();
    ctx.textAlign='center'; ctx.fillText(lx?('1e'+v).replace('1e0','1').replace('1e1','10'):(+v.toFixed(6)), px, H-M.b+16); });
  ticks(y0,y1,ly).forEach(v=>{ const py=H-M.b-(v-y0)/(y1-y0)*(H-M.t-M.b);
    ctx.beginPath();ctx.moveTo(M.l,py);ctx.lineTo(W-M.r,py);ctx.stroke();
    ctx.textAlign='right'; ctx.fillText(ly?('1e'+v).replace('1e0','1').replace('1e1','10'):(+v.toFixed(6)), M.l-6, py+4); });
  ctx.fillStyle='#333'; ctx.textAlign='center'; ctx.font='12px system-ui';
  ctx.fillText(AXES[ax].label + (lx?' — log':''), M.l+(W-M.l-M.r)/2, H-8);
  ctx.save(); ctx.translate(14, M.t+(H-M.t-M.b)/2); ctx.rotate(-Math.PI/2);
  ctx.fillText(AXES[ay].label + (ly?' — log':''), 0, 0); ctx.restore();
  // reference laws
  if ($('laws').checked) {
    ctx.save(); ctx.lineWidth=1.4; ctx.strokeStyle='#444'; ctx.setLineDash([]);
    const curve=(f,dash)=>{ ctx.setLineDash(dash||[]); ctx.beginPath(); let started=false;
      for(let i=0;i<=300;i++){ const xv=lx?Math.pow(10,x0+(x1-x0)*i/300):(x0+(x1-x0)*i/300);
        const yv=f(xv); if(yv==null||yv<=0&&ly) continue; const px=SX(xv), py=SY(yv);
        if(py<M.t-5||py>H-M.b+5){started=false;continue;}
        started?ctx.lineTo(px,py):(ctx.moveTo(px,py),started=true);} ctx.stroke(); };
    if (ax==='bs'&&ay==='mt') { curve(b=>140*b,[5,4]); curve(b=>b>1?140*b*b:140*b); }
    if (ax==='bs'&&ay==='bh') { curve(b=>12*b,[5,4]); curve(b=>15*b,[5,4]); }
    if (ax==='bs'&&ay==='dw') { curve(b=>1.9*Math.sqrt(b)); }
    if (ax==='bs'&&ay==='kbs') { curve(()=>12,[5,4]); curve(()=>15,[5,4]); }
    ctx.restore();
  }
  // points
  pts=[];
  const inBasket = new Set(basket);
  for (const p of good) {
    const px=SX(p.x), py=SY(p.y), c=colorOf(p.r,mode,topmods);
    ctx.globalAlpha = p.r.cut||p.r.zz ? 0.35 : 0.8;
    ctx.fillStyle=c; ctx.beginPath(); ctx.arc(px,py,3.2,0,7); ctx.fill();
    if (inBasket.has(p.r.d)) { ctx.globalAlpha=1; ctx.strokeStyle='#c0392b'; ctx.lineWidth=1.6;
      ctx.beginPath(); ctx.arc(px,py,5.4,0,7); ctx.stroke(); }
    pts.push({x:px,y:py,r:p.r,vx:p.x,vy:p.y});
  }
  ctx.globalAlpha=1;
  $('status').textContent = `${good.length} plotted · ${dropped} filtered rows lack a value for this pair · `
    + `laws drawn: ${$('laws').checked && (ax==='bs'&&['mt','bh','dw','kbs'].includes(ay)) ? 'yes' : 'none for this pair'}`;
  // legend
  const lg=$('legend'); lg.innerHTML='';
  const sw=(c,t)=>`<span style="display:inline-block;width:10px;height:10px;background:${c};border-radius:5px;margin-right:4px"></span>${t}<br>`;
  if (mode==='k') lg.innerHTML=Object.entries(KINDCOL).map(([k,c])=>sw(c,k)).join('');
  else if (mode==='cut') lg.innerHTML=sw('#3b6fb5','live')+sw('#d97706','commonality zeroed')+sw('#c0392b','Cherry Picker cut');
  else lg.innerHTML=topmods.map((m,i)=>sw(PAL[i%PAL.length],m)).join('')+sw('#bbb','other mods');
}
function nearest(mx,my){ let best=null,bd=90;
  for(const p of pts){ const d=(p.x-mx)**2+(p.y-my)**2; if(d<bd){bd=d;best=p;} } return best; }
cv.addEventListener('mousemove', e=>{
  const b=cv.getBoundingClientRect(), p=nearest(e.clientX-b.left, e.clientY-b.top);
  if(!p){ tip.style.display='none'; return; }
  const r=p.r;
  tip.innerHTML = (r.sprite?`<img src="../${r.sprite}" onerror="this.style.display='none'">`:'') +
    `<div class="nm">${r.l||r.d}</div><div class="mut">${r.d} · ${r.k} · ${r.m}</div>` +
    `<div>bodySize ${r.bs} · health ${r.hs} · speed ${r.sp}</div>` +
    `<div>meat ${r.mt==null?'—':Math.round(r.mt)} · bestHit ${r.bh==null?'—':r.bh} · wild ${r.wd==null?'—':r.wd}</div>` +
    `<div>${AXES[$('ax').value].label}: <b>${+(+p.vx).toPrecision(4)}</b> · ${AXES[$('ay').value].label}: <b>${+(+p.vy).toPrecision(4)}</b></div>` +
    (r.cut?'<div style="color:#c0392b">CUT by Cherry Picker</div>':'') +
    (r.zz?'<div style="color:#d97706">commonality zeroed</div>':'');
  const bx=e.clientX-b.left+14, by=e.clientY-b.top+10;
  tip.style.left=Math.min(bx, cv.clientWidth-290)+'px'; tip.style.top=Math.min(by, cv.clientHeight-160)+'px';
  tip.style.display='block';
});
cv.addEventListener('mouseleave', ()=>tip.style.display='none');
cv.addEventListener('click', e=>{
  const b=cv.getBoundingClientRect(), p=nearest(e.clientX-b.left, e.clientY-b.top);
  if(!p) return;
  const i=basket.indexOf(p.r.d);
  if(i>=0) basket.splice(i,1); else basket.push(p.r.d);
  saveBasket(); draw();
});
function saveBasket(){ try{localStorage.setItem('creature_basket',JSON.stringify(basket));}catch(e){}
  $('bcount').textContent=basket.length;
  $('bitems').innerHTML=basket.map(d=>`<span class="item" data-d="${d}">${d}</span>`).join('');
  document.querySelectorAll('#basket .item').forEach(el=>el.onclick=()=>{
    basket=basket.filter(x=>x!==el.dataset.d); saveBasket(); draw(); });
}
$('bcopy').onclick=()=>{ navigator.clipboard.writeText(JSON.stringify(basket,null,1))
  .then(()=>$('bcopy').textContent='copied!').catch(()=>prompt('copy:',JSON.stringify(basket)));
  setTimeout(()=>$('bcopy').textContent='copy defNames JSON',1200); };
$('bclear').onclick=()=>{ basket=[]; saveBasket(); draw(); };
['ax','ay','axlog','aylog','laws','colorby','liveonly','fbiome','fkind','fmod'].forEach(id=>$(id).addEventListener('change',draw));
$('fsearch').addEventListener('input',()=>{clearTimeout(window._t);window._t=setTimeout(draw,200);});
window.addEventListener('resize',draw);
saveBasket(); draw();
</script>
"""

note = ("%d creatures · dump of %d mods · register built %s. Data: creature_register_rows.json (verbatim); "
        "derived axes state their formula." % (meta["n"], meta["dumpMods"], meta["built"][:10]))
page = TEMPLATE.replace("__META_NOTE__", html.escape(note)).replace(
    "__DATA__", json.dumps(data, separators=(",", ":")))
with open(OUT, "w") as f:
    f.write(page)
print("wrote %s  (%.1f KB, %d rows)" % (OUT, os.path.getsize(OUT) / 1024, meta["n"]))
