#!/usr/bin/env python3
"""Write the PROVE/EXPECT/LIES plan beside a finished facing set.

Every number in the plan is MEASURED off the PNGs that were just written, not
asserted, so the plan cannot drift from the art it describes.

    python3 write_sea_plan.py CrimsonOpee [...]
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, "/mnt/d/Luke/dev/Rimworld/skills/generating-rimworld-sprites/scripts")
import validate_sprite as V  # noqa: E402
from sea_creatures import CREATURES, FINAL, TELL, canvas_for  # noqa: E402

FACINGS = ("south", "east", "north", "west")

DOC = """<!-- SW_SEA_MONSTERS_ART_1 — the facing set. The shipping copies live in
     src/RimStarWars/SeaBeasts/Textures/Things/Pawn/Animal/SeaBeasts/{slug}/;
     art/ is DEPLOY_HOLD'd source (src/DEPLOY_HOLD.txt) and never ships.
     Approved concept: src/RimStarWars/SeaBeasts/art/mockups/{stem}.png (KEPT by the
     owner 2026-08-31; this set must read as the SAME animal and was not re-rolled).
     Roster: design/Jawa/worldbuilding/sea_beasts_roster.md · def spec:
     design/Jawa/worldbuilding/sea_beasts_def_spec.md §5. -->
# {label} — facing set validation plan

`{defname}` · bodySize {bs} · drawSize **{draw}** → {draw} × 128 px/cell = {want} px →
canvas **{n}x{n}**{capnote}.

How this set was built, because it decides what can be wrong with it:

- **west** is the owner's kept mockup itself, chroma-keyed and fitted. `Rot4.West`
  means the animal faces left, which is the pose the mockup was drawn in — so west
  is the approved concept at pixel level, not an interpretation of it.
- **east** is west mirrored horizontally.
- **south** and **north** were generated by editing *from* that mockup, one call
  each, carrying the creature's treatment as words (the two-image anchor hangs on
  this install; the word anchor is the documented fallback).
- All four were scaled to a common long axis of {long} px on the same canvas, so the
  animal does not change size as it turns.

## 1. Offline — done, this commit

```
PROVE    src/RimStarWars/SeaBeasts/art/tools/seacheck.py on the folder: validate_sprite.measure() plus the
         reference-free half of its gate on each facing, then the set-level
         checks a per-file validator cannot make (one canvas, one animal size,
         east != west, four distinct images, no missing facing)
EXPECT   4/4 at {n}x{n}, alpha yes, all four corners 0, no faint pixels reaching
         past the silhouette, mid-alpha under {midmax:.0%}, 0 REJECT
LIES     it grades the SET's geometry and the cutout's health — it cannot see
         whether south and north are the same ANIMAL as west. Only the contact
         sheet shows that, and only a human or a Fable-tier review reads it
```

Measured on the committed PNGs:

| facing | canvas | subject | coverage | fringe (a1-31) | mid (a32-223) |
|---|---|---|---|---|---|
{rows}

## 2. In game — owed

The `{defname}` ThingDef and PawnKindDef are authored under
`src/RimStarWars/SeaBeasts/Defs/ThingDefs_Races/`, so there is something to spawn:

```
PROVE    spawn {defname} on a quicktest map, select it, and rotate it through
         all four facings at default zoom (adult drawSize {draw} ⇒ roughly {cells}
         cells across the screen)
EXPECT   {tell} — visible on south, east and west; hidden on north, which shows
         only the back
LIES     Graphic_Multi's bare-path fallback: Graphic_Multi.Init calls
         ContentFinder.Get on the path WITHOUT the _south/_north suffix before it
         errors, so one mis-deployed facing silently draws a different one and the
         creature looks fine. Name the facing you looked at, per rotation — and a
         MISSING facing renders nothing at all, with no magenta to warn you
LIES     texPath binds by path, not defName. The def must point at
         Things/Pawn/Animal/SeaBeasts/{slug}/{slug} and the four files must be
         deployed under that exact folder in the Steam Mods tree; byte-identical
         files in this repo prove nothing about what the game loads
LIES     `lifeStages/swimmingGraphicData` is specced to the same texPath in v1
         (def spec §3). If it is ever given its own art, this set stops being the
         only thing on screen and a "the sprite is right" check silently moves
```

## Out of scope here

Art quality and style coherence are Fable-tier review, not this plan
(`infrastructure/VALIDATION_LADDER.md`); this plan proves the files are shippable
and says what a look would have to find.
"""


def main():
    for slug in sys.argv[1:]:
        stem, draw, _ = CREATURES[slug]
        defname, label, bs, tell = TELL[slug]
        n = canvas_for(draw)
        want = int(round(draw * 128))
        d = Path(FINAL) / slug
        rows, longs = [], []
        for f in FACINGS:
            s = V.measure(str(d / f"{slug}_{f}.png"))
            longs.append(max(s["span_w"], s["span_h"]))
            rows.append(f"| {f} | {s['w']}x{s['h']} | {s['span_w']}x{s['span_h']} | "
                        f"{s['coverage']:.1%} | {s['fringe']/s['n']:.2%} | "
                        f"{s['midtone']/s['n']:.2%} |")
        cap = ("" if n >= want else
               f" — **capped**: {want} px would want a {2*n} canvas, and the image "
               f"model returns ~1.5 Mpx natively, so that would be an upscale of "
               f"detail that is not there. This ships at {n/draw:.0f} px/cell")
        (d / "PLAN.md").write_text(DOC.format(
            stem=stem, label=label, defname=defname, bs=bs, draw=draw, want=want,
            n=n, capnote=cap, long=max(longs), rows="\n".join(rows), tell=tell,
            slug=slug, cells=round(draw), midmax=V.MIDTONE_MAX_FRACTION))
        print(f"wrote {d / 'PLAN.md'}")


if __name__ == "__main__":
    sys.exit(main() or 0)
