using System;
using System.Collections.Generic;
using System.Linq;
using BigAndSmall.FilteredLists;
using RimWorld;
using Verse;

namespace BigAndSmall;

public class GlobalSettings : Def
{
	public static Dictionary<string, GlobalSettings> globalSettings = DefDatabase<GlobalSettings>.AllDefs.ToDictionary((GlobalSettings x) => ((Def)x).defName);

	public List<string> enabledFeatures = new List<string>();

	public List<List<string>> alienGeneGroups = new List<List<string>>();

	public List<XenotypeChance> returnedXenotypes = new List<XenotypeChance>();

	public List<XenotypeChance> returnedXenotypesColonist = new List<XenotypeChance>();

	public List<InfiltratorData> infiltratorTypes = new List<InfiltratorData>();

	public List<ShaderTypeDef> autoGeneratedShaderOptions = new List<ShaderTypeDef>();

	[Unsaved(false)]
	private static List<List<GeneDef>> alienGeneGroupsDefs = null;

	public static XenotypeDef GetRandomReturnedXenotype
	{
		get
		{
			XenotypeChance val = default(XenotypeChance);
			if (!GenCollection.TryRandomElementByWeight<XenotypeChance>(globalSettings.SelectMany((KeyValuePair<string, GlobalSettings> x) => x.Value.returnedXenotypes), (Func<XenotypeChance, float>)((XenotypeChance x) => x.chance), ref val))
			{
				return null;
			}
			return val.xenotype;
		}
	}

	public static XenotypeDef GetRandomReturnedColonistXenotype
	{
		get
		{
			XenotypeChance val = default(XenotypeChance);
			if (!GenCollection.TryRandomElementByWeight<XenotypeChance>(globalSettings.SelectMany((KeyValuePair<string, GlobalSettings> x) => x.Value.returnedXenotypesColonist), (Func<XenotypeChance, float>)((XenotypeChance x) => x.chance), ref val))
			{
				return null;
			}
			return val.xenotype;
		}
	}

	public static List<ShaderTypeDef> AllAutoGeneratedShaderOptions => globalSettings.Values.SelectMany((GlobalSettings x) => x.autoGeneratedShaderOptions ?? new List<ShaderTypeDef>()).Distinct().ToList();

	public static bool IsFeatureEnabled(string featureName)
	{
		return globalSettings.Values.Any((GlobalSettings x) => x.enabledFeatures.Contains(featureName, StringComparer.OrdinalIgnoreCase));
	}

	public static void Initialize()
	{
		globalSettings = DefDatabase<GlobalSettings>.AllDefs.ToDictionary((GlobalSettings x) => ((Def)x).defName);
	}

	public static (XenotypeDef def, InfiltratorData data) GetRandomInfiltratorReplacementXenotype(Pawn pawn, int seed, bool forceNeeded, bool isFullRaid)
	{
		List<InfiltratorData> list = globalSettings.Values.SelectMany((GlobalSettings x) => x.infiltratorTypes).ToList();
		if (((Thing)pawn).Faction != null)
		{
			list = list.Where(delegate(InfiltratorData x)
			{
				if (GenCollection.Any<XenotypeChance>(x.doubleXenotypes) && (!x.canOnlyBeFullRaid || (x.canOnlyBeFullRaid && isFullRaid)) && (!isFullRaid || x.canBeFullRaid) && (!forceNeeded || x.canSwapXeno) && (x.factionFilter == null || x.factionFilter.GetFilterResult(((Thing)pawn).Faction.def).Accepted()) && (x.thingFilter == null || x.thingFilter.GetFilterResult(((Thing)pawn).def).Accepted()))
				{
					if (x.xenoFilter != null)
					{
						Pawn_GeneTracker genes = pawn.genes;
						XenotypeDef val = ((genes != null) ? genes.Xenotype : null);
						if (val != null)
						{
							return x.xenoFilter.GetFilterResult(val).Accepted();
						}
						return false;
					}
					return true;
				}
				return false;
			}).ToList();
		}
		if (list.Count == 0 || list.All(delegate(InfiltratorData x)
		{
			List<XenotypeChance> doubleXenotypes = x.doubleXenotypes;
			return doubleXenotypes != null && doubleXenotypes.Count == 0;
		}))
		{
			return (def: null, data: null);
		}
		RandBlock val2 = default(RandBlock);
		((RandBlock)(ref val2))._002Ector(seed);
		try
		{
			GenCollection.RandomElementByWeight<InfiltratorData>((IEnumerable<InfiltratorData>)list, (Func<InfiltratorData, float>)((InfiltratorData x) => x.TotalChance));
		}
		finally
		{
			((IDisposable)(RandBlock)(ref val2)/*cast due to .constrained prefix*/).Dispose();
		}
		XenotypeDef resultXeno = GenCollection.RandomElementByWeight<XenotypeChance>((IEnumerable<XenotypeChance>)list.SelectMany((InfiltratorData x) => x.doubleXenotypes).ToList(), (Func<XenotypeChance, float>)((XenotypeChance x) => x.chance)).xenotype;
		return (def: resultXeno, data: list.First((InfiltratorData x) => GenCollection.Any<XenotypeChance>(x.doubleXenotypes, (Predicate<XenotypeChance>)((XenotypeChance y) => y.xenotype == resultXeno))));
	}

	public static List<List<GeneDef>> GetAlienGeneGroups()
	{
		if (alienGeneGroupsDefs == null)
		{
			alienGeneGroupsDefs = new List<List<GeneDef>>();
			foreach (GlobalSettings item in globalSettings.Values.Where((GlobalSettings x) => x.alienGeneGroups != null))
			{
				foreach (List<string> alienGeneGroup in item.alienGeneGroups)
				{
					if (GenList.NullOrEmpty<string>((IList<string>)alienGeneGroup))
					{
						continue;
					}
					List<GeneDef> list = new List<GeneDef>();
					foreach (GeneDef item2 in alienGeneGroup.Select((string x) => DefDatabase<GeneDef>.GetNamed(x, false)))
					{
						if (item2 != null)
						{
							list.Add(item2);
						}
					}
					if (list.Count > 0)
					{
						alienGeneGroupsDefs.Add(list);
					}
				}
			}
		}
		return alienGeneGroupsDefs;
	}
}
