using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Runtime.CompilerServices;
using RimWorld;
using Verse;

namespace BigAndSmall;

public static class RenderNodePatcher
{
	[CompilerGenerated]
	private static List<ShaderTypeDef> _003CDefaultPickableExtraShader_003Ek__BackingField;

	public static List<ShaderTypeDef> DefaultPickableExtraShader => _003CDefaultPickableExtraShader_003Ek__BackingField = GlobalSettings.AllAutoGeneratedShaderOptions;

	public static void TryUpdate(Dictionary<FlagString, HasCustomizableGraphics> dict, FlagString flag, List<FlagString> extraKeys)
	{
		if (!dict.TryGetValue(flag, out var value))
		{
			value = (dict[flag] = new HasCustomizableGraphics
			{
				Flag = flag,
				colorA = true,
				colorB = true
			});
		}
		if (extraKeys != null)
		{
			GenCollection.AddRange<FlagString>((HashSet<FlagString>)value.customFlags, extraKeys);
		}
	}

	public static void TryPatchPawnRenderNodeDefs()
	{
		//IL_0767: Unknown result type (might be due to invalid IL or missing references)
		//IL_0805: Unknown result type (might be due to invalid IL or missing references)
		//IL_07a8: Unknown result type (might be due to invalid IL or missing references)
		//IL_07ae: Invalid comparison between Unknown and I4
		//IL_0843: Unknown result type (might be due to invalid IL or missing references)
		//IL_0849: Invalid comparison between Unknown and I4
		bool num = BigSmallMod.settings?.makeDefsRecolorable ?? false;
		IEnumerable<GeneDef> enumerable = DefDatabase<GeneDef>.AllDefsListForReading.Where(delegate(GeneDef x)
		{
			if (!GenList.NullOrEmpty<PawnRenderNodeProperties>((IList<PawnRenderNodeProperties>)x.RenderNodeProperties))
			{
				List<DefModExtension> modExtensions = ((Def)x).modExtensions;
				if (modExtensions == null || !GenCollection.Any<DefModExtension>(modExtensions, (Predicate<DefModExtension>)((DefModExtension x) => x is HasCustomizableGraphics)))
				{
					List<DefModExtension> modExtensions2 = ((Def)x).modExtensions;
					if (modExtensions2 == null)
					{
						return true;
					}
					return !GenCollection.Any<DefModExtension>(modExtensions2, (Predicate<DefModExtension>)((DefModExtension x) => x is GraphicsOverride));
				}
			}
			return false;
		});
		IEnumerable<HediffDef> enumerable2 = DefDatabase<HediffDef>.AllDefsListForReading.Where(delegate(HediffDef x)
		{
			if (!GenList.NullOrEmpty<PawnRenderNodeProperties>((IList<PawnRenderNodeProperties>)x.RenderNodeProperties))
			{
				List<DefModExtension> modExtensions3 = ((Def)x).modExtensions;
				if (modExtensions3 == null || !GenCollection.Any<DefModExtension>(modExtensions3, (Predicate<DefModExtension>)((DefModExtension x) => x is HasCustomizableGraphics)))
				{
					List<DefModExtension> modExtensions4 = ((Def)x).modExtensions;
					if (modExtensions4 == null)
					{
						return true;
					}
					return !GenCollection.Any<DefModExtension>(modExtensions4, (Predicate<DefModExtension>)((DefModExtension x) => x is GraphicsOverride));
				}
			}
			return false;
		});
		if (!num)
		{
			enumerable = enumerable.Where((GeneDef x) => ((Def)x).defName.StartsWith("BS_"));
			enumerable2 = enumerable2.Where((HediffDef x) => ((Def)x).defName.StartsWith("BS_"));
		}
		List<PawnRenderingProps_Lite> list = new List<PawnRenderingProps_Lite>();
		FlagString flagString = new FlagString("HornGraphics");
		FlagString flagString2 = new FlagString("EarGraphics");
		FlagString flagString3 = new FlagString("WingGraphics");
		FlagString flagString4 = new FlagString("TailGraphics");
		FlagString flagString5 = new FlagString("HaloGraphics");
		FlagString flagString6 = new FlagString("MiscHeadGraphics");
		FlagString flagString7 = new FlagString("MiscBodyGraphics");
		FlagString flagString8 = new FlagString("HeadBionicGraphics");
		FlagString flagString9 = new FlagString("BodyBionicGraphics");
		FlagString flagString10 = new FlagString("HeadFleshGraphics");
		FlagString flagString11 = new FlagString("BodyFleshGraphics");
		foreach (GeneDef item in enumerable)
		{
			Dictionary<FlagString, HasCustomizableGraphics> dictionary = new Dictionary<FlagString, HasCustomizableGraphics>();
			for (int num2 = item.RenderNodeProperties.Count - 1; num2 >= 0; num2--)
			{
				PawnRenderNodeProperties val = item.RenderNodeProperties[num2];
				_ = ((Def)item).defName;
				if (((object)val).GetType() != typeof(PawnRenderNodeProperties) || typeof(PawnRenderNode_Fur).IsAssignableFrom(val.nodeClass))
				{
					continue;
				}
				if (val.nodeClass == typeof(PawnRenderNode_AttachmentHead) || val.parentTagDef == PawnRenderNodeTagDefOf.Head)
				{
					string defName = ((Def)item).defName;
					if (defName == null || !defName.Contains("horn", StringComparison.OrdinalIgnoreCase))
					{
						List<string> exclusionTags = item.exclusionTags;
						if (exclusionTags == null || !GenCollection.Any<string>(exclusionTags, (Predicate<string>)((string x) => x.Contains("horn", StringComparison.OrdinalIgnoreCase))))
						{
							GeneCategoryDef displayCategory = item.displayCategory;
							if (displayCategory == null || ((Def)displayCategory).defName?.Contains("horn", StringComparison.OrdinalIgnoreCase) != true)
							{
								string defName2 = ((Def)item).defName;
								if (defName2 == null || !defName2.Contains("ears", StringComparison.OrdinalIgnoreCase))
								{
									List<string> exclusionTags2 = item.exclusionTags;
									if (exclusionTags2 == null || !GenCollection.Any<string>(exclusionTags2, (Predicate<string>)((string x) => x.Contains("ears", StringComparison.OrdinalIgnoreCase))))
									{
										GeneCategoryDef displayCategory2 = item.displayCategory;
										if (displayCategory2 == null || ((Def)displayCategory2).defName?.Contains("ears", StringComparison.OrdinalIgnoreCase) != true)
										{
											string defName3 = ((Def)item).defName;
											if (defName3 == null || !defName3.Contains("halo", StringComparison.OrdinalIgnoreCase))
											{
												List<string> exclusionTags3 = item.exclusionTags;
												if (exclusionTags3 == null || !GenCollection.Any<string>(exclusionTags3, (Predicate<string>)((string x) => x.Contains("halo", StringComparison.OrdinalIgnoreCase))))
												{
													GeneCategoryDef displayCategory3 = item.displayCategory;
													if (displayCategory3 == null || ((Def)displayCategory3).defName?.Contains("halo", StringComparison.OrdinalIgnoreCase) != true)
													{
														List<FlagString> userPickableAlts;
														PawnRenderingProps_Lite pawnRenderingProps_Lite = ReplaceWithLite(val, flagString6, (Def)(object)item, useHeadMesh: true, out userPickableAlts);
														TryUpdate(dictionary, flagString6, userPickableAlts);
														item.RenderNodeProperties[num2] = (PawnRenderNodeProperties)(object)pawnRenderingProps_Lite;
														list.Add(pawnRenderingProps_Lite);
														continue;
													}
												}
											}
											List<FlagString> userPickableAlts2;
											PawnRenderingProps_Lite pawnRenderingProps_Lite2 = ReplaceWithLite(val, flagString5, (Def)(object)item, useHeadMesh: true, out userPickableAlts2);
											TryUpdate(dictionary, flagString5, userPickableAlts2);
											item.RenderNodeProperties[num2] = (PawnRenderNodeProperties)(object)pawnRenderingProps_Lite2;
											list.Add(pawnRenderingProps_Lite2);
											continue;
										}
									}
								}
								List<FlagString> userPickableAlts3;
								PawnRenderingProps_Lite pawnRenderingProps_Lite3 = ReplaceWithLite(val, flagString2, (Def)(object)item, useHeadMesh: true, out userPickableAlts3);
								TryUpdate(dictionary, flagString2, userPickableAlts3);
								item.RenderNodeProperties[num2] = (PawnRenderNodeProperties)(object)pawnRenderingProps_Lite3;
								list.Add(pawnRenderingProps_Lite3);
								continue;
							}
						}
					}
					List<FlagString> userPickableAlts4;
					PawnRenderingProps_Lite pawnRenderingProps_Lite4 = ReplaceWithLite(val, flagString, (Def)(object)item, useHeadMesh: true, out userPickableAlts4);
					TryUpdate(dictionary, flagString, userPickableAlts4);
					item.RenderNodeProperties[num2] = (PawnRenderNodeProperties)(object)pawnRenderingProps_Lite4;
					list.Add(pawnRenderingProps_Lite4);
				}
				else
				{
					if (!(val.nodeClass == typeof(PawnRenderNode)))
					{
						continue;
					}
					string defName4 = ((Def)item).defName;
					if (defName4 == null || !defName4.Contains("wing", StringComparison.OrdinalIgnoreCase))
					{
						List<string> exclusionTags4 = item.exclusionTags;
						if (exclusionTags4 == null || !GenCollection.Any<string>(exclusionTags4, (Predicate<string>)((string x) => x.Contains("wing", StringComparison.OrdinalIgnoreCase))))
						{
							GeneCategoryDef displayCategory4 = item.displayCategory;
							if (displayCategory4 == null || ((Def)displayCategory4).defName?.Contains("wing", StringComparison.OrdinalIgnoreCase) != true)
							{
								string defName5 = ((Def)item).defName;
								if (defName5 == null || !defName5.Contains("tail", StringComparison.OrdinalIgnoreCase))
								{
									List<string> exclusionTags5 = item.exclusionTags;
									if (exclusionTags5 == null || !GenCollection.Any<string>(exclusionTags5, (Predicate<string>)((string x) => x.Contains("tail", StringComparison.OrdinalIgnoreCase))))
									{
										GeneCategoryDef displayCategory5 = item.displayCategory;
										if (displayCategory5 == null || ((Def)displayCategory5).defName?.Contains("tail", StringComparison.OrdinalIgnoreCase) != true)
										{
											List<FlagString> userPickableAlts5;
											PawnRenderingProps_Lite pawnRenderingProps_Lite5 = ReplaceWithLite(val, flagString7, (Def)(object)item, useHeadMesh: false, out userPickableAlts5);
											TryUpdate(dictionary, flagString7, userPickableAlts5);
											item.RenderNodeProperties[num2] = (PawnRenderNodeProperties)(object)pawnRenderingProps_Lite5;
											list.Add(pawnRenderingProps_Lite5);
											continue;
										}
									}
								}
								List<FlagString> userPickableAlts6;
								PawnRenderingProps_Lite pawnRenderingProps_Lite6 = ReplaceWithLite(val, flagString4, (Def)(object)item, useHeadMesh: false, out userPickableAlts6);
								TryUpdate(dictionary, flagString4, userPickableAlts6);
								item.RenderNodeProperties[num2] = (PawnRenderNodeProperties)(object)pawnRenderingProps_Lite6;
								list.Add(pawnRenderingProps_Lite6);
								continue;
							}
						}
					}
					List<FlagString> userPickableAlts7;
					PawnRenderingProps_Lite pawnRenderingProps_Lite7 = ReplaceWithLite(val, flagString3, (Def)(object)item, useHeadMesh: true, out userPickableAlts7);
					TryUpdate(dictionary, flagString3, userPickableAlts7);
					item.RenderNodeProperties[num2] = (PawnRenderNodeProperties)(object)pawnRenderingProps_Lite7;
					list.Add(pawnRenderingProps_Lite7);
				}
			}
			foreach (HasCustomizableGraphics value in dictionary.Values)
			{
				GeneDef val2 = item;
				if (((Def)val2).modExtensions == null)
				{
					((Def)val2).modExtensions = new List<DefModExtension>();
				}
				((Def)item).modExtensions.Add((DefModExtension)(object)value);
			}
		}
		foreach (HediffDef item2 in enumerable2)
		{
			Dictionary<FlagString, HasCustomizableGraphics> dictionary2 = new Dictionary<FlagString, HasCustomizableGraphics>();
			if (item2.addedPartProps == null)
			{
				continue;
			}
			for (int num3 = item2.RenderNodeProperties.Count - 1; num3 >= 0; num3--)
			{
				PawnRenderNodeProperties val3 = item2.RenderNodeProperties[num3];
				if (!(((object)val3).GetType() != typeof(PawnRenderNodeProperties)))
				{
					if (val3.nodeClass == typeof(PawnRenderNode_AttachmentHead))
					{
						if ((int)val3.colorType == 0)
						{
							List<FlagString> userPickableAlts8;
							PawnRenderingProps_Lite pawnRenderingProps_Lite8 = ReplaceWithLite(val3, flagString8, (Def)(object)item2, useHeadMesh: true, out userPickableAlts8);
							TryUpdate(dictionary2, flagString8, userPickableAlts8);
							item2.RenderNodeProperties[num3] = (PawnRenderNodeProperties)(object)pawnRenderingProps_Lite8;
							list.Add(pawnRenderingProps_Lite8);
						}
						else if ((int)val3.colorType == 2)
						{
							List<FlagString> userPickableAlts9;
							PawnRenderingProps_Lite pawnRenderingProps_Lite9 = ReplaceWithLite(val3, flagString10, (Def)(object)item2, useHeadMesh: true, out userPickableAlts9);
							TryUpdate(dictionary2, flagString10, userPickableAlts9);
							item2.RenderNodeProperties[num3] = (PawnRenderNodeProperties)(object)pawnRenderingProps_Lite9;
							list.Add(pawnRenderingProps_Lite9);
						}
					}
					else if (val3.nodeClass == typeof(PawnRenderNode))
					{
						if ((int)val3.colorType == 0)
						{
							List<FlagString> userPickableAlts10;
							PawnRenderingProps_Lite pawnRenderingProps_Lite10 = ReplaceWithLite(val3, flagString9, (Def)(object)item2, useHeadMesh: true, out userPickableAlts10);
							TryUpdate(dictionary2, flagString9, userPickableAlts10);
							item2.RenderNodeProperties[num3] = (PawnRenderNodeProperties)(object)pawnRenderingProps_Lite10;
							list.Add(pawnRenderingProps_Lite10);
						}
						else if ((int)val3.colorType == 2)
						{
							List<FlagString> userPickableAlts11;
							PawnRenderingProps_Lite pawnRenderingProps_Lite11 = ReplaceWithLite(val3, flagString11, (Def)(object)item2, useHeadMesh: true, out userPickableAlts11);
							TryUpdate(dictionary2, flagString11, userPickableAlts11);
							item2.RenderNodeProperties[num3] = (PawnRenderNodeProperties)(object)pawnRenderingProps_Lite11;
							list.Add(pawnRenderingProps_Lite11);
						}
					}
					foreach (HasCustomizableGraphics value2 in dictionary2.Values)
					{
						HediffDef val4 = item2;
						if (((Def)val4).modExtensions == null)
						{
							((Def)val4).modExtensions = new List<DefModExtension>();
						}
						((Def)item2).modExtensions.Add((DefModExtension)(object)value2);
					}
				}
			}
		}
		Log.Message(string.Format("[Big & Small] Patched {0} PawnRenderNodeProperties to use {1} for recolorable graphics.\nRemember that you can always disable this again in the mod options.", list.Count, "PawnRenderingProps_Lite"));
		foreach (PawnRenderingProps_Lite item3 in list)
		{
			item3.TrySetup(forceSetup: true);
			((PawnRenderNodeProperties)item3).EnsureInitialized();
			((PawnRenderNodeProperties)item3).ResolveReferencesRecursive();
		}
	}

	public static PawnRenderingProps_Lite ReplaceWithLite(PawnRenderNodeProperties original, FlagString tag, Def def, bool useHeadMesh, out List<FlagString> userPickableAlts)
	{
		PawnRenderingProps_Lite pawnRenderingProps_Lite = new PawnRenderingProps_Lite();
		Type type = ((object)original).GetType();
		FieldInfo[] fields = type.GetFields(BindingFlags.Instance | BindingFlags.Public);
		PropertyInfo[] properties = type.GetProperties(BindingFlags.Instance | BindingFlags.Public);
		foreach (PropertyInfo propertyInfo in properties)
		{
			if (!propertyInfo.CanRead || !propertyInfo.CanWrite)
			{
				continue;
			}
			object value = propertyInfo.GetValue(original);
			if (value != null && value != null)
			{
				try
				{
					propertyInfo.SetValue(pawnRenderingProps_Lite, value);
				}
				catch (ArgumentException)
				{
					Log.WarningOnce(string.Format("[Big & Small] Failed to copy property {0} of type {1} from {2} to {3}. Skipping.", propertyInfo.Name, propertyInfo.PropertyType, type, "PawnRenderingProps_Lite"), 2654322);
				}
			}
		}
		FieldInfo[] array = fields;
		foreach (FieldInfo fieldInfo in array)
		{
			object value2 = fieldInfo.GetValue(original);
			if (value2 != null && value2 != null)
			{
				try
				{
					fieldInfo.SetValue(pawnRenderingProps_Lite, value2);
				}
				catch (ArgumentException)
				{
					Log.WarningOnce(string.Format("[Big & Small] Failed to copy field {0} of type {1} from {2} to {3}. Skipping.", fieldInfo.Name, fieldInfo.FieldType, type, "PawnRenderingProps_Lite"), 2654321);
				}
			}
		}
		pawnRenderingProps_Lite.tag = tag;
		((PawnRenderNodeProperties)pawnRenderingProps_Lite).nodeClass = typeof(RenderNodeLite);
		pawnRenderingProps_Lite.useHeadMesh = useHeadMesh;
		((PawnRenderNodeProperties)pawnRenderingProps_Lite).workerClass = typeof(UltimateRenderNodeWorker);
		if (original.shaderTypeDef == null || original.shaderTypeDef == ShaderTypeDefOf.Cutout)
		{
			pawnRenderingProps_Lite.shader = ShaderTypeDefOf.Cutout;
		}
		else
		{
			pawnRenderingProps_Lite.shader = original.shaderTypeDef;
		}
		pawnRenderingProps_Lite.identifier = def.defName;
		List<FlagString> list = new List<FlagString>();
		foreach (ShaderTypeDef item2 in DefaultPickableExtraShader)
		{
			FlagString item = new FlagString(def.defName, ((Def)item2).defName)
			{
				Label = GenText.CapitalizeFirst(tag.Label) + " -> " + ((Def)item2).label
			};
			list.Add(item);
			pawnRenderingProps_Lite.userPickableShaders.Add(item2);
		}
		userPickableAlts = list;
		return pawnRenderingProps_Lite;
	}
}
