#!/usr/bin/env python3
"""Write the ideology authoring palette: every meme, precept, style and ritual
that ACTUALLY LOADED, straight from the live def dump.

WHY: a religion spec is worthless if it names a meme that is not installed. The
KotOR Factions mod ships `guy762_MemeDef_mando`, which is exactly what the
Blackstar Company's Creed wants -- and that mod is not in the active list, so the
meme does not exist and a FactionDef naming it is a silent no-op. The only honest
source is what the running game built.

    python3 src/RimMandrake/Utils/ideology_palette.py

Output: design/Jawa/worldbuilding/data/ideology_palette.md (committed -- it is
the reference BUILD authors against, and regenerating it needs the game's dump).
"""

from __future__ import annotations

import json
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from game_paths import LOCALLOW  # noqa: E402

DUMP = Path(LOCALLOW) / "DefDump"
OUT = Path("design/Jawa/worldbuilding/data/ideology_palette.md")


def load(name: str) -> list[dict]:
    p = DUMP / "defs" / f"{name}.json"
    if not p.is_file():
        sys.exit(f"missing {p} — run a def dump from the live game first")
    return json.loads(p.read_text(encoding="utf-8"))["defs"]


def f(d: dict, key: str, default=None):
    return (d.get("fields") or {}).get(key, default)


def main() -> int:
    manifest = json.loads((DUMP / "manifest.json").read_text(encoding="utf-8"))
    stamp = f'{manifest.get("capturedUtc","?")}, game {manifest.get("gameVersion","?")}'

    memes = load("MemeDef")
    precepts = load("PreceptDef")
    issues = load("IssueDef")
    styles = load("StyleCategoryDef")
    patterns = load("RitualPatternDef")

    out: list[str] = []
    w = out.append
    w("# Ideology authoring palette — what is actually installed")
    w("")
    w(f"_Generated by `src/RimMandrake/Utils/ideology_palette.py` from the live def "
      f"dump captured {stamp}. **Do not hand-edit** — regenerate it._")
    w("")
    w("🔴 **This is the whole legal vocabulary.** A `MemeDef`, `PreceptDef` or "
      "`StyleCategoryDef` not listed here does not exist in this campaign, and a "
      "`FactionDef` naming one fails silently — the faction simply generates "
      "without it. Check against this file before writing any ideoligion XML.")
    w("")
    w(f"**Totals:** {len(memes)} memes · {len(precepts)} precepts across "
      f"{len(issues)} issues · {len(styles)} style categories · "
      f"{len(patterns)} ritual patterns.")
    w("")

    # ---- memes
    struct = sorted((m for m in memes if f(m, "category") == "Structure"),
                    key=lambda m: (m["modName"], m["defName"]))
    norm = sorted((m for m in memes if f(m, "category") != "Structure"),
                  key=lambda m: (m["modName"], m["defName"]))

    w("---")
    w("")
    w(f"## Structure memes ({len(struct)}) — exactly one per ideoligion")
    w("")
    w("The structure meme sets the worship room and **how many deities the "
      "religion may have** (`deityCount`). A faction whose spec calls for named "
      "gods must take a structure whose `deityCount` is not 0.")
    w("")
    w("| defName | label | deities | source |")
    w("|---|---|---|---|")
    for m in struct:
        w(f'| `{m["defName"]}` | {m.get("label") or ""} | '
          f'{f(m, "deityCount", 0)} | {m["modName"]} |')
    w("")

    w(f"## Normal memes ({len(norm)}) — several per ideoligion, budgeted by impact")
    w("")
    w("| defName | label | impact | source |")
    w("|---|---|---|---|")
    for m in norm:
        w(f'| `{m["defName"]}` | {m.get("label") or ""} | '
          f'{f(m, "impact", "")} | {m["modName"]} |')
    w("")

    # ---- precepts by issue
    by_issue: dict[str, list[dict]] = defaultdict(list)
    for p in precepts:
        iss = f(p, "issue")
        if iss:
            by_issue[iss].append(p)
    issue_label = {i["defName"]: (i.get("label") or i["defName"]) for i in issues}

    w("---")
    w("")
    w(f"## Precepts by issue ({len(by_issue)} issues carry at least one precept)")
    w("")
    w("An ideoligion takes **one position per issue**. Issues with only one "
      "precept are not choices; the ones worth specifying are the multi-position "
      "axes, listed first.")
    w("")
    ordered = sorted(by_issue, key=lambda i: (-len(by_issue[i]), i))
    for iss in ordered:
        ps = sorted(by_issue[iss], key=lambda p: (f(p, "displayOrderInIssue") or 0,
                                                  p["defName"]))
        if len(ps) < 2:
            continue
        w(f'### {issue_label.get(iss, iss)} — `{iss}` ({len(ps)} positions)')
        w("")
        for p in ps:
            src = p["modName"]
            src = "" if src in ("Core", "Ideology") else f" · _{src}_"
            w(f'- `{p["defName"]}` — {p.get("label") or ""}{src}')
        w("")

    singles = [i for i in ordered if len(by_issue[i]) == 1]
    if singles:
        w("### Single-position issues (no choice to make)")
        w("")
        w(", ".join(f'`{by_issue[i][0]["defName"]}`' for i in sorted(singles)))
        w("")

    # ---- styles
    w("---")
    w("")
    w(f"## Style categories ({len(styles)})")
    w("")
    w("A style category rewires the ART of a faction's buildings and apparel. "
      "Bound via `FactionDef.<styles>` or a meme's `<thingStyleCategories>`. "
      "This is the cheapest way to make a faction *look* like its religion.")
    w("")
    w("| defName | label | source |")
    w("|---|---|---|")
    for s in sorted(styles, key=lambda s: (s["modName"], s["defName"])):
        w(f'| `{s["defName"]}` | {s.get("label") or ""} | {s["modName"]} |')
    w("")

    # ---- ritual patterns
    w("---")
    w("")
    w(f"## Ritual patterns ({len(patterns)})")
    w("")
    w("| defName | source |")
    w("|---|---|")
    for r in sorted(patterns, key=lambda r: (r["modName"], r["defName"])):
        w(f'| `{r["defName"]}` | {r["modName"]} |')
    w("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(out)} lines)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
