#!/usr/bin/env python3
r"""plant_walk_list.py — where to stand to see the plants you are deciding about.

WHY THIS EXISTS
---------------
`PLANT_CHERRYPICK_PASS_1`'s only remaining criterion is the owner's, verbatim
2026-08-22: *"Let's run around the world and see how it looks before we actually cut
anything."* Everything decidable from a desk is decided. What is left is looking.

⭐ **A walk is only cheap if someone says where to walk.** Every tile of a biome grows the
same roster, so one landing site per biome answers the whole biome — and this picks that
site rather than leaving him to hunt for one. Ordered by what he actually objected to
(trees in the core desert) and then by how much of the planet the biome covers.

🔑 **It names the plants he will SEE there, not the plants that exist.** The candidate
list is already the reachable set; this narrows it to the ones worth a look — trees, and
anything whose loss would delete a resource from that biome.

    python3 design/Jawa/mods/plant_walk_list.py --md design/Jawa/mods/plant_walk_list.md
"""
from __future__ import annotations
import argparse, collections, csv, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(HERE)))
sys.path.insert(0, HERE)
from plant_harvest_coverage import (  # noqa: E402
    CSV, TILES, tile_counts, load_rows, sole_sources)

# The complaint that started the pass, in his words: trees on a desert map.
CORE_DESERT = ('Desert', 'ExtremeDesert', 'AridShrubland')

# 🔑 A CACTUS IS A TREE TO THE ENGINE, and lumping it with the drago tree makes the walk
# list useless — the owner said of the cacti "may be wanted". Same word list the sheet
# generator uses, so the two never disagree about what reads as desert flora.
DESERT_READS = ('cactus', 'saguaro', 'agave', 'palm', 'succulent', 'yucca',
                'aloe', 'scrub', 'brush', 'sage', 'grass', 'moss', 'lichen',
                'shrub', 'thistle', 'weed', 'dead', 'snag', 'bramble')


def reads_desert(label: str) -> bool:
    return any(k in label.lower() for k in DESERT_READS)


def pick_tile(rows_for_biome):
    """A representative landing site. ⚠️ NOT the first row — tile 2 sits at latitude
    -58 on the planet's rim. Take the median by elevation, which lands in the body of
    the biome rather than on an edge case."""
    s = sorted(rows_for_biome, key=lambda t: float(t['elev_m']))
    return s[len(s) // 2]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--md")
    args = ap.parse_args()

    tiles = list(csv.DictReader(open(TILES, encoding='utf-8')))
    counts = tile_counts()
    rows = load_rows()
    sole = sole_sources(rows, counts)

    by_biome = collections.defaultdict(list)
    for t in tiles:
        if t.get('biome'):
            by_biome[t['biome']].append(t)

    plants_of = collections.defaultdict(list)
    for r in rows:
        for b in (r.get('biomes') or '').split('|'):
            if b:
                plants_of[b].append(r)

    order = [b for b in CORE_DESERT if b in plants_of]
    order += sorted((b for b in plants_of if b not in CORE_DESERT),
                    key=lambda x: -counts[x])

    L: list[str] = []
    A = L.append
    A("# The plant walk — where to stand, and what to look at when you get there")
    A("")
    A("Generated by `design/Jawa/mods/plant_walk_list.py`. The last open criterion of")
    A("`PLANT_CHERRYPICK_PASS_1` is your walk; this is the route.")
    A("")
    A("🔑 **Every tile of a biome grows the same roster**, so one landing per biome settles")
    A("the biome. The core desert is first because it is what you objected to.")
    A("")
    A("⚠️ **Nothing is cut.** You ruled keep-all pending this walk, so the sheet is showing")
    A("you a world with every plant still in it. Mark what looks wrong; the cost of each cut")
    A("is already on its row in `plant_review.html`.")
    A("")

    for b in order:
        t = pick_tile(by_biome[b])
        ps = plants_of[b]
        trees = [p for p in ps if p['isTree'] == 'True']
        fragile = [p for p in ps if any(bb == b for bb, _ in sole.get(p['defName'], []))]
        head = "🔴 " if b in CORE_DESERT else ""
        A(f"## {head}`{b}` — {counts[b]:,} tiles ({100.0*counts[b]/len(tiles):.1f}% of the planet)")
        A("")
        A(f"**Land on tile `{t['tile']}`** — *{t['region']}*, {t['temp_c']}°C, "
          f"{t['elev_m']} m, rain {t['rain_mm']} mm.")
        A("")
        odd = [p for p in trees if not reads_desert(p['label'])]
        fits = [p for p in trees if reads_desert(p['label'])]
        if odd:
            A(f"🔴 **{len(odd)} tree(s) here do NOT read as desert flora** — this is the shape "
              "of the thing you objected to:")
            A("")
            for p in sorted(odd, key=lambda x: -int(x['tilesReachable'])):
                A(f"- **{p['label']}** (`{p['defName']}`, {p['mod']}) — reaches "
                  f"{int(p['tilesReachable']):,} tiles")
            A("")
        if fits:
            A(f"✅ *{len(fits)} more tree-class plants read correctly for the ground — "
              + ", ".join(p['label'] for p in sorted(fits, key=lambda x: -int(x['tilesReachable'])))
              + ".*")
            A("")
        if not trees:
            A("**No trees here.** Groundcover only.")
            A("")
        if fragile:
            A(f"⚠️ **{len(fragile)} plant(s) here supply something nothing else here does** — "
              "cutting one deletes the resource from this biome:")
            A("")
            for p in fragile:
                res = sorted({r for bb, r in sole[p['defName']] if bb == b})
                A(f"- **{p['label']}** (`{p['defName']}`) — only source of "
                  + ", ".join(f"`{x}`" for x in res))
            A("")
        A(f"*{len(ps)} plants reachable in total.*")
        A("")

    text = "\n".join(L) + "\n"
    if args.md:
        open(args.md, "w", encoding="utf-8").write(text)
        print(f"wrote {args.md}")
        print(f"  {len(order)} biomes · one landing tile each · "
              f"{sum(1 for r in rows if r['isTree']=='True')} trees across the roster")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
