#!/usr/bin/env python3
r"""plant_harvest_coverage.py — what a plant cut actually costs, per biome.

WHY THIS EXISTS
---------------
`PLANT_CHERRYPICK_PASS_1` names the trap and then only half-guards it:

> From `skills/rimworld-content-moderation`: cutting the last item carrying a tag
> silently disarms every pawn kind whose tags all went to zero. **The plant equivalent
> is `harvestedThingDef`** — cut every plant that yields a resource and the resource
> leaves the biome, with nothing warning you.

`gen_plant_sheet.py` guards **WoodLog only**, in biomes over 100 tiles, at a floor of two
sources. That is the right idea applied to one resource out of thirty. This is the
general case, and it is the item's second criterion: *"the kept set checked for
`harvestedThingDef` coverage per biome."*

🔴 **THE CHECK IS PER BIOME, NEVER PLANET-WIDE.** A resource with nine suppliers across
Ash'karr can still have exactly one inside `AB_MycoticJungle`, and a colony does not
travel to another biome for wood. A planet-wide count answers a question nobody asked and
reads as safety.

⚠️ **This measures the SHIPPED roster, not a proposal.** Under the owner's keep-all
ruling nothing is cut, so today every number here is a *what it would cost*, not a
defect. That is the point: it is the decision aid the sheet was missing.

    python3 design/Jawa/mods/plant_harvest_coverage.py            # report to stdout
    python3 design/Jawa/mods/plant_harvest_coverage.py --md <out.md>
"""
from __future__ import annotations
import argparse, collections, csv, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
CSV = os.path.join(ROOT, 'design', 'Jawa', 'mods', 'plant_cherrypick_candidates.csv')
TILES = os.path.join(ROOT, 'world', 'ASHKARR_WORLDMAP_tiles.csv')

# Biomes that are SUPPOSED to have no flora. Anything else with an empty roster is a
# finding, not a fact of nature.
PLANTLESS_BY_DESIGN = {'Ocean', 'Lake', 'SeaIce', 'IceSheet'}


def tile_counts() -> collections.Counter:
    c = collections.Counter()
    with open(TILES, encoding='utf-8') as fh:
        for r in csv.DictReader(fh):
            if r.get('biome'):
                c[r['biome']] += 1
    return c


def load_rows() -> list[dict]:
    with open(CSV, encoding='utf-8') as fh:
        return list(csv.DictReader(fh))


def coverage(rows, tiles):
    """biome -> resource -> [defName, ...], over the biomes that exist on the planet."""
    cov = collections.defaultdict(lambda: collections.defaultdict(list))
    for r in rows:
        h = (r.get('harvestedThingDef') or '').strip()
        for b in (r.get('biomes') or '').split('|'):
            if b and b in tiles:
                cov[b]  # a biome with plants but no yields still deserves a row
                if h:
                    cov[b][h].append(r['defName'])
    return cov


def sole_sources(rows, tiles) -> dict[str, list[tuple[str, str]]]:
    """defName -> [(biome, resource), ...] where it is the ONLY supplier in that biome.

    🔑 This is the number that decides a cut. Everything else on the sheet is taste."""
    cov = coverage(rows, tiles)
    out = collections.defaultdict(list)
    for b, by_res in cov.items():
        for res, defs in by_res.items():
            if len(defs) == 1:
                out[defs[0]].append((b, res))
    return dict(out)


def report(rows, tiles) -> str:
    cov = coverage(rows, tiles)
    sole = sole_sources(rows, tiles)
    L: list[str] = []
    A = L.append
    A("# Plant harvest coverage on Ash'karr — what a cut would cost")
    A("")
    A("Generated by `design/Jawa/mods/plant_harvest_coverage.py` from")
    A("`plant_cherrypick_candidates.csv` × `world/ASHKARR_WORLDMAP_tiles.csv`.")
    A("Discharges the second criterion of `PLANT_CHERRYPICK_PASS_1`.")
    A("")
    A("⚠️ **Nothing is cut.** The owner ruled keep-all on 2026-08-22 pending a walk of the")
    A("world, so every figure below is the *price* of a future cut, not a present defect.")
    A("")

    missing = sorted(b for b in tiles if b not in cov and b not in PLANTLESS_BY_DESIGN)
    A(f"**{len(tiles)} biomes on the planet · {len(cov)} carry reachable plants · "
      f"{len(PLANTLESS_BY_DESIGN & set(tiles))} are plantless by design.**")
    A("")
    if missing:
        A("## 🔴 A biome with no reachable plant at all")
        A("")
        for b in missing:
            A(f"- **`{b}`** — {tiles[b]} tiles, and not one plant in the candidate list "
              f"reaches it. Nothing grows there in any season.")
        A("")

    A("## Per biome")
    A("")
    A("| biome | tiles | plants | resources | wood sources | fragile (sole-source) |")
    A("|---|---:|---:|---:|---:|---|")
    for b in sorted(cov, key=lambda x: -tiles[x]):
        by = cov[b]
        plants = len({d for ds in by.values() for d in ds}) or sum(
            1 for r in rows if b in (r.get('biomes') or '').split('|'))
        plants = sum(1 for r in rows if b in (r.get('biomes') or '').split('|'))
        wood = len(by.get('WoodLog', []))
        frag = sorted(res for res, ds in by.items() if len(ds) == 1)
        woodcell = ("🔴 **0**" if wood == 0 else ("⚠️ **1**" if wood == 1 else str(wood)))
        A(f"| `{b}` | {tiles[b]} | {plants} | {len(by)} | {woodcell} | "
          + (", ".join(f"`{x}`" for x in frag) if frag else "—") + " |")
    A("")

    nowood = [b for b in cov if not cov[b].get('WoodLog')]
    onewood = [b for b in cov if len(cov[b].get('WoodLog', [])) == 1]
    if nowood:
        A("## 🔴 Biomes with no wood at all — before any cut")
        A("")
        for b in sorted(nowood, key=lambda x: -tiles[x]):
            A(f"- **`{b}`** ({tiles[b]} tiles) — no plant here yields `WoodLog`. "
              f"A colony landing on it has no wood without hauling it in.")
        A("")
    if onewood:
        A("## ⚠️ Biomes hanging on ONE wood source")
        A("")
        A("Cut the named plant and the biome joins the list above.")
        A("")
        for b in sorted(onewood, key=lambda x: -tiles[x]):
            A(f"- **`{b}`** ({tiles[b]} tiles) — `{cov[b]['WoodLog'][0]}`, and nothing else.")
        A("")

    A("## The sole-source roster")
    A("")
    A(f"**{len(sole)} of {len(rows)} plants are the only supplier of some resource in some "
      f"biome.** Cutting one of these does not thin a biome; it deletes a resource from it.")
    A("")
    A("| plant | resource(s) | biome(s) |")
    A("|---|---|---|")
    for d, pairs in sorted(sole.items(), key=lambda kv: (-len(kv[1]), kv[0])):
        res = sorted({r for _, r in pairs})
        bs = sorted({b for b, _ in pairs}, key=lambda x: -tiles[x])
        A(f"| `{d}` | " + ", ".join(f"`{x}`" for x in res) + " | "
          + ", ".join(f"`{b}`" for b in bs) + " |")
    A("")
    return "\n".join(L) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--md")
    args = ap.parse_args()
    rows, tiles = load_rows(), tile_counts()
    text = report(rows, tiles)
    if args.md:
        open(args.md, "w", encoding="utf-8").write(text)
        sole = sole_sources(rows, tiles)
        cov = coverage(rows, tiles)
        print(f"wrote {args.md}")
        print(f"  {len(rows)} plants · {len(cov)} biomes with flora · "
              f"{len(sole)} sole-source plants · "
              f"{sum(1 for b in cov if not cov[b].get('WoodLog'))} biomes with no wood")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
