#!/usr/bin/env python3
"""rimflow/render.py — every derived view, rebuilt from `events.jsonl` alone.

WHAT THIS PRODUCES, AND WHY EACH ONE IS DERIVED
===============================================
One artifact, never hand-edited:

    infrastructure/state/queue/<SEAT>.md      a GENERATED VIEW of the one ledger

⭐ 2026-08-27: `board.json` and the status board it fed are GONE. The owner retired
the web page — git is the provenance — so this module renders queue views and
nothing else.

The queue view exists so that a human reading a file and a seat running
`rimflow next` **cannot disagree**. The items are emitted in `priority.rank()`
order — the same function `next` calls, not a re-implementation of it — so the
top of the file IS the next item, by construction rather than by discipline.

⛔ THE VIEW CARRIES ONE LINE PER ITEM, NEVER THE PROSE.
The prose lives in `items/<ID>.md` and copying it here would recreate exactly the
drift the ledger was built to end: 827 KB of markdown in which the same item sat
in two queues with two different states. A summary line is a POINTER. If it is
wrong, nothing breaks, because nothing reads it but a human deciding whether to
open the item.

🔴 `render` DOES NOT WRITE `queue/*.md` BY DEFAULT, AND THAT IS THE POINT.
Those six files are the hand-written source of 142 items and ~827 KB of prose, and
until a human has checked the importer against them, a generator pointed at them is
a shredder. So the default target is `derived/queue_preview/<SEAT>.md` plus a diff
summary, and `--overwrite-queues` REFUSES unless the ledger holds at least as many
items as the queues do — printing both counts, because "it refused" without the
numbers tells you nothing about what to fix.

⭐ THE OUTPUT IS A PURE FUNCTION OF THE LEDGER — NO WALL CLOCK ANYWHERE.
`as_of` is the timestamp of the last EVENT, not the moment of rendering. That is
not cosmetic: it is what makes `reindex --verify` a real test. If a rendered
artifact carried `generated_at: now`, every verification would differ for a reason
that means nothing, and a byte-comparison that always fails teaches people to
ignore it. With the clock removed, a difference means exactly one of two things —
a bug in this file, or somebody hand-edited a generated artifact — and both are
things you want to be told about.

Stdlib only.

    python3 src/RimMandrake/rimflow/render.py                 render + diff summary
    python3 src/RimMandrake/rimflow/render.py --overwrite-queues
    python3 src/RimMandrake/rimflow/render.py reindex
    python3 src/RimMandrake/rimflow/render.py reindex --verify
    python3 src/RimMandrake/rimflow/render.py bench --events 2000
"""
import json
import os
import re
import shutil
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
if os.path.dirname(HERE) not in sys.path:
    sys.path.insert(0, os.path.dirname(HERE))

from rimflow import model, priority                                  # noqa: E402

STATE = model.STATE
QUEUE = os.path.join(STATE, "queue")
DERIVED = os.path.join(STATE, "derived")
PREVIEW = os.path.join(DERIVED, "queue_preview")

# The seats that get a rendered view, in board order.
#
# 🔴 OWNER IS NOT ONE OF THEM — owner's ruling, 2026-08-20. `queue/HUMAN.md` is HIS
# INBOX and stays hand-written.
#
# ⚠️ The migration made it a generated view and that was wrong. Prose written TO the
# owner has no home in the ledger by construction: an event carries scalars, an item
# file carries spec/verify/criteria, and a briefing is neither — which is exactly why
# 593 lines of his briefings had to be rescued into `preserved/` to survive the import
# at all. A do-not-edit banner on the one file a person writes in is the tool telling
# its user to go away.
#
# ✅ Owner-owned ITEMS still live in the ledger and are still offered by
# `rimflow next --seat OWNER`; they are simply not rendered over his prose.
# ⛔ Do not add OWNER back here. If a rendered view of owner items is ever wanted, give
# it its own filename — never HUMAN.md.
VIEW_SEATS = ("BENCH", "FOUNDRY")
FILENAME = {}

# The three seats that carry work items. Kept after the board's removal because
# bench() still round-robins synthetic items across them; it is no longer a grid.
COLS = ("DECIDE", "BUILD", "CHECK")

MARKER = "<!-- generated by rimflow render — derived, do not edit -->"
REGEN = "python3 src/RimMandrake/rimflow/render.py --overwrite-queues"
# 🔴 THE FLAG IS PART OF THE COMMAND. Without it `render` writes a PREVIEW to
# derived/preview/ and leaves queue/*.md untouched — and says so only as a diff
# table that reads like success. This string is what every seat sees at the top of
# its own queue; when it lacked the flag the queues sat frozen for 2h17m while four
# seats filed 24 items into them, and every seat read the stale copy. 2026-08-21.

CLOSING = ("close", "drop", "supersede")
SUMMARY_WIDTH = 110


# ---------------------------------------------------------------------------
# READING THE LEDGER
# ---------------------------------------------------------------------------
def build(events_path=None):
    """-> (world, events). One read, one replay; everything below is pure."""
    path = events_path or model.EVENTS
    events = model.read(path)
    return model.replay(events), events


def _closing_events(events):
    """-> (closed_at, close_days).

    `closed_at` is per item and covers close/drop/supersede, because "what left the
    queue recently" is the question the view answers. `close_days` counts `close`
    ONLY — a dropped item is scope leaving, not work landing, and mixing the two is
    how a velocity line starts flattering itself.
    """
    closed_at, close_days = {}, {}
    for ev in events:
        verb = ev.get("event")
        if verb not in CLOSING:
            continue
        iid, ts = ev.get("id"), ev.get("ts") or ""
        if iid:
            closed_at[iid] = ts
        if verb == "close" and ts:
            day = ts[:10]
            close_days[day] = close_days.get(day, 0) + 1
    return closed_at, close_days


def as_of(events):
    """The ledger's own clock. `None` on an empty ledger, which is honest."""
    for ev in reversed(events):
        if ev.get("ts"):
            return ev["ts"]
    return None


# ---------------------------------------------------------------------------
# THE ONE-LINE SUMMARY
# ---------------------------------------------------------------------------
_SPEC_RE = re.compile(r"^##\s+spec\s*$(.*?)(?=^##\s|\Z)", re.M | re.S | re.I)
_STRIP = re.compile(r"[`*_>#\[\]]")


# 🔴 ONE `listdir`, NOT ONE `open` PER ITEM. MEASURED, NOT ASSUMED.
# On this repo's 9p/DrvFs mount a failed `open()` costs ~0.8 ms — 500 of them is
# 404 ms, against 0.8 ms total on tmpfs. So an item with no prose file must never
# reach the filesystem: the directory is listed ONCE per render and absence is
# answered from that set. Rendering the whole ledger is supposed to cost less than
# one of those opens.
_INDEX = {"dir": None, "names": frozenset(), "cache": {}}


def item_index(items_dir=None, refresh=False):
    d = items_dir or model.ITEMS
    if refresh or _INDEX["dir"] != d:
        try:
            names = frozenset(os.listdir(d))
        except OSError:
            names = frozenset()
        _INDEX.update(dir=d, names=names, cache={})
    return _INDEX


def summary(iid, items_dir=None):
    """First sentence of `## spec`, flattened to ONE line.

    ⛔ Not the prose. This is a pointer at `items/<ID>.md`, deliberately lossy: a
    reader decides from it whether to open the item, and nothing else reads it at
    all. An item with no file says so, because "missing" is a fact worth seeing in
    the queue rather than a blank.
    """
    idx = item_index(items_dir)
    if iid in idx["cache"]:
        return idx["cache"][iid]
    name = "%s.md" % iid
    if name not in idx["names"]:
        return "(no items/%s.md yet — write one when you have something to say)" % iid
    try:
        with open(os.path.join(idx["dir"], name), encoding="utf-8") as fh:
            text = fh.read()
    except OSError:
        return "(no items/%s.md yet — write one when you have something to say)" % iid
    m = _SPEC_RE.search(text)
    body = m.group(1) if m else text
    for raw in body.splitlines():
        line = _STRIP.sub("", raw).strip()
        if line:
            line = " ".join(line.split())
            if len(line) > SUMMARY_WIDTH:
                line = line[:SUMMARY_WIDTH - 1].rstrip() + "…"
            idx["cache"][iid] = line
            return line
    return "(items/%s.md has no ## spec text)" % iid


# ---------------------------------------------------------------------------
# THE QUEUE VIEW
# ---------------------------------------------------------------------------
def _item_line(it, extra=None):
    """One item, one heading plus scalars.

    🔑 `## <ID> <title>` with `row:` and `state:` underneath. The ID grammar itself is
    `model.ID_RE` and lives only there — do not restate it here or in a doctrine file.
    """
    out = ["## %s %s" % (it.id, it.title or "")]
    out.append("state:    %s%s" % (it.state, "  (BLOCKED)" if it.blocked else ""))
    out.append("row:      %s" % (it.row if it.row not in (None, "") else "unassigned"))
    out.append("needs:    %s" % it.needs)
    out.append("target:   %s" % (it.target or "v1"))
    out.append("kind:     %s" % (it.kind or "task"))
    if it.this_deployment:
        out.append("flag:     this-deployment")
    for line in (extra or []):
        out.append(line)
    out.append("summary:  %s" % summary(it.id))
    out.append("prose:    infrastructure/state/items/%s.md" % it.id)
    out.append("")
    return out


def queue_view(world, seat, events, target="v1", ctx=None):
    """-> markdown text for one seat. Pure; no clock, no filesystem beyond items/."""
    closed_at, _ = _closing_events(events)
    mine = [i for i in world.items.values() if i.owner == seat]
    ranked = priority.rank(world, seat, target, ctx)
    ranked_ids = {i.id for i in ranked}

    doing = sorted((i for i in mine if i.state == "doing"),
                   key=lambda i: (i.created_at or "", i.id))
    blocked = sorted((i for i in mine if i.blocked and i.open),
                     key=lambda i: (i.created_at or "", i.id))
    blocked_ids = {i.id for i in blocked}
    waiting = sorted(
        (i for i in mine
         if i.state == "ready" and i.id not in ranked_ids and i.id not in blocked_ids
         and not priority.satisfiable(i, world, ctx, seat)),
        key=lambda i: (i.created_at or "", i.id))
    offtarget = sorted(
        (i for i in mine
         if i.state == "ready" and i.id not in ranked_ids and i.id not in blocked_ids
         and i.id not in {x.id for x in waiting}),
        key=lambda i: (i.created_at or "", i.id))
    proposed = sorted((i for i in mine if i.state == "proposed" and not i.blocked),
                      key=lambda i: (i.created_at or "", i.id))
    shut = sorted((i for i in mine if not i.open),
                  key=lambda i: (closed_at.get(i.id, ""), i.id), reverse=True)[:10]

    L = [MARKER,
         "# %s — generated queue view" % seat,
         "",
         "⛔ **DERIVED. DO NOT EDIT.** Every edit here is overwritten without warning.",
         "The truth is `infrastructure/state/ledger/events.jsonl`; the prose is",
         "`infrastructure/state/items/<ID>.md`. Regenerate with:",
         "",
         "    %s" % REGEN,
         "",
         "as-of: %s (the last event's own timestamp, not the render clock)"
         % (as_of(events) or "empty ledger"),
         "game:  %s   bridge: %s" % (world.game, world.bridge_holder or "free"),
         "",
         "# NEXT — `priority.rank()` order, top item first",
         ""]
    if ranked:
        L.append("The first heading below is what `rimflow next --seat %s` returns. "
                 "This file and that command call the same function, so they cannot "
                 "disagree." % seat)
        L.append("")
        for it in ranked:
            L += _item_line(it)
    else:
        L += ["Nothing is offered. That is a legitimate answer — check WAITING and "
              "BLOCKED below before concluding there is no work.", ""]

    def section(title, items, note, extra=None):
        # 🔑 `# `, not `## `. Any parser of this file reads the first token after
        # `## ` as an item ID, so a section header at h2 would file itself as an
        # item called NEXT or BLOCKED. Sections are h1; only items are h2.
        L.append("# %s" % title)
        L.append("")
        if not items:
            L.extend(["_none._", ""])
            return
        L.extend([note, ""])
        for it in items:
            L.extend(_item_line(it, extra(it) if extra else None))

    section("IN PROGRESS", doing,
            "Started, and therefore not offered again. `rimflow close` or "
            "`rimflow block` moves them.")
    section("BLOCKED — something is WRONG and someone must act", blocked,
            "⚠️ Blocked is not the same as waiting for a window. These need an "
            "action, not the passage of time.",
            lambda i: ["blocked:  %s%s" % (i.blocked_reason or "unexplained",
                                           " (on %s)" % i.blocked_on
                                           if i.blocked_on else "")])
    section("WAITING ON A WINDOW — nothing is wrong", waiting,
            "🔑 These are ready and unblocked; their `needs` is simply not "
            "satisfiable while the game is %s. ⚠️ A `bridge` row does NOT reopen on "
            "its own — it reopens when the seat holding the bridge releases it."
            % world.game,
            lambda i: ["waiting:  needs `%s`, game is %s" % (i.needs, world.game)])
    section("NOT THIS TARGET", offtarget,
            "Ready, but aimed at another version. A planning decision, not a defect.")
    section("PROPOSED — filed, not yet taken", proposed,
            "Claim one to work it. Any item can be claimed and started; the prose "
            "sections are good practice, never a precondition.",
            lambda i: ["thin:     %s" % (", ".join("no ## " + m for m in model._missing(i))
                                         or "spec, verify and criteria all present")])

    # ⛔ NO "CLOSED RECENTLY" SECTION. Owner's ruling 2026-08-26: "clear out any closed
    # items still in your queue or other files... anything done is GONE." A queue is what
    # is LEFT TO DO; a list of finished work at the bottom of it is read as work, and every
    # seat pays to re-skim it. The record of what closed is the ledger, which is
    # append-only and complete: `rimflow show <ID>` and `git log` both still answer it.
    return "\n".join(L).rstrip() + "\n"


# ---------------------------------------------------------------------------
# WRITING
# ---------------------------------------------------------------------------
def _write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path + ".tmp", "w", encoding="utf-8") as fh:
        fh.write(text)
    os.replace(path + ".tmp", path)


def _queue_path(seat, root=None):
    # Resolved at CALL time. A `root=QUEUE` default binds at import and quietly
    # ignores any redirection — which is how a selftest ends up writing the real
    # queue files it was meant to leave alone.
    return os.path.join(root or QUEUE, "%s.md" % FILENAME.get(seat, seat))


_HEAD_RE = re.compile(r"^##\s+(\S+)")


def queue_item_ids(path):
    """-> set of IDs filed in a hand-written queue file.

    Only headings whose first token is a legal item ID count. `## 🔴 OWNER RULINGS,
    2026-08-19` is a prose section, not an item, and counting it would demand the
    ledger hold prose.
    """
    out = set()
    try:
        with open(path, encoding="utf-8") as fh:
            lines = fh.read().splitlines()
    except OSError:
        return out
    heads = [i for i, l in enumerate(lines) if _HEAD_RE.match(l)] + [len(lines)]
    for a, b in zip(heads, heads[1:]):
        m = _HEAD_RE.match(lines[a])
        # ⛔ `model.is_item_heading`, NOT a local rule. This function and the importer
        # MUST count the same things or the overwrite guard cries wolf — it did, on
        # 2026-08-20, counting `## A (DECIDE…)`, `## FYI…`, `## The…` as items and
        # refusing a migration that was actually complete.
        if m and model.is_item_heading(m.group(1), lines[a + 1:b]):
            out.add(m.group(1))
    return out


def queue_census(root=None):
    """-> (total_ids, {file: n}). Every file in queue/, archives included.

    Archives count. An item that closed is still a
    row the ledger has to be able to reproduce before anything is allowed to
    overwrite the originals.
    """
    root = root or QUEUE
    per, ids = {}, set()
    try:
        names = sorted(os.listdir(root))
    except OSError:
        return 0, {}
    for name in names:
        if not name.endswith(".md"):
            continue
        got = queue_item_ids(os.path.join(root, name))
        per[name] = len(got)
        ids |= got
    return len(ids), per


def render(events_path=None, out_dir=None, overwrite_queues=False, target="v1",
           ctx=None, quiet=False, queue_root=None):
    """Write the queue views. -> dict summary.

    🔴 The refusal below is the whole safety property of this module. Six files, 827
    KB, 142 items of hand-written prose, and a generator that would replace them with
    whatever the ledger currently holds — including nothing. So the ledger must first
    demonstrate that it can reproduce at least as many items as the queues contain,
    and the refusal prints BOTH counts, because a refusal without numbers cannot be
    acted on.
    """
    t0 = time.perf_counter()
    item_index(refresh=True)          # one listdir for the whole render; see above
    world, events = build(events_path)
    t_ledger = (time.perf_counter() - t0) * 1000.0
    out_dir = out_dir or PREVIEW
    queue_root = queue_root or QUEUE

    t = time.perf_counter()
    q_total, q_per = queue_census(queue_root)
    t_census = (time.perf_counter() - t) * 1000.0
    refused = None
    if overwrite_queues and len(world.items) < q_total:
        refused = (
            "REFUSED to overwrite queue/*.md: the ledger holds %d item(s) and the "
            "queues hold %d. Overwriting now would delete %d item(s) that exist only "
            "as hand-written prose, and the ledger is append-only — nothing here "
            "could put them back.\n"
            "    ledger : %d item(s)  (%s)\n"
            "    queues : %d item(s)  %s\n"
            "Run the importer first, then re-run with --overwrite-queues."
            % (len(world.items), q_total, q_total - len(world.items),
               len(world.items), events_path or model.EVENTS, q_total,
               ", ".join("%s=%d" % (k, v) for k, v in sorted(q_per.items()))))
        overwrite_queues = False

    target_dir = queue_root if overwrite_queues else out_dir
    t = time.perf_counter()
    written, diffs = [], []
    for seat in VIEW_SEATS:
        text = queue_view(world, seat, events, target, ctx)
        path = _queue_path(seat, target_dir)
        _write(path, text)
        written.append(path)
        if not overwrite_queues:
            real = _queue_path(seat, queue_root)
            have = queue_item_ids(real)
            mine = {i.id for i in world.items.values() if i.owner == seat}
            diffs.append({"seat": seat, "preview": path, "queue": real,
                          "in_ledger_only": sorted(mine - have),
                          "in_queue_only": sorted(have - mine),
                          "both": len(mine & have)})

    t_views = (time.perf_counter() - t) * 1000.0
    ms = (time.perf_counter() - t0) * 1000.0

    summary_ = {"ms": ms,
                # 🔑 Attributed, because an unattributed total cannot be fixed by
                # anyone. `ledger` is model.read + model.replay and is not this
                # module's to speed up — see the note in bench().
                "stages": {"ledger": t_ledger, "census": t_census,
                           "views": t_views}, "written": written, "diffs": diffs,
                "refused": refused, "items": len(world.items), "events": len(events),
                "queue_items": q_total, "overwrote": overwrite_queues,
                "errors": len(world.errors)}
    if not quiet:
        _print_render(summary_)
    return summary_


def _print_render(s):
    if s["refused"]:
        print("🔴 " + s["refused"], file=sys.stderr)
    print("queue views: %d event(s) -> %d item(s)%s"
          % (s["events"], s["items"],
             ", %d replay refusal(s)" % s["errors"] if s["errors"] else ""))
    if s["overwrote"]:
        print("⚠️  OVERWROTE the real queue/*.md — %d file(s)" % len(s["written"]))
    else:
        # 🔑 Say the negative out loud. The table below is easy to read as a success
        # report; it is a report of how far the real queues have drifted. ⚠️ Do NOT
        # quote `in_ledger_only` as a staleness count — it includes every CLOSED item,
        # which a view legitimately shows only the last 10 of.
        print("PREVIEW ONLY — queue/*.md NOT written. The seats are still reading "
              "whatever\nthey said before this run. Re-run with --overwrite-queues "
              "to publish.")
    for d in s["diffs"]:
        print("  %-7s preview %-4s | queue %-4s | shared %-4s%s"
              % (d["seat"], len(d["in_ledger_only"]) + d["both"],
                 len(d["in_queue_only"]) + d["both"], d["both"],
                 "   ⚠ %d only in queue" % len(d["in_queue_only"])
                 if d["in_queue_only"] else ""))
    # ⚠️ Reported against the 60 s CADENCE, not against a 100 ms stopwatch. The
    # plan's 100 ms target was measured on tmpfs and is unreachable on this repo's
    # 9p mount by any caching strategy: `stat`-ing the 144 item files alone costs
    # 130 ms, so a cache that verifies freshness is already over budget before it
    # parses anything. What the target was PROXYING for — "slow cadence, nothing
    # that stresses the system" — holds comfortably: 374 ms every 60 s is 0.62%
    # of one core. A warm in-process replay is ~1 ms, which is what a long-lived
    # publisher actually pays.
    print("render: %.1f ms  (%.2f%% of one core at the 60 s cadence)"
          % (s["ms"], 100.0 * s["ms"] / 60000.0))


# ---------------------------------------------------------------------------
# REINDEX
# ---------------------------------------------------------------------------
def _tree(root):
    out = {}
    for dirpath, _dirs, files in os.walk(root):
        for f in files:
            if f.endswith(".tmp"):
                continue
            p = os.path.join(dirpath, f)
            out[os.path.relpath(p, root)] = open(p, "rb").read()
    return out


def reindex(verify=False, events_path=None, target="v1", ctx=None):
    """Rebuild every derived artifact from `events.jsonl` alone.

    ⭐ `--verify` is the real test of the claim that the ledger IS the truth. It
    renders into a scratch tree and compares BYTE FOR BYTE with what is on disk.
    Because nothing rendered contains a wall clock, a difference has exactly two
    possible causes — a bug in this file, or a hand edit to a generated artifact —
    and both are things somebody needs to see.

    ⚠️ The scratch tree is under the repo, never `/tmp`. They are different
    filesystems here (9p vs tmpfs) and a test that runs on the wrong one has already
    reported green while the real disk was losing 83% of its writes.
    """
    if not verify:
        s = render(events_path=events_path, target=target, ctx=ctx)
        return 0 if not s["refused"] else 1

    scratch = os.path.join(DERIVED, ".verify")
    shutil.rmtree(scratch, ignore_errors=True)
    os.makedirs(scratch, exist_ok=True)
    try:
        s = render(events_path=events_path,
                   out_dir=os.path.join(scratch, "queue_preview"),
                   target=target, ctx=ctx, quiet=True)
        fresh = _tree(scratch)
        same, differ, missing = [], [], []
        for rel, blob in sorted(fresh.items()):
            live = os.path.join(DERIVED, rel)
            try:
                with open(live, "rb") as fh:
                    cur = fh.read()
            except OSError:
                missing.append(rel)
                continue
            (same if cur == blob else differ).append(rel)
        print("reindex --verify: %d identical, %d differ, %d missing on disk"
              % (len(same), len(differ), len(missing)))
        for rel in differ:
            print("  DIFFERS  %s  — a bug in render.py, or somebody hand-edited a "
                  "generated file" % rel)
        for rel in missing:
            print("  MISSING  %s  — never rendered; run `render` first" % rel)
        print("  ⚠ queue/*.md is NOT compared: it is still hand-written and is not "
              "generated until --overwrite-queues is allowed.")
        print("render: %.1f ms (target 100 ms%s)"
              % (s["ms"], "" if s["ms"] <= 100 else
                 " — OVER by %.1f ms" % (s["ms"] - 100)))
        return 0 if not (differ or missing) else 1
    finally:
        shutil.rmtree(scratch, ignore_errors=True)


# ---------------------------------------------------------------------------
# BENCH — the 100 ms target, measured rather than asserted
# ---------------------------------------------------------------------------
def bench(n=2000, with_prose=True):
    """Render a synthetic ledger of `n` events and report the time, stage by stage.

    The live ledger is young; a target measured against 3 events proves nothing. The
    plan measured ~1,100 events in 8 days, so 2,000 is roughly a fortnight of work.

    🔑 It writes real `items/<ID>.md` files and points `model.ITEMS` at them, because
    the honest cost of a render on this filesystem is dominated by how many times it
    touches `items/`, and a bench with no prose on disk would flatter every number.
    ⚠️ Everything is under the repo, on the filesystem this actually runs on — the
    same trap `selftest_concurrency.py` fell into when it defaulted to /tmp.
    """
    d = os.path.join(DERIVED, ".bench")
    shutil.rmtree(d, ignore_errors=True)
    items_dir = os.path.join(d, "items")
    os.makedirs(items_dir, exist_ok=True)
    path = os.path.join(d, "events.jsonl")
    real_items = model.ITEMS
    try:
        with open(path, "w", encoding="utf-8") as fh:
            for i in range(n // 4):
                iid = "SYNTHETIC_BENCH_ITEM_%d" % i
                seat = COLS[i % 3]
                if with_prose:
                    with open(os.path.join(items_dir, "%s.md" % iid), "w",
                              encoding="utf-8") as ih:
                        ih.write("## spec\nbench item %d, one line of spec.\n\n"
                                 "## verify\nrun it\n\n## criteria\nit ran\n" % i)
                for ev in (
                    {"seat": "DECIDE", "event": "file", "id": iid,
                     "title": "bench %d" % i, "kind": "task", "for": seat,
                     "row": str(i % 20)},
                    {"seat": seat, "event": "claim", "id": iid},
                    {"seat": seat, "event": "note", "id": iid, "text": "bench"},
                    {"seat": seat, "event": "close", "id": iid, "sha": "abc1234"},
                ):
                    ev["ts"] = "2026-08-%02dT00:00:%02dZ" % (1 + i % 20, i % 60)
                    fh.write(json.dumps(ev, separators=(",", ":")) + "\n")
        model.ITEMS = items_dir
        best, st = None, None
        for _ in range(3):
            s = render(events_path=path, out_dir=os.path.join(d, "queue_preview"),
                       quiet=True)
            if best is None or s["ms"] < best:
                best, st = s["ms"], s["stages"]
        over = best - 100.0
        print("bench: %d events, %d items, prose on disk=%s"
              % (n, s["items"], with_prose))
        print("  total   %7.1f ms  (best of 3; target 100 ms%s)"
              % (best, "" if over <= 0 else " — OVER by %.1f ms" % over))
        for k in ("ledger", "census", "views"):
            print("    %-8s %7.1f ms%s" % (k, st[k],
                  "  ⚠️ model.read + model.replay; replay opens items/<ID>.md once "
                  "per claim/start event, and a single open costs ~0.8 ms on this "
                  "9p mount" if k == "ledger" else ""))
        print("  render's own work (census+views): %.1f ms"
              % (st["census"] + st["views"]))
        return 0 if over <= 0 else 1
    finally:
        model.ITEMS = real_items
        shutil.rmtree(d, ignore_errors=True)


# ---------------------------------------------------------------------------
def main(argv=None):
    argv = list(sys.argv[1:] if argv is None else argv)
    cmd = argv[0] if argv and not argv[0].startswith("-") else "render"
    if argv and argv[0] == cmd and not argv[0].startswith("-"):
        argv = argv[1:]
    if cmd == "reindex":
        return reindex(verify="--verify" in argv)
    if cmd == "bench":
        n = 2000
        if "--events" in argv:
            n = int(argv[argv.index("--events") + 1])
        return bench(n, with_prose="--no-prose" not in argv)
    if cmd != "render":
        print("usage: render.py [render [--overwrite-queues]] | reindex [--verify] "
              "| bench [--events N]", file=sys.stderr)
        return 2
    s = render(overwrite_queues="--overwrite-queues" in argv)
    return 1 if s["refused"] else 0


if __name__ == "__main__":
    sys.exit(main())
