#!/usr/bin/env python3
"""rimflow/render.py — every derived view, rebuilt from `events.jsonl` alone.

WHAT THIS PRODUCES, AND WHY EACH ONE IS DERIVED
===============================================
Two artifacts, and neither is ever hand-edited:

    infrastructure/state/queue/<SEAT>.md      a GENERATED VIEW of the one ledger
    infrastructure/state/derived/board.json   everything the status board needs

The queue view exists so that a human reading a file and a seat running
`rimflow next` **cannot disagree**. The items are emitted in `priority.rank()`
order — the same function `next` calls, not a re-implementation of it — so the
top of the file IS the next item, by construction rather than by discipline.

⛔ THE VIEW CARRIES ONE LINE PER ITEM, NEVER THE PROSE.
The prose lives in `items/<ID>.md` and copying it here would recreate exactly the
drift the ledger was built to end: 827 KB of markdown in which the same item sat
in two queues with two different states. A summary line is a POINTER. If it is
wrong, nothing breaks, because nothing reads it but a human deciding whether to
open the item.

🔴 `render` DOES NOT WRITE `queue/*.md` BY DEFAULT, AND THAT IS THE POINT.
Those six files are the hand-written source of 142 items and ~827 KB of prose, and
until a human has checked the importer against them, a generator pointed at them is
a shredder. So the default target is `derived/queue_preview/<SEAT>.md` plus a diff
summary, and `--overwrite-queues` REFUSES unless the ledger holds at least as many
items as the queues do — printing both counts, because "it refused" without the
numbers tells you nothing about what to fix.

⭐ THE OUTPUT IS A PURE FUNCTION OF THE LEDGER — NO WALL CLOCK ANYWHERE.
`as_of` is the timestamp of the last EVENT, not the moment of rendering. That is
not cosmetic: it is what makes `reindex --verify` a real test. If a rendered
artifact carried `generated_at: now`, every verification would differ for a reason
that means nothing, and a byte-comparison that always fails teaches people to
ignore it. With the clock removed, a difference means exactly one of two things —
a bug in this file, or somebody hand-edited a generated artifact — and both are
things you want to be told about.

Stdlib only.

    python3 src/RimMandrake/rimflow/render.py                 render + diff summary
    python3 src/RimMandrake/rimflow/render.py --overwrite-queues
    python3 src/RimMandrake/rimflow/render.py reindex
    python3 src/RimMandrake/rimflow/render.py reindex --verify
    python3 src/RimMandrake/rimflow/render.py bench --events 2000
"""
import json
import os
import re
import shutil
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
if os.path.dirname(HERE) not in sys.path:
    sys.path.insert(0, os.path.dirname(HERE))

from rimflow import model, priority                                  # noqa: E402

STATE = model.STATE
QUEUE = os.path.join(STATE, "queue")
DERIVED = os.path.join(STATE, "derived")
PREVIEW = os.path.join(DERIVED, "queue_preview")
BOARD = os.path.join(DERIVED, "board.json")

# The seats that get a rendered view, in board order. OWNER's queue file has always
# been called HUMAN.md; the view keeps that name so a diff against the real file is
# a direct comparison rather than a rename nobody asked for.
VIEW_SEATS = ("DECIDE", "BUILD", "CHECK", "REP", "OWNER")
FILENAME = {"OWNER": "HUMAN"}

# ⚠️ `rows` keeps THREE columns because `status_server.py` renders exactly three and
# a fourth would push a column off the grid. REP and OWNER are not dropped — they are
# reported in `seats`, which is new. See the header note in board().
COLS = ("DECIDE", "BUILD", "CHECK")

MARKER = "<!-- generated by rimflow render — derived, do not edit -->"
REGEN = "python3 src/RimMandrake/rimflow/render.py"

CLOSING = ("close", "drop", "supersede")
SUMMARY_WIDTH = 110


# ---------------------------------------------------------------------------
# READING THE LEDGER
# ---------------------------------------------------------------------------
def build(events_path=None):
    """-> (world, events). One read, one replay; everything below is pure."""
    path = events_path or model.EVENTS
    events = model.read(path)
    return model.replay(events), events


def _closing_events(events):
    """-> (closed_at, close_days).

    `closed_at` is per item and covers close/drop/supersede, because "what left the
    queue recently" is the question the view answers. `close_days` counts `close`
    ONLY — a dropped item is scope leaving, not work landing, and mixing the two is
    how a velocity line starts flattering itself.
    """
    closed_at, close_days = {}, {}
    for ev in events:
        verb = ev.get("event")
        if verb not in CLOSING:
            continue
        iid, ts = ev.get("id"), ev.get("ts") or ""
        if iid:
            closed_at[iid] = ts
        if verb == "close" and ts:
            day = ts[:10]
            close_days[day] = close_days.get(day, 0) + 1
    return closed_at, close_days


def as_of(events):
    """The ledger's own clock. `None` on an empty ledger, which is honest."""
    for ev in reversed(events):
        if ev.get("ts"):
            return ev["ts"]
    return None


# ---------------------------------------------------------------------------
# THE ONE-LINE SUMMARY
# ---------------------------------------------------------------------------
_SPEC_RE = re.compile(r"^##\s+spec\s*$(.*?)(?=^##\s|\Z)", re.M | re.S | re.I)
_STRIP = re.compile(r"[`*_>#\[\]]")


# 🔴 ONE `listdir`, NOT ONE `open` PER ITEM. MEASURED, NOT ASSUMED.
# On this repo's 9p/DrvFs mount a failed `open()` costs ~0.8 ms — 500 of them is
# 404 ms, against 0.8 ms total on tmpfs. So an item with no prose file must never
# reach the filesystem: the directory is listed ONCE per render and absence is
# answered from that set. Rendering the whole ledger is supposed to cost less than
# one of those opens.
_INDEX = {"dir": None, "names": frozenset(), "cache": {}}


def item_index(items_dir=None, refresh=False):
    d = items_dir or model.ITEMS
    if refresh or _INDEX["dir"] != d:
        try:
            names = frozenset(os.listdir(d))
        except OSError:
            names = frozenset()
        _INDEX.update(dir=d, names=names, cache={})
    return _INDEX


def summary(iid, items_dir=None):
    """First sentence of `## spec`, flattened to ONE line.

    ⛔ Not the prose. This is a pointer at `items/<ID>.md`, deliberately lossy: a
    reader decides from it whether to open the item, and nothing else reads it at
    all. An item with no file says so, because "missing" is a fact worth seeing in
    the queue rather than a blank.
    """
    idx = item_index(items_dir)
    if iid in idx["cache"]:
        return idx["cache"][iid]
    name = "%s.md" % iid
    if name not in idx["names"]:
        return "(no items/%s.md yet — cannot enter `ready` without spec/verify/criteria)" % iid
    try:
        with open(os.path.join(idx["dir"], name), encoding="utf-8") as fh:
            text = fh.read()
    except OSError:
        return "(no items/%s.md yet — cannot enter `ready` without spec/verify/criteria)" % iid
    m = _SPEC_RE.search(text)
    body = m.group(1) if m else text
    for raw in body.splitlines():
        line = _STRIP.sub("", raw).strip()
        if line:
            line = " ".join(line.split())
            if len(line) > SUMMARY_WIDTH:
                line = line[:SUMMARY_WIDTH - 1].rstrip() + "…"
            idx["cache"][iid] = line
            return line
    return "(items/%s.md has no ## spec text)" % iid


# ---------------------------------------------------------------------------
# THE QUEUE VIEW
# ---------------------------------------------------------------------------
def _item_line(it, extra=None):
    """One item, one heading plus scalars — in the field shape derive_matrix parses.

    🔑 `## <ID> <title>` with `row:` and `state:` underneath is not nostalgia: it is
    the exact grammar `Utils/derive_matrix.py` already reads, so the day these files
    become real, the old board keeps working without a change.
    """
    out = ["## %s %s" % (it.id, it.title or "")]
    out.append("state:    %s%s" % (it.state, "  (BLOCKED)" if it.blocked else ""))
    out.append("row:      %s" % (it.row if it.row not in (None, "") else "unassigned"))
    out.append("needs:    %s" % it.needs)
    out.append("target:   %s" % (it.target or "v1"))
    out.append("kind:     %s" % (it.kind or "task"))
    if it.this_deployment:
        out.append("flag:     this-deployment")
    for line in (extra or []):
        out.append(line)
    out.append("summary:  %s" % summary(it.id))
    out.append("prose:    infrastructure/state/items/%s.md" % it.id)
    out.append("")
    return out


def queue_view(world, seat, events, target="v1", ctx=None):
    """-> markdown text for one seat. Pure; no clock, no filesystem beyond items/."""
    closed_at, _ = _closing_events(events)
    mine = [i for i in world.items.values() if i.owner == seat]
    ranked = priority.rank(world, seat, target, ctx)
    ranked_ids = {i.id for i in ranked}

    doing = sorted((i for i in mine if i.state == "doing"),
                   key=lambda i: (i.created_at or "", i.id))
    blocked = sorted((i for i in mine if i.blocked and i.open),
                     key=lambda i: (i.created_at or "", i.id))
    blocked_ids = {i.id for i in blocked}
    waiting = sorted(
        (i for i in mine
         if i.state == "ready" and i.id not in ranked_ids and i.id not in blocked_ids
         and not priority.satisfiable(i, world, ctx)),
        key=lambda i: (i.created_at or "", i.id))
    offtarget = sorted(
        (i for i in mine
         if i.state == "ready" and i.id not in ranked_ids and i.id not in blocked_ids
         and i.id not in {x.id for x in waiting}),
        key=lambda i: (i.created_at or "", i.id))
    proposed = sorted((i for i in mine if i.state == "proposed" and not i.blocked),
                      key=lambda i: (i.created_at or "", i.id))
    shut = sorted((i for i in mine if not i.open),
                  key=lambda i: (closed_at.get(i.id, ""), i.id), reverse=True)[:10]

    L = [MARKER,
         "# %s — generated queue view" % seat,
         "",
         "⛔ **DERIVED. DO NOT EDIT.** Every edit here is overwritten without warning.",
         "The truth is `infrastructure/state/ledger/events.jsonl`; the prose is",
         "`infrastructure/state/items/<ID>.md`. Regenerate with:",
         "",
         "    %s" % REGEN,
         "",
         "as-of: %s (the last event's own timestamp, not the render clock)"
         % (as_of(events) or "empty ledger"),
         "game:  %s   bridge: %s" % (world.game, world.bridge_holder or "free"),
         "",
         "# NEXT — `priority.rank()` order, top item first",
         ""]
    if ranked:
        L.append("The first heading below is what `rimflow next --seat %s` returns. "
                 "This file and that command call the same function, so they cannot "
                 "disagree." % seat)
        L.append("")
        for it in ranked:
            L += _item_line(it)
    else:
        L += ["Nothing is offered. That is a legitimate answer — check WAITING and "
              "BLOCKED below before concluding there is no work.", ""]

    def section(title, items, note, extra=None):
        # 🔑 `# `, not `## `. `derive_matrix.parse()` reads the first token after
        # `## ` as an item ID, so a section header at h2 would file itself as an
        # item called NEXT or BLOCKED. Sections are h1; only items are h2.
        L.append("# %s" % title)
        L.append("")
        if not items:
            L.extend(["_none._", ""])
            return
        L.extend([note, ""])
        for it in items:
            L.extend(_item_line(it, extra(it) if extra else None))

    section("IN PROGRESS", doing,
            "Started, and therefore not offered again. `rimflow close` or "
            "`rimflow block` moves them.")
    section("BLOCKED — something is WRONG and someone must act", blocked,
            "⚠️ Blocked is not the same as waiting for a window. These need an "
            "action, not the passage of time.",
            lambda i: ["blocked:  %s%s" % (i.blocked_reason or "unexplained",
                                           " (on %s)" % i.blocked_on
                                           if i.blocked_on else "")])
    section("WAITING ON A WINDOW — nothing is wrong", waiting,
            "🔑 These are ready and unblocked; their `needs` is simply not "
            "satisfiable while the game is %s. They will offer themselves when it "
            "changes." % world.game,
            lambda i: ["waiting:  needs `%s`, game is %s" % (i.needs, world.game)])
    section("NOT THIS TARGET", offtarget,
            "Ready, but aimed at another version. A planning decision, not a defect.")
    section("PROPOSED — cannot enter `ready` yet", proposed,
            "An item without spec/verify/criteria in its `items/<ID>.md` cannot "
            "start. The missing sections are named per item.",
            lambda i: ["missing:  %s" % (", ".join("## " + m for m in model._missing(i))
                                         or "nothing — claim it")])

    L.append("# CLOSED RECENTLY — the last 10, newest first")
    L.append("")
    if shut:
        L += ["⭐ Terminal, permanently. A failed run or a dropped item is not a hole "
              "in the record — it IS the record. Follow-up work is a NEW item linked "
              "with `caused_by`.", ""]
        for it in shut:
            L.append("- `%s` **%s** %s%s — %s"
                     % (it.id, it.state,
                        (closed_at.get(it.id) or "")[:10],
                        (" at %s" % it.closed_sha) if it.closed_sha else "",
                        it.title or ""))
        L.append("")
    else:
        L += ["_none._", ""]
    return "\n".join(L).rstrip() + "\n"


# ---------------------------------------------------------------------------
# THE BOARD
# ---------------------------------------------------------------------------
def _rownames():
    """Row labels from V1.md, so the board and the burn-down cannot disagree.

    Re-implemented from `derive_matrix.rownames()` rather than imported: rimflow is
    stdlib-only and must not take a dependency on a Utils script that reads the
    queues it is replacing.
    """
    out = {}
    try:
        with open(os.path.join(STATE, "V1.md"), encoding="utf-8") as fh:
            for ln in fh:
                m = re.match(r"\|\s*(\d+)\s*\|\s*([^|]+?)\s*\|", ln)
                if m:
                    out[m.group(1)] = "%s %s" % (m.group(1), m.group(2))
    except OSError:
        pass
    return out


def _rowkey(it):
    return (str(it.row).strip() if it.row not in (None, "") else "unassigned")


def _velocity(close_days, remaining):
    """Closes per day, straight off the `close` events. Same shape as derive_matrix.

    ⚠️ `eta_days` is a trend line, not a date: it assumes today's rate and a fixed
    scope, and v1's scope has already moved once.
    """
    if not close_days:
        return {"days": [], "per_day": 0.0, "closed": 0,
                "remaining": remaining, "eta_days": None}
    span = sorted(close_days)
    total = sum(close_days.values())
    try:
        import datetime as _dt
        elapsed = max(1, (_dt.date.fromisoformat(span[-1])
                          - _dt.date.fromisoformat(span[0])).days + 1)
    except Exception:
        elapsed = max(1, len(span))
    rate = total / elapsed
    return {"days": [{"d": d, "n": close_days[d]} for d in span],
            "per_day": round(rate, 2), "closed": total, "remaining": remaining,
            "eta_days": int(round(remaining / rate)) if rate and remaining else None}


def board(world, events, target="v1", ctx=None):
    """-> dict. Everything the status board needs, from the ledger alone."""
    closed_at, close_days = _closing_events(events)
    names = _rownames()

    # --- rows, in status_matrix.json's shape -------------------------------
    grid = {}
    for it in world.items.values():
        if it.owner not in COLS:
            continue
        grid.setdefault(_rowkey(it), {c: [] for c in COLS})[it.owner].append(it)
    order = sorted(names, key=int) + [k for k in sorted(grid) if k not in names]
    rows = []
    for key in order:
        cells = {}
        for col in COLS:
            its = [i for i in grid.get(key, {}).get(col, [])
                   if i.state not in ("dropped", "superseded")]
            # `closed` vs `done`: derive_matrix split these because its numerator came
            # from git trailers and its denominator from the queue files. Here every
            # close carries a sha in the ledger, so all of them are `closed` and
            # `done` is structurally zero. The renderer sums both segments, so the
            # bar draws identically.
            done = sum(1 for i in its if i.state == "done")
            st = ("blocked" if any(i.blocked for i in its)
                  else "working" if any(i.state == "doing" for i in its)
                  else "offline" if not its
                  else "idle" if done < len(its) else "idle")
            cells[col] = {
                "done": done, "total": len(its), "state": st,
                "mix": {"closed": done, "done": 0,
                        "doing": sum(1 for i in its if i.state == "doing"),
                        "blocked": sum(1 for i in its if i.blocked),
                        "ready": sum(1 for i in its
                                     if i.state in ("proposed", "ready")
                                     and not i.blocked)}}
        rows.append({"name": names.get(key, key), "cells": cells})

    # --- blockers ----------------------------------------------------------
    classes, on_human = {}, 0
    blocked_list = []
    for it in sorted(world.items.values(), key=lambda i: i.id):
        if not (it.blocked and it.open):
            continue
        reason = it.blocked_reason or "unexplained"
        classes[reason] = classes.get(reason, 0) + 1
        if it.needs == "owner" or re.search(r"human|owner", reason, re.I):
            on_human += 1
        blocked_list.append({"id": it.id, "owner": it.owner, "state": it.state,
                             "reason": reason, "on": it.blocked_on,
                             "needs": it.needs, "row": it.row})

    # --- per seat ----------------------------------------------------------
    seats = {}
    for seat in VIEW_SEATS:
        mine = [i for i in world.items.values() if i.owner == seat]
        counts = {s: sum(1 for i in mine if i.state == s) for s in model.STATES}
        offered = priority.rank(world, seat, target, ctx)
        said = world.seats.get(seat) or {}
        doing = sorted(i.id for i in mine if i.state == "doing")
        seats[seat] = {
            "counts": counts,
            "open": sum(1 for i in mine if i.open),
            "blocked": sum(1 for i in mine if i.blocked and i.open),
            "offered": len(offered),
            "next": offered[0].id if offered else None,
            # 🔑 Two DIFFERENT readings of "what is this seat doing", kept apart on
            # purpose. `doing` is what the ledger's item states say. `says` is what
            # the seat last announced about itself. When they disagree, that IS the
            # finding — a seat announcing busy with nothing started is the failure
            # mode the old board could not see.
            "doing": doing,
            "says": {"state": said.get("state"), "reason": said.get("reason"),
                     "item": said.get("item")},
        }

    tot = sum(c["total"] for r in rows for c in r["cells"].values())
    don = sum(c["done"] for r in rows for c in r["cells"].values())
    return {
        "schema": "rimflow-board/1",
        "as_of": as_of(events),
        "events": len(events),
        "items": len(world.items),
        "game": world.game,
        "bridge_holder": world.bridge_holder,
        "target": target,
        "rows": rows,
        "blockers": {"on_human": on_human,
                     "classes": [{"label": k, "count": v} for k, v in
                                 sorted(classes.items(), key=lambda kv: (-kv[1], kv[0]))]},
        "velocity": _velocity(close_days, tot - don),
        "seats": seats,
        "blocked": blocked_list,
        "findings": world.findings,
        # Refusals already IN the append-only file. Surfaced, never swallowed: an
        # event that replay rejected is a fact about the ledger, not a crash.
        "errors": [{"index": i, "event": v, "message": m} for i, v, m in world.errors],
    }


# ---------------------------------------------------------------------------
# WRITING
# ---------------------------------------------------------------------------
def _write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path + ".tmp", "w", encoding="utf-8") as fh:
        fh.write(text)
    os.replace(path + ".tmp", path)


def _queue_path(seat, root=None):
    # Resolved at CALL time. A `root=QUEUE` default binds at import and quietly
    # ignores any redirection — which is how a selftest ends up writing the real
    # queue files it was meant to leave alone.
    return os.path.join(root or QUEUE, "%s.md" % FILENAME.get(seat, seat))


_HEAD_RE = re.compile(r"^##\s+(\S+)")


def queue_item_ids(path):
    """-> set of IDs filed in a hand-written queue file.

    Only headings whose first token is a legal item ID count. `## 🔴 OWNER RULINGS,
    2026-08-19` is a prose section, not an item, and counting it would demand the
    ledger hold prose.
    """
    out = set()
    try:
        with open(path, encoding="utf-8") as fh:
            lines = fh.read().splitlines()
    except OSError:
        return out
    heads = [i for i, l in enumerate(lines) if _HEAD_RE.match(l)] + [len(lines)]
    for a, b in zip(heads, heads[1:]):
        m = _HEAD_RE.match(lines[a])
        # ⛔ `model.is_item_heading`, NOT a local rule. This function and the importer
        # MUST count the same things or the overwrite guard cries wolf — it did, on
        # 2026-08-20, counting `## A (DECIDE…)`, `## FYI…`, `## The…` as items and
        # refusing a migration that was actually complete.
        if m and model.is_item_heading(m.group(1), lines[a + 1:b]):
            out.add(m.group(1))
    return out


def queue_census(root=None):
    """-> (total_ids, {file: n}). Every file in queue/, archives included.

    Archives count. An item that closed and moved to `CHECK_CLOSED.md` is still a
    row the ledger has to be able to reproduce before anything is allowed to
    overwrite the originals.
    """
    root = root or QUEUE
    per, ids = {}, set()
    try:
        names = sorted(os.listdir(root))
    except OSError:
        return 0, {}
    for name in names:
        if not name.endswith(".md"):
            continue
        got = queue_item_ids(os.path.join(root, name))
        per[name] = len(got)
        ids |= got
    return len(ids), per


def render(events_path=None, out_dir=None, overwrite_queues=False, target="v1",
           ctx=None, quiet=False, queue_root=None, board_path=None):
    """Write board.json and the queue views. -> dict summary.

    🔴 The refusal below is the whole safety property of this module. Six files, 827
    KB, 142 items of hand-written prose, and a generator that would replace them with
    whatever the ledger currently holds — including nothing. So the ledger must first
    demonstrate that it can reproduce at least as many items as the queues contain,
    and the refusal prints BOTH counts, because a refusal without numbers cannot be
    acted on.
    """
    t0 = time.perf_counter()
    item_index(refresh=True)          # one listdir for the whole render; see above
    world, events = build(events_path)
    t_ledger = (time.perf_counter() - t0) * 1000.0
    out_dir = out_dir or PREVIEW
    board_path = board_path or BOARD
    queue_root = queue_root or QUEUE

    t = time.perf_counter()
    q_total, q_per = queue_census(queue_root)
    t_census = (time.perf_counter() - t) * 1000.0
    refused = None
    if overwrite_queues and len(world.items) < q_total:
        refused = (
            "REFUSED to overwrite queue/*.md: the ledger holds %d item(s) and the "
            "queues hold %d. Overwriting now would delete %d item(s) that exist only "
            "as hand-written prose, and the ledger is append-only — nothing here "
            "could put them back.\n"
            "    ledger : %d item(s)  (%s)\n"
            "    queues : %d item(s)  %s\n"
            "Run the importer first, then re-run with --overwrite-queues."
            % (len(world.items), q_total, q_total - len(world.items),
               len(world.items), events_path or model.EVENTS, q_total,
               ", ".join("%s=%d" % (k, v) for k, v in sorted(q_per.items()))))
        overwrite_queues = False

    target_dir = queue_root if overwrite_queues else out_dir
    t = time.perf_counter()
    written, diffs = [], []
    for seat in VIEW_SEATS:
        text = queue_view(world, seat, events, target, ctx)
        path = _queue_path(seat, target_dir)
        _write(path, text)
        written.append(path)
        if not overwrite_queues:
            real = _queue_path(seat, queue_root)
            have = queue_item_ids(real)
            mine = {i.id for i in world.items.values() if i.owner == seat}
            diffs.append({"seat": seat, "preview": path, "queue": real,
                          "in_ledger_only": sorted(mine - have),
                          "in_queue_only": sorted(have - mine),
                          "both": len(mine & have)})

    t_views = (time.perf_counter() - t) * 1000.0
    t = time.perf_counter()
    payload = board(world, events, target, ctx)
    _write(board_path, json.dumps(payload, indent=1, ensure_ascii=False) + "\n")
    t_board = (time.perf_counter() - t) * 1000.0
    ms = (time.perf_counter() - t0) * 1000.0

    summary_ = {"ms": ms,
                # 🔑 Attributed, because an unattributed total cannot be fixed by
                # anyone. `ledger` is model.read + model.replay and is not this
                # module's to speed up — see the note in bench().
                "stages": {"ledger": t_ledger, "census": t_census,
                           "views": t_views, "board": t_board}, "written": written, "board": board_path, "diffs": diffs,
                "refused": refused, "items": len(world.items), "events": len(events),
                "queue_items": q_total, "overwrote": overwrite_queues,
                "errors": len(world.errors)}
    if not quiet:
        _print_render(summary_)
    return summary_


def _print_render(s):
    if s["refused"]:
        print("🔴 " + s["refused"], file=sys.stderr)
    print("%s: %d event(s) -> %d item(s)%s"
          % (os.path.basename(s["board"]), s["events"], s["items"],
             ", %d replay refusal(s)" % s["errors"] if s["errors"] else ""))
    if s["overwrote"]:
        print("⚠️  OVERWROTE the real queue/*.md — %d file(s)" % len(s["written"]))
    for d in s["diffs"]:
        print("  %-7s preview %-4s | queue %-4s | shared %-4s%s"
              % (d["seat"], len(d["in_ledger_only"]) + d["both"],
                 len(d["in_queue_only"]) + d["both"], d["both"],
                 "   ⚠ %d only in queue" % len(d["in_queue_only"])
                 if d["in_queue_only"] else ""))
    over = s["ms"] - 100.0
    print("render: %.1f ms (target 100 ms%s)"
          % (s["ms"], "" if over <= 0 else " — OVER by %.1f ms" % over))


# ---------------------------------------------------------------------------
# REINDEX
# ---------------------------------------------------------------------------
def _tree(root):
    out = {}
    for dirpath, _dirs, files in os.walk(root):
        for f in files:
            if f.endswith(".tmp"):
                continue
            p = os.path.join(dirpath, f)
            out[os.path.relpath(p, root)] = open(p, "rb").read()
    return out


def reindex(verify=False, events_path=None, target="v1", ctx=None):
    """Rebuild every derived artifact from `events.jsonl` alone.

    ⭐ `--verify` is the real test of the claim that the ledger IS the truth. It
    renders into a scratch tree and compares BYTE FOR BYTE with what is on disk.
    Because nothing rendered contains a wall clock, a difference has exactly two
    possible causes — a bug in this file, or a hand edit to a generated artifact —
    and both are things somebody needs to see.

    ⚠️ The scratch tree is under the repo, never `/tmp`. They are different
    filesystems here (9p vs tmpfs) and a test that runs on the wrong one has already
    reported green while the real disk was losing 83% of its writes.
    """
    if not verify:
        s = render(events_path=events_path, target=target, ctx=ctx)
        return 0 if not s["refused"] else 1

    scratch = os.path.join(DERIVED, ".verify")
    shutil.rmtree(scratch, ignore_errors=True)
    os.makedirs(scratch, exist_ok=True)
    try:
        s = render(events_path=events_path,
                   out_dir=os.path.join(scratch, "queue_preview"),
                   board_path=os.path.join(scratch, "board.json"),
                   target=target, ctx=ctx, quiet=True)
        fresh = _tree(scratch)
        same, differ, missing = [], [], []
        for rel, blob in sorted(fresh.items()):
            live = os.path.join(DERIVED, rel)
            try:
                with open(live, "rb") as fh:
                    cur = fh.read()
            except OSError:
                missing.append(rel)
                continue
            (same if cur == blob else differ).append(rel)
        print("reindex --verify: %d identical, %d differ, %d missing on disk"
              % (len(same), len(differ), len(missing)))
        for rel in differ:
            print("  DIFFERS  %s  — a bug in render.py, or somebody hand-edited a "
                  "generated file" % rel)
        for rel in missing:
            print("  MISSING  %s  — never rendered; run `render` first" % rel)
        print("  ⚠ queue/*.md is NOT compared: it is still hand-written and is not "
              "generated until --overwrite-queues is allowed.")
        print("render: %.1f ms (target 100 ms%s)"
              % (s["ms"], "" if s["ms"] <= 100 else
                 " — OVER by %.1f ms" % (s["ms"] - 100)))
        return 0 if not (differ or missing) else 1
    finally:
        shutil.rmtree(scratch, ignore_errors=True)


# ---------------------------------------------------------------------------
# BENCH — the 100 ms target, measured rather than asserted
# ---------------------------------------------------------------------------
def bench(n=2000, with_prose=True):
    """Render a synthetic ledger of `n` events and report the time, stage by stage.

    The live ledger is young; a target measured against 3 events proves nothing. The
    plan measured ~1,100 events in 8 days, so 2,000 is roughly a fortnight of work.

    🔑 It writes real `items/<ID>.md` files and points `model.ITEMS` at them, because
    the honest cost of a render on this filesystem is dominated by how many times it
    touches `items/`, and a bench with no prose on disk would flatter every number.
    ⚠️ Everything is under the repo, on the filesystem this actually runs on — the
    same trap `selftest_concurrency.py` fell into when it defaulted to /tmp.
    """
    d = os.path.join(DERIVED, ".bench")
    shutil.rmtree(d, ignore_errors=True)
    items_dir = os.path.join(d, "items")
    os.makedirs(items_dir, exist_ok=True)
    path = os.path.join(d, "events.jsonl")
    real_items = model.ITEMS
    try:
        with open(path, "w", encoding="utf-8") as fh:
            for i in range(n // 4):
                iid = "SYNTHETIC_BENCH_ITEM_%d" % i
                seat = COLS[i % 3]
                if with_prose:
                    with open(os.path.join(items_dir, "%s.md" % iid), "w",
                              encoding="utf-8") as ih:
                        ih.write("## spec\nbench item %d, one line of spec.\n\n"
                                 "## verify\nrun it\n\n## criteria\nit ran\n" % i)
                for ev in (
                    {"seat": "DECIDE", "event": "file", "id": iid,
                     "title": "bench %d" % i, "kind": "task", "for": seat,
                     "row": str(i % 20)},
                    {"seat": seat, "event": "claim", "id": iid},
                    {"seat": seat, "event": "note", "id": iid, "text": "bench"},
                    {"seat": seat, "event": "close", "id": iid, "sha": "abc1234"},
                ):
                    ev["ts"] = "2026-08-%02dT00:00:%02dZ" % (1 + i % 20, i % 60)
                    fh.write(json.dumps(ev, separators=(",", ":")) + "\n")
        model.ITEMS = items_dir
        best, st = None, None
        for _ in range(3):
            s = render(events_path=path, out_dir=os.path.join(d, "queue_preview"),
                       board_path=os.path.join(d, "board.json"), quiet=True)
            if best is None or s["ms"] < best:
                best, st = s["ms"], s["stages"]
        over = best - 100.0
        print("bench: %d events, %d items, prose on disk=%s"
              % (n, s["items"], with_prose))
        print("  total   %7.1f ms  (best of 3; target 100 ms%s)"
              % (best, "" if over <= 0 else " — OVER by %.1f ms" % over))
        for k in ("ledger", "census", "views", "board"):
            print("    %-8s %7.1f ms%s" % (k, st[k],
                  "  ⚠️ model.read + model.replay; replay opens items/<ID>.md once "
                  "per claim/start event, and a single open costs ~0.8 ms on this "
                  "9p mount" if k == "ledger" else ""))
        print("  render's own work (census+views+board): %.1f ms"
              % (st["census"] + st["views"] + st["board"]))
        return 0 if over <= 0 else 1
    finally:
        model.ITEMS = real_items
        shutil.rmtree(d, ignore_errors=True)


# ---------------------------------------------------------------------------
def main(argv=None):
    argv = list(sys.argv[1:] if argv is None else argv)
    cmd = argv[0] if argv and not argv[0].startswith("-") else "render"
    if argv and argv[0] == cmd and not argv[0].startswith("-"):
        argv = argv[1:]
    if cmd == "reindex":
        return reindex(verify="--verify" in argv)
    if cmd == "bench":
        n = 2000
        if "--events" in argv:
            n = int(argv[argv.index("--events") + 1])
        return bench(n, with_prose="--no-prose" not in argv)
    if cmd != "render":
        print("usage: render.py [render [--overwrite-queues]] | reindex [--verify] "
              "| bench [--events N]", file=sys.stderr)
        return 2
    s = render(overwrite_queues="--overwrite-queues" in argv)
    return 1 if s["refused"] else 0


if __name__ == "__main__":
    sys.exit(main())
