"""Generate absorbed defs for guy762.mm.kotorcore's materials+apparel subset
(workshop folder 3254370945) into Jawa_Armoury -- the last remaining piece
of WEAPONS_ABSORPTION_WAVE_1, and the reason JawaArmoury.csproj (this mod's
first C#) exists: kotorweapons absorbs cleanly only once kotorcore's own
abstract base ThingDefs and 11 load-bearing comp/worker classes are also
absorbed.

Scope: the WHOLE main 1.6/Defs/ tree (DamageDefs, HediffDefs, ProjectileDefs,
SoundDefs, ThingCategoryDefs, ThingDefs_Buildings/Consumables/Items/Resources/
WeaponsArmorsGadgets, TraderKindDefs, interfaceDefs, researchDefs, and the
loose root-level files). "droid-base" is NOT a subfolder of this tree at
all -- it lives entirely under 1.6/AdditionalMods/_DroidsBase, gated by
IfModActive="guy762.KotORDroids" in kotorcore's own LoadFolders.xml, so it is
excluded automatically by only ever walking 1.6/Defs/, not by filtering
anything out of it.

Rule-6 DLL coupling, measured this pass with a full-tree Class=/compClass=/
verbClass=/workerClass=/driverClass=/thingClass=/genStep= sweep (the prior
pass that named "7 load-bearing DLLs" only grepped 3 of 13 subfolders --
ThingDefs_WeaponsArmorsGadgets/Resources/Items -- and said so explicitly:
"remaining 29 ... not confirmed unused". This sweep covers the full tree):

  PORTED this pass, into JawaArmoury.csproj, namespace-identical to the
  source DLL so Class=/compClass=/etc. need ZERO rewriting:
    CompExtraSounds, CrystalFormations, KoltoTank, MentalBreakBlocker,
    SecondaryMineableYield, SelfHediffVerb, Spinning_Projectile (the
    original 7) -- plus guy762_Ionization, MinePocket, InstantHealingDrug,
    JumppackForMeleeAI, found load-bearing by the full-tree sweep and
    ported for the same reason: each gates a large, squarely
    materials/apparel/consumables slice (guy762_Ionization alone backs
    all four DamageDefs files: every ranged/melee/grenade weapon's damage
    resolution) that a full absorption pass cannot leave stubbed.

  BLOCKED this pass (excluded, logged to the manifest, not guessed at):
    AthenaPort.*, taranchuk_homingprojectiles.* -- both use
    IgnoresAccessChecksToAttribute in the decompiled source (a private/
    internal Assembly-CSharp member access hack), which this generator's
    port discipline will not blind-replicate without a live behavior
    check it cannot perform offline. Gates 2 files (Bullets_Special.xml,
    Bullets_HomingProjectiles.xml).
    SWCP.Core.*, SWCP.Currencies.*, SWCP.RimframeGrineerDoors.* -- a
    faction/vehicle/economy sub-framework (tax collector incidents, VATS
    targeting, currency-replacement trade generators, a custom door), not
    materials/apparel by function even though its Defs live in this tree;
    WEAPONS_ABSORPTION_WAVE_1's own causal chain names a successor item
    (FORCE_SYSTEM_OWNERSHIP_1) as the more likely home for faction-system
    absorption. Gates 13 files, mostly TraderKindDefs.
  Neither block is a guess: every excluded element is logged by defName,
  source file and matched namespace to Absorbed_KotorCore_BLOCKED_manifest.txt,
  regenerated by rerunning this script, same discipline as
  gen_kotorweapons_absorption.py's own blocked-class filter (its template).

Generator shape: identical to gen_kotorweapons_absorption.py (this script's
direct template) -- parse source XML directly, generic recursive serializer,
mirror the source's own subfolder layout under Defs/Absorbed_KotorCore/
<subfolder>/, verify+copy every texPath/iconPath/clipPath before trusting it,
defName-preserving, collision-check excluding this generator's own prior
output, no silent fixes. One addition: clipPath/SoundDef asset copying
(kotorcore has 23 SoundDefs files, none of the two prior generators needed
this) and Rule_File plain-text word-list copying (RulePackDefs_CloneTrooper.xml
uses it, same mechanism gen_sovsith_absorption.py already established --
Rule_File is a vanilla RimWorld class, not a coupling, needs no blocking).

Does not deploy: guy762.mm.kotorcore stays active in the live ModsConfig.xml
(rule 5); a defName-preserving copy loaded alongside it collides on every
defName. Retirement is gated on the item's own full-list-load check.
"""
import os
import shutil
import sys
import xml.etree.ElementTree as ET


def _find_repo_root(start):
    d = os.path.abspath(start)
    while True:
        if os.path.isdir(os.path.join(d, ".git")) or \
           os.path.isfile(os.path.join(d, "CLAUDE.md")):
            return d
        parent = os.path.dirname(d)
        if parent == d:
            raise RuntimeError("no repo root above %s" % start)
        d = parent


_REPO_ROOT = _find_repo_root(os.path.dirname(__file__))
ARMOURY_ROOT = os.path.join(_REPO_ROOT, "src", "Jawa", "Jawa_Armoury")
DEFS_ROOT = os.path.join(ARMOURY_ROOT, "Defs")
TEX_ROOT = os.path.join(ARMOURY_ROOT, "Textures")
SOUND_ROOT = os.path.join(ARMOURY_ROOT, "Sounds")
LANG_ROOT = os.path.join(ARMOURY_ROOT, "Languages", "English", "Strings")

WORKSHOP_FOLDER = "/mnt/c/Program Files (x86)/Steam/steamapps/workshop/content/294100/3254370945"
# Real About.xml packageId is "guy762.MM.KotORCore" (confirmed from source,
# not guessed) -- the item's own notes/ledger spelled it lowercase, same
# casing mismatch gen_sovsith_absorption.py found and corrected for Sov.Sith.
EXPECTED_PACKAGE_ID = "guy762.MM.KotORCore"
SRC_DEFS = os.path.join(WORKSHOP_FOLDER, "1.6", "Defs")
SRC_TEX = os.path.join(WORKSHOP_FOLDER, "Textures")
SRC_SOUND = os.path.join(WORKSHOP_FOLDER, "Sounds")
SRC_LANG = os.path.join(WORKSHOP_FOLDER, "Languages", "English", "Strings")

OUT_SUBDIR = "Absorbed_KotorCore"  # under DEFS_ROOT; this generator's own output tree
OUT_FILE_PREFIX = "Absorbed_KotorCore_"

# Namespaces confirmed (by full-tree Class=/compClass=/verbClass=/driverClass=/
# thingClass= sweep) to be guy762.mm.kotorcore's OWN classes that this pass
# does NOT port -- see module docstring for why each is deferred rather than
# guessed at. Genuinely external frameworks (EBSGFramework, ModularWeapons2,
# AthenaFramework, VanillaApparelExpanded, ArtificialBeings, BigAndSmall,
# SaveOurShip2, Vehicles, XmlExtensions, MechHumanlikes, ATReforged,
# lee.theforce.lightsaber's Lightsaber.*) are NOT in this list -- they stay
# active regardless, same treatment gen_kotorweapons_absorption.py already
# established, not this generator's concern.
BLOCKED_NAMESPACES = (
    "AthenaPort.",
    "taranchuk_homingprojectiles.",
    "SWCP.Core.",
    "SWCP.Currencies.",
    "SWCP.RimframeGrineerDoors.",
)


class Report(object):
    def __init__(self):
        self.notes, self.warns = [], []

    def note(self, msg):
        self.notes.append(msg)
        print("NOTE  " + msg)

    def warn(self, msg):
        self.warns.append(msg)
        print("WARN  " + msg)


R = Report()


def existing_defnames_in(defs_root, exclude_dir):
    """(tag, defName) -> source file, for every def already under defs_root
    EXCEPT this generator's own output tree (exclude_dir) -- a rerun must not
    treat its own last run as a foreign pack to collide against.

    Keyed by (tag, defName), not bare defName: RimWorld's defName uniqueness
    is per-DefType, not global -- a ThingDef and a HediffDef sharing a name
    (e.g. "SpiceHigh" as both the drug's ThingDef and its status-effect
    HediffDef, a normal authoring pattern) do NOT collide in the live game.
    The two prior generators in this item key on bare defName and were never
    exercised against a same-name-different-type pair; kotorcore's own
    source has three (deathstickHigh, RhydoniumHigh, SpiceHigh) that a bare-
    defName check would have wrongly dropped the HediffDef half of."""
    out = {}
    for dirpath, dirnames, files in os.walk(defs_root):
        if os.path.abspath(dirpath) == os.path.abspath(exclude_dir) or \
           os.path.abspath(dirpath).startswith(os.path.abspath(exclude_dir) + os.sep):
            dirnames[:] = []
            continue
        for fn in files:
            if not fn.endswith(".xml"):
                continue
            p = os.path.join(dirpath, fn)
            try:
                tree = ET.parse(p)
            except ET.ParseError:
                continue
            for el in tree.getroot():
                dn = el.find("defName")
                if dn is not None and dn.text:
                    out[(el.tag, dn.text.strip())] = os.path.relpath(p, defs_root)
    return out


# --------------------------------------------------------- serialization --
def _escape_text(s):
    return (s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))


def _escape_attr(s):
    return _escape_text(s).replace('"', "&quot;")


def serialize(el, indent=1):
    pad = "  " * indent
    if el.tag is ET.Comment:
        text = (el.text or "").strip("\n")
        return "%s<!--%s-->" % (pad, text)

    attrs = "".join(' %s="%s"' % (k, _escape_attr(v)) for k, v in el.attrib.items())
    children = list(el)
    text = (el.text or "").strip()

    if not children and not text:
        return "%s<%s%s />" % (pad, el.tag, attrs)

    if not children:
        return "%s<%s%s>%s</%s>" % (pad, el.tag, attrs, _escape_text(text), el.tag)

    lines = ["%s<%s%s>" % (pad, el.tag, attrs)]
    if text:
        lines.append("%s  %s" % (pad, _escape_text(text)))
    for c in children:
        lines.append(serialize(c, indent + 1))
    lines.append("%s</%s>" % (pad, el.tag))
    return "\n".join(lines)


def matched_blocked_namespace(el):
    """Return the first BLOCKED_NAMESPACES entry found anywhere in el's
    serialized form (any attribute value, any depth), or None."""
    blob = ET.tostring(el, encoding="unicode")
    for ns in BLOCKED_NAMESPACES:
        if ns in blob:
            return ns
    return None


def write_defs_file(rel_dir, filename, elements, src_relpath):
    if not elements:
        return
    out_dir = os.path.join(DEFS_ROOT, OUT_SUBDIR, rel_dir)
    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, filename)
    body = "\n\n".join(serialize(e) for e in elements)
    fh = (
        '<?xml version="1.0" encoding="utf-8" ?>\n'
        "<!-- Absorbed from guy762.mm.kotorcore (workshop %s, packageId %s),\n"
        "     source file 1.6/Defs/%s, WEAPONS_ABSORPTION_WAVE_1. GENERATED by\n"
        "     src/RimStarWars/Armoury/Source/gen_kotorcore_absorption.py.\n"
        "     defNames preserved verbatim. Class=/compClass=/verbClass=/\n"
        "     driverClass=/genStep= values referencing this pack's own C# are\n"
        "     UNCHANGED from source: JawaArmoury.dll defines the same\n"
        "     namespaces+class names (CompExtraSounds, CrystalFormations,\n"
        "     KoltoTank, MentalBreakBlocker, SecondaryMineableYield,\n"
        "     SelfHediffVerb, Spinning_Projectile, guy762_Ionization,\n"
        "     MinePocket, InstantHealingDrug, JumppackForMeleeAI), so no\n"
        "     rewrite was needed for those to resolve to the port instead of\n"
        "     the original DLL.\n"
        "     Source pack stays active in the live ModsConfig for now (rule 5);\n"
        "     do NOT deploy this file until it retires, or duplicate defNames\n"
        "     result. -->\n"
        "<Defs>\n\n" % (os.path.basename(WORKSHOP_FOLDER), EXPECTED_PACKAGE_ID, src_relpath)
    )
    fh += body + "\n\n</Defs>\n"
    with open(path, "w", encoding="utf-8") as f:
        f.write(fh)
    R.note("wrote %s (%d defs)" % (os.path.relpath(path, _REPO_ROOT), len(elements)))


# ----------------------------------------------------------- asset copy --
def _copy_one(rel_stem_with_ext, src_root, dst_root):
    src = os.path.join(src_root, rel_stem_with_ext.replace("/", os.sep))
    dst = os.path.join(dst_root, rel_stem_with_ext.replace("/", os.sep))
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    shutil.copyfile(src, dst)


def find_and_copy_texture(tex_path, seen, missing):
    if tex_path in seen or tex_path in missing:
        return
    copied_any = False
    for ext in (".png", ".jpg", ".jpeg"):
        if os.path.isfile(os.path.join(SRC_TEX, tex_path.replace("/", os.sep) + ext)):
            _copy_one(tex_path + ext, SRC_TEX, TEX_ROOT)
            copied_any = True
        for rot in ("_south", "_north", "_east", "_west"):
            if os.path.isfile(os.path.join(SRC_TEX, tex_path.replace("/", os.sep) + rot + ext)):
                _copy_one(tex_path + rot + ext, SRC_TEX, TEX_ROOT)
                copied_any = True
    # Graphic_StackCount / Graphic_Random / Graphic_Appearances multi-frame art:
    # texPath names a DIRECTORY of _a/_b/_c-suffixed frames, not one file --
    # first pass over this pack missed this and reported 43 false "missing"
    # textures (kolto, medpac, rocket_*, credits, raw_resources/* etc. are all
    # folders, confirmed by listing). Copy the whole directory's images.
    src_dir = os.path.join(SRC_TEX, tex_path.replace("/", os.sep))
    if os.path.isdir(src_dir):
        dst_dir = os.path.join(TEX_ROOT, tex_path.replace("/", os.sep))
        for fn in os.listdir(src_dir):
            if fn.lower().endswith((".png", ".jpg", ".jpeg")):
                os.makedirs(dst_dir, exist_ok=True)
                shutil.copyfile(os.path.join(src_dir, fn), os.path.join(dst_dir, fn))
                copied_any = True
    if copied_any:
        seen.add(tex_path)
        return
    missing.add(tex_path)
    R.warn("texPath/iconPath %r has no .png/.jpg/.jpeg (bare, rotation-suffixed, or as a frame "
           "directory) under %s -- reference kept in XML, art NOT copied" % (tex_path, SRC_TEX))


def find_and_copy_sound(clip_path, seen, missing):
    if clip_path in seen or clip_path in missing:
        return
    for ext in (".ogg", ".wav"):
        src = os.path.join(SRC_SOUND, clip_path.replace("/", os.sep) + ext)
        if os.path.isfile(src):
            dst = os.path.join(SOUND_ROOT, clip_path.replace("/", os.sep) + ext)
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            shutil.copyfile(src, dst)
            seen.add(clip_path)
            return
    # AudioGrain_Folder clipFolderPath references a directory of clips, not
    # one file -- handled separately in find_and_copy_sound_folder.
    if os.path.isdir(os.path.join(SRC_SOUND, clip_path.replace("/", os.sep))):
        return
    missing.add(clip_path)
    R.warn("clipPath %r has no .ogg/.wav under %s -- reference kept in XML, audio NOT copied"
           % (clip_path, SRC_SOUND))


def find_and_copy_sound_folder(folder_path, seen, missing):
    if folder_path in seen or folder_path in missing:
        return
    src = os.path.join(SRC_SOUND, folder_path.replace("/", os.sep))
    if not os.path.isdir(src):
        missing.add(folder_path)
        R.warn("clipFolderPath %r has no directory under %s -- reference kept in XML, audio NOT copied"
               % (folder_path, SRC_SOUND))
        return
    dst = os.path.join(SOUND_ROOT, folder_path.replace("/", os.sep))
    for fn in os.listdir(src):
        if fn.lower().endswith((".ogg", ".wav")):
            os.makedirs(dst, exist_ok=True)
            shutil.copyfile(os.path.join(src, fn), os.path.join(dst, fn))
    seen.add(folder_path)


def find_and_copy_word_list(rule_path, seen, missing):
    if rule_path in seen or rule_path in missing:
        return
    src = os.path.join(SRC_LANG, rule_path.replace("/", os.sep) + ".txt")
    if os.path.isfile(src):
        dst = os.path.join(LANG_ROOT, rule_path.replace("/", os.sep) + ".txt")
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        shutil.copyfile(src, dst)
        seen.add(rule_path)
        return
    missing.add(rule_path)
    R.warn("Rule_File path %r has no .txt under %s -- reference kept in XML, word list NOT copied"
           % (rule_path, SRC_LANG))


def collect_paths(el, tag, out):
    if el.tag == tag and el.text and el.text.strip():
        out.add(el.text.strip())
    for c in el:
        collect_paths(c, tag, out)


def collect_rule_file_paths(el, out):
    """<li Class="Rule_File"><path>...</path></li> entries anywhere in the tree."""
    if el.tag == "li" and el.attrib.get("Class") == "Rule_File":
        path_el = el.find("path")
        if path_el is not None and path_el.text and path_el.text.strip():
            out.add(path_el.text.strip())
    for c in el:
        collect_rule_file_paths(c, out)


def main():
    # ------------------------------------------------------- guard rails --
    about = os.path.join(WORKSHOP_FOLDER, "About", "About.xml")
    if not os.path.isfile(about):
        R.warn("About.xml not found at %s -- workshop folder id may be wrong, ABORTING" % about)
        sys.exit(1)
    about_text = open(about, "r", encoding="utf-8-sig").read()
    if EXPECTED_PACKAGE_ID not in about_text:
        R.warn("About.xml at %s does not contain expected packageId %r -- ABORTING, do not guess the folder"
               % (about, EXPECTED_PACKAGE_ID))
        sys.exit(1)
    R.note("confirmed workshop folder %s is packageId %s" % (WORKSHOP_FOLDER, EXPECTED_PACKAGE_ID))

    own_out_dir = os.path.join(DEFS_ROOT, OUT_SUBDIR)
    existing = existing_defnames_in(DEFS_ROOT, own_out_dir)
    R.note("%d defNames already present in Jawa_Armoury/Defs outside %s -- collision-checking against these"
           % (len(existing), OUT_SUBDIR))

    src_files = []
    for dirpath, _, files in os.walk(SRC_DEFS):
        for fn in sorted(files):
            if fn.endswith(".xml"):
                src_files.append(os.path.join(dirpath, fn))
    src_files.sort()
    R.note("%d source XML files under %s" % (len(src_files), SRC_DEFS))

    buckets = {}  # (rel_dir, filename) -> list[Element]
    all_new_defnames = {}  # defName -> source file
    tex_paths, sound_paths, sound_folder_paths, rule_paths = set(), set(), set(), set()
    n_source_defs = 0
    n_dropped = 0       # collision drops
    n_blocked = 0        # excluded: references a not-yet-ported kotorcore comp/worker class
    blocked_manifest = []

    for src_path in src_files:
        rel = os.path.relpath(src_path, SRC_DEFS)
        rel_dir = os.path.dirname(rel)
        fn = os.path.basename(rel)
        out_filename = OUT_FILE_PREFIX + fn

        parser = ET.XMLParser(target=ET.TreeBuilder(insert_comments=True))
        tree = ET.parse(src_path, parser=parser)
        root = tree.getroot()

        for el in root:
            if el.tag is ET.Comment:
                continue
            n_source_defs += 1

            dn_el = el.find("defName")
            dn = dn_el.text.strip() if dn_el is not None and dn_el.text else None

            blocked_ns = matched_blocked_namespace(el)
            if blocked_ns:
                n_blocked += 1
                blocked_manifest.append((dn or "(no defName)", rel, blocked_ns))
                continue

            if dn:
                key = (el.tag, dn)
                if key in existing:
                    R.warn("defName %r <%s> (from %s) COLLIDES with already-absorbed %s -- SKIPPED" % (dn, el.tag, rel, existing[key]))
                    n_dropped += 1
                    continue
                if key in all_new_defnames:
                    R.warn("defName %r <%s> (from %s) COLLIDES within this pack's own output (also in %s) -- SKIPPED"
                           % (dn, el.tag, rel, all_new_defnames[key]))
                    n_dropped += 1
                    continue
                all_new_defnames[key] = rel

            collect_paths(el, "texPath", tex_paths)
            collect_paths(el, "iconPath", tex_paths)
            collect_paths(el, "uiIconPath", tex_paths)
            collect_paths(el, "clipPath", sound_paths)
            collect_paths(el, "clipFolderPath", sound_folder_paths)
            collect_rule_file_paths(el, rule_paths)

            buckets.setdefault((rel_dir, out_filename), []).append(el)

    # ---------------------------------------------------------- assets ---
    tex_seen, tex_missing = set(), set()
    for t in sorted(tex_paths):
        find_and_copy_texture(t, tex_seen, tex_missing)
    sound_seen, sound_missing = set(), set()
    for s in sorted(sound_paths):
        find_and_copy_sound(s, sound_seen, sound_missing)
    sound_folder_seen, sound_folder_missing = set(), set()
    for s in sorted(sound_folder_paths):
        find_and_copy_sound_folder(s, sound_folder_seen, sound_folder_missing)
    rule_seen, rule_missing = set(), set()
    for r in sorted(rule_paths):
        find_and_copy_word_list(r, rule_seen, rule_missing)

    # ------------------------------------------------------------- write --
    for (rel_dir, filename), elements in sorted(buckets.items()):
        src_relpath = os.path.join(rel_dir, filename[len(OUT_FILE_PREFIX):]) if rel_dir else filename[len(OUT_FILE_PREFIX):]
        write_defs_file(rel_dir, filename, elements, src_relpath)

    if blocked_manifest:
        manifest_path = os.path.join(own_out_dir, OUT_FILE_PREFIX + "BLOCKED_manifest.txt")
        os.makedirs(own_out_dir, exist_ok=True)
        with open(manifest_path, "w", encoding="utf-8") as f:
            f.write(
                "guy762.mm.kotorcore elements EXCLUDED from absorption -- each references a\n"
                "class confirmed to be kotorcore's own (AthenaPort.*, taranchuk_homingprojectiles.*)\n"
                "or a faction/vehicle/economy sub-framework judged out of this item's materials+\n"
                "apparel scope (SWCP.Core.*, SWCP.Currencies.*, SWCP.RimframeGrineerDoors.*). See\n"
                "gen_kotorcore_absorption.py's module docstring for why each is deferred rather\n"
                "than ported or guessed at. Not written to any Defs/ file; regenerate this list\n"
                "by rerunning gen_kotorcore_absorption.py.\n\n"
                "defName\tsource file\tmatched class\n"
            )
            for dn, rel, ns in blocked_manifest:
                f.write("%s\t%s\t%s\n" % (dn, rel, ns))
        R.note("wrote %s (%d blocked elements)" % (os.path.relpath(manifest_path, _REPO_ROOT), len(blocked_manifest)))

    # ------------------------------------------------------------ report --
    print("\n=== summary ===")
    n_written = n_source_defs - n_dropped - n_blocked
    n_abstract = n_written - len(all_new_defnames)
    print("source elements seen: %d; written to output: %d; blocked (unported kotorcore class or out-of-scope sub-framework): %d; dropped (collision): %d"
          % (n_source_defs, n_written, n_blocked, n_dropped))
    print("of those written, %d carry a defName, %d are Abstract/parent-only defs with none "
          "(kept for ParentName resolution, not a drop)" % (len(all_new_defnames), n_abstract))
    print("textures/icons: %d found+copied, %d MISSING" % (len(tex_seen), len(tex_missing)))
    print("sounds (clipPath): %d found+copied, %d MISSING" % (len(sound_seen), len(sound_missing)))
    print("sounds (clipFolderPath): %d found+copied, %d MISSING" % (len(sound_folder_seen), len(sound_folder_missing)))
    print("word lists (Rule_File): %d found+copied, %d MISSING" % (len(rule_seen), len(rule_missing)))
    print("notes: %d, warnings: %d" % (len(R.notes), len(R.warns)))
    if tex_missing:
        print("missing textures: %s" % sorted(tex_missing))
    if sound_missing:
        print("missing sounds: %s" % sorted(sound_missing))
    if sound_folder_missing:
        print("missing sound folders: %s" % sorted(sound_folder_missing))
    if rule_missing:
        print("missing word lists: %s" % sorted(rule_missing))


if __name__ == "__main__":
    main()
