#!/usr/bin/env python3
"""
gl_emit.py

A small typed builder that WRITES Geological Landforms landform-recipe XML
(NodeCanvas / GraphEditor.Landform) from Python, byte-shape compatible with
the files shipped in the Landforms-v1 workshop item.

Design: rather than hand-writing per-node-type XML templates, this module
LEARNS them by parsing the one ground-truth file it must reproduce
(LandformDesertPlateau.xml) once, at first use: which XML tag each scalar
field uses (string/int/long/double/float/boolean/Topology/...), which fields
are FloatRange or Variable/Object indirections, and the extra sub-element
block a dynamic Port carries. The VALUES written to any given file come from
whoever calls the builder; the per-type SHAPE comes from that parse.

stdlib only.

Builder API:
    g = Graph()
    node = g.node(type_, name, pos=None, **fields)
    port = g.port(node, name, direction, dynamic=False, **overrides)
    g.connect(port_a, port_b)
    node = g.manifest(id_, display_name, is_custom=True, ...)
    node = g.tile_req(**ranges)
    g.write(path)

--selftest   Rebuild LandformDesertPlateau.xml entirely via builder calls
             (the calls are generated by parsing the source once; the
             emitted bytes come from the builder, not a copy), then compare
             against the original using gl_schema_census's own parser
             (imported, not duplicated). Prints `SELFTEST PASS N/N`.

--variant --frequency F --id ID --out PATH
             DesertPlateau via the builder with the primary Perlin's
             (source Node ID=5) Frequency replaced by F, manifest Id/
             DisplayName set to ID, IsCustom true, Commonness 1, hilliness
             0-6, rainfall 0-10000, temperature -100..100.
"""
from __future__ import annotations

import argparse
import importlib.util
import os
import random
import sys
import tempfile
import time
import xml.etree.ElementTree as ET
from collections import Counter, defaultdict

SOURCE_DESERTPLATEAU = (
    "/mnt/c/Program Files (x86)/Steam/steamapps/workshop/content/294100/"
    "2773943594/1.6/Landforms-v1/LandformDesertPlateau.xml"
)

GL_SCHEMA_CENSUS_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "gl_schema_census.py")

DEFAULT_KNOB_TYPE = (
    "NodeEditorFramework.ValueConnectionKnob, TerrainGraph, Version=1.1.5.0, "
    "Culture=neutral, PublicKeyToken=null"
)
XML_SCHEMA_XMLNS = ' xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"'
XSI_NIL_ATTR = "{http://www.w3.org/2001/XMLSchema-instance}nil"


def _load_gl_schema_census():
    """Import gl_schema_census.py's parser (FileGraph, collect_scalar_fields)
    without executing its module-level main() (guarded by __main__)."""
    spec = importlib.util.spec_from_file_location("gl_schema_census", GL_SCHEMA_CENSUS_PATH)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _esc(s):
    return (
        str(s)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def _fmt_scalar(value):
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        return value
    if value is None:
        return ""
    if isinstance(value, float):
        if value == int(value):
            return str(int(value))
        return repr(value)
    return str(value)


# =========================== source introspection ===========================
# Parses the shipped LandformDesertPlateau.xml once, both to LEARN per-type
# field-tag/port templates and to get the exact node/port/connection graph
# that --selftest replays through the builder.

def _read_objects(root):
    """refID(str) -> {"elem_kind": "double"|"string", "values": [str|None, ...]}"""
    out = {}
    objects_el = root.find("Objects")
    if objects_el is None:
        return out
    for obj_el in objects_el.findall("Object"):
        refid = obj_el.get("refID")
        children = list(obj_el)
        if not children:
            continue
        arr_el = children[0]
        items = list(arr_el)
        elem_kind = items[0].tag if items else "double"
        values = []
        for item in items:
            if item.get(XSI_NIL_ATTR) == "true":
                values.append(None)
            else:
                values.append(item.text if item.text is not None else "")
        out[refid] = {"elem_kind": elem_kind, "values": values}
    return out


def _parse_source(path):
    """Return (nodes, connections).

    nodes: list of dicts, one per <Node>, in document order:
        old_id, name, type, pos,
        ordered: [("scalar",tag,name,text) | ("floatrange",name,min,max)
                  | ("variable",name,obj-or-None)]  (document order, excludes
                  Port and the trailing RandSeed)
        ports: [{"old_id","name","dynamic","type_attr","sub"}]  (sub: dict of
                  subelement-name -> (tag, text), populated for dynamic ports)
    connections: [(port1_old_id, port2_old_id), ...]
    """
    tree = ET.parse(path)
    root = tree.getroot()
    objects_by_refid = _read_objects(root)

    nodes = []
    nodes_el = root.find("Nodes")
    for node_el in nodes_el.findall("Node") if nodes_el is not None else []:
        ninfo = {
            "old_id": node_el.get("ID"),
            "name": node_el.get("name"),
            "type": node_el.get("type"),
            "pos": node_el.get("pos"),
            "ordered": [],
            "ports": [],
        }
        for child in list(node_el):
            tag = child.tag
            name = child.get("name")
            if tag == "Port":
                pdyn = child.get("dynamic")
                pinfo = {
                    "old_id": child.get("ID"),
                    "name": name,
                    "dynamic": pdyn,
                    "type_attr": child.get("type"),
                    "sub": {},
                }
                if pdyn == "True":
                    for sub in list(child):
                        key = sub.get("name") or sub.tag
                        pinfo["sub"][key] = (sub.tag, sub.text)
                ninfo["ports"].append(pinfo)
                continue
            if tag == "int" and name == "RandSeed":
                continue
            if tag == "Variable":
                refid = child.get("refID")
                ninfo["ordered"].append(("variable", name, objects_by_refid.get(refid)))
                continue
            if tag == "FloatRange":
                mn = child.findtext("min")
                mx = child.findtext("max")
                ninfo["ordered"].append(("floatrange", name, mn, mx))
                continue
            text = child.text if child.text is not None else ""
            ninfo["ordered"].append(("scalar", tag, name, text))
        nodes.append(ninfo)

    connections = []
    conns_el = root.find("Connections")
    for c in conns_el.findall("Connection") if conns_el is not None else []:
        connections.append((c.get("port1ID"), c.get("port2ID")))

    return nodes, connections


_TEMPLATE_CACHE = {}


def _templates(path=SOURCE_DESERTPLATEAU):
    if path in _TEMPLATE_CACHE:
        return _TEMPLATE_CACHE[path]
    nodes, conns = _parse_source(path)
    field_tag = {}          # (type,name) -> tag
    variable_elem_kind = {}  # (type,name) -> "double"|"string"
    port_dynamic = {}       # (type,name) -> dict of style_id/conn_count/side/side_position/side_offset/knob_type
    for n in nodes:
        for entry in n["ordered"]:
            if entry[0] == "scalar":
                _, tag, name, _text = entry
                field_tag[(n["type"], name)] = tag
            elif entry[0] == "variable":
                _, name, obj = entry
                if obj is not None:
                    variable_elem_kind[(n["type"], name)] = obj["elem_kind"]
        for p in n["ports"]:
            if p["dynamic"] == "True":
                sub = p["sub"]
                port_dynamic[(n["type"], p["name"])] = {
                    "style_id": sub.get("styleID", ("string", "GridFunc"))[1],
                    "conn_count": sub.get("maxConnectionCount", ("ConnectionCount", "Single"))[1],
                    "side": sub.get("side", ("NodeSide", "Left"))[1],
                    "side_position": sub.get("sidePosition", ("float", "0"))[1],
                    "side_offset": sub.get("sideOffset", ("float", "0"))[1],
                    "knob_type": p["type_attr"] or DEFAULT_KNOB_TYPE,
                }
    result = {
        "nodes": nodes,
        "connections": conns,
        "field_tag": field_tag,
        "variable_elem_kind": variable_elem_kind,
        "port_dynamic": port_dynamic,
    }
    _TEMPLATE_CACHE[path] = result
    return result


# ================================== builder ==================================

class _Node:
    def __init__(self, id_, type_, name, pos):
        self.id = id_
        self.type = type_
        self.name = name
        self.pos = pos
        self.ports = []
        self.fields = []  # ("scalar",tag,name,value) | ("floatrange",name,(min,max)) | ("variable",name,elem_kind,values,refid)


class _Port:
    def __init__(self, id_, node, name, dynamic, direction, dyn=None):
        self.id = id_
        self.node = node
        self.name = name
        self.dynamic = dynamic
        self.direction = direction
        self.dyn = dyn or {}


class Graph:
    def __init__(self, template_source=SOURCE_DESERTPLATEAU):
        self._tpl = _templates(template_source)
        self._nodes = []
        self._node_ctr = 0
        self._port_ctr = 0
        self._obj_ctr = 0
        self._connections = []

    # ---- node/port/connection construction ----

    def node(self, type_, name, pos=None, **fields):
        nid = self._node_ctr
        self._node_ctr += 1
        n = _Node(nid, type_, name, pos if pos is not None else "0,0")
        self._nodes.append(n)
        for k, v in fields.items():
            if isinstance(v, list):
                elem_kind = self._tpl["variable_elem_kind"].get((type_, k))
                if elem_kind is None:
                    elem_kind = "string" if any(e is None or isinstance(e, str) for e in v) else "double"
                refid = self._obj_ctr
                self._obj_ctr += 1
                n.fields.append(("variable", k, elem_kind, list(v), refid))
            else:
                tag = self._tpl["field_tag"].get((type_, k))
                if tag is None:
                    if isinstance(v, bool):
                        tag = "boolean"
                    elif isinstance(v, int):
                        tag = "int"
                    elif isinstance(v, float):
                        tag = "double"
                    else:
                        tag = "string"
                n.fields.append(("scalar", tag, k, v))
        return n

    def port(self, node, name, direction, dynamic=False, **overrides):
        pid = self._port_ctr
        self._port_ctr += 1
        dyn = {}
        if dynamic:
            tpl = self._tpl["port_dynamic"].get((node.type, name), {})
            dyn = {
                "style_id": overrides.get("style_id", tpl.get("style_id", "GridFunc")),
                "conn_count": overrides.get("conn_count", tpl.get("conn_count", "Single")),
                "side": overrides.get("side", tpl.get("side", "Left")),
                "side_position": overrides.get("side_position", tpl.get("side_position", "0")),
                "side_offset": overrides.get("side_offset", tpl.get("side_offset", "0")),
                "knob_type": overrides.get("knob_type", tpl.get("knob_type", DEFAULT_KNOB_TYPE)),
            }
        p = _Port(pid, node, name, dynamic, direction, dyn)
        node.ports.append(p)
        return p

    def connect(self, port_a, port_b):
        self._connections.append((port_a, port_b))

    # ---- convenience nodes ----

    def manifest(self, id_, display_name, is_custom=True, revision_version=1,
                 time_created=None, is_experimental=False, is_internal=False,
                 is_edited=False, display_name_has_direction=False, pos=None):
        if time_created is None:
            time_created = int(time.time() * 1000)
        return self.node(
            "landformManifest", "Custom Landform", pos=pos,
            Id=id_,
            IsCustom=is_custom,
            IsExperimental=is_experimental,
            IsInternal=is_internal,
            RevisionVersion=revision_version,
            TimeCreated=time_created,
            IsEdited=is_edited,
            DisplayName=display_name,
            DisplayNameHasDirection=display_name_has_direction,
        )

    def tile_req(self, topology="Inland", commonness=0.03351957, cave_chance=0.0,
                 hilliness=(1, 2.50282478), road=(0, 1), river=(0, 1),
                 elevation=(0, 5000), avg_temperature=(2.259887, 100),
                 rainfall=(0, 508.474579), swampiness=(0, 1),
                 biome_transitions=(0, 6), topology_value=(-1, 1),
                 depth_in_cave_system=(0, 10), map_size=(50, 1000),
                 allow_settlements=True, allow_sites=True, pos=None):
        n = self.node(
            "worldTileReq", "World Tile Requirements", pos=pos,
            Topology=topology, Commonness=commonness, CaveChance=cave_chance,
        )
        for name, rng in (
            ("HillinessRequirement", hilliness),
            ("RoadRequirement", road),
            ("RiverRequirement", river),
            ("ElevationRequirement", elevation),
            ("AvgTemperatureRequirement", avg_temperature),
            ("RainfallRequirement", rainfall),
            ("SwampinessRequirement", swampiness),
            ("BiomeTransitionsRequirement", biome_transitions),
            ("TopologyValueRequirement", topology_value),
            ("DepthInCaveSystemRequirement", depth_in_cave_system),
            ("MapSizeRequirement", map_size),
        ):
            n.fields.append(("floatrange", name, rng))
        n.fields.append(("scalar", "boolean", "AllowSettlements", allow_settlements))
        n.fields.append(("scalar", "boolean", "AllowSites", allow_sites))
        return n

    # ---- serialization ----

    def write(self, path):
        out = []
        out.append('<?xml version="1.0" encoding="utf-8"?>')
        out.append('<NodeCanvas type="GeologicalLandforms.GraphEditor.Landform">')
        out.append('\t<EditorStates />')
        out.append('\t<Groups />')
        out.append('\t<Nodes>')
        objects_out = []
        for n in self._nodes:
            out.append(f'\t\t<Node name="{_esc(n.name)}" ID="{n.id}" type="{n.type}" pos="{n.pos}">')
            for p in n.ports:
                if not p.dynamic:
                    out.append(f'\t\t\t<Port ID="{p.id}" name="{_esc(p.name)}" dynamic="False" />')
                else:
                    out.append(
                        f'\t\t\t<Port ID="{p.id}" name="{_esc(p.name)}" dynamic="True" '
                        f'type="{_esc(p.dyn["knob_type"])}">'
                    )
                    out.append(f'\t\t\t\t<string name="styleID">{_esc(p.dyn["style_id"])}</string>')
                    out.append(f'\t\t\t\t<Direction name="direction">{_esc(p.direction or "In")}</Direction>')
                    out.append(f'\t\t\t\t<ConnectionCount name="maxConnectionCount">{_esc(p.dyn["conn_count"])}</ConnectionCount>')
                    out.append(f'\t\t\t\t<NodeSide name="side">{_esc(p.dyn["side"])}</NodeSide>')
                    out.append(f'\t\t\t\t<float name="sidePosition">{_fmt_scalar(p.dyn["side_position"])}</float>')
                    out.append(f'\t\t\t\t<float name="sideOffset">{_fmt_scalar(p.dyn["side_offset"])}</float>')
                    out.append('\t\t\t</Port>')
            for f in n.fields:
                kind = f[0]
                if kind == "scalar":
                    _, tag, name, value = f
                    text = _fmt_scalar(value)
                    if text == "":
                        out.append(f'\t\t\t<{tag} name="{_esc(name)}" />')
                    else:
                        out.append(f'\t\t\t<{tag} name="{_esc(name)}">{_esc(text)}</{tag}>')
                elif kind == "floatrange":
                    _, name, (mn, mx) = f
                    out.append(f'\t\t\t<FloatRange{XML_SCHEMA_XMLNS} name="{_esc(name)}">')
                    out.append(f'\t\t\t\t<min>{_esc(_fmt_scalar(mn))}</min>')
                    out.append(f'\t\t\t\t<max>{_esc(_fmt_scalar(mx))}</max>')
                    out.append('\t\t\t</FloatRange>')
                elif kind == "variable":
                    _, name, elem_kind, values, refid = f
                    out.append(f'\t\t\t<Variable name="{_esc(name)}" refID="{refid}" />')
                    dotnet_elem = (
                        "System.Double, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"
                        if elem_kind == "double" else
                        "System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"
                    )
                    array_tag = "ArrayOfDouble" if elem_kind == "double" else "ArrayOfString"
                    obj_lines = [
                        f'\t\t<Object refID="{refid}" type="System.Collections.Generic.List`1[[{dotnet_elem}]]">',
                        f'\t\t\t<{array_tag}{XML_SCHEMA_XMLNS}>',
                    ]
                    for v in values:
                        if v is None:
                            obj_lines.append(f'\t\t\t\t<{elem_kind} xsi:nil="true" />')
                        elif v == "":
                            obj_lines.append(f'\t\t\t\t<{elem_kind} />')
                        else:
                            obj_lines.append(f'\t\t\t\t<{elem_kind}>{_esc(_fmt_scalar(v))}</{elem_kind}>')
                    obj_lines.append(f'\t\t\t</{array_tag}>')
                    obj_lines.append('\t\t</Object>')
                    objects_out.extend(obj_lines)
            out.append(f'\t\t\t<int name="RandSeed">{random.randint(1, 2_147_483_647)}</int>')
            out.append('\t\t</Node>')
        out.append('\t</Nodes>')
        out.append('\t<Connections>')
        for a, b in self._connections:
            out.append(f'\t\t<Connection port1ID="{a.id}" port2ID="{b.id}" />')
        out.append('\t</Connections>')
        if objects_out:
            out.append('\t<Objects>')
            out.extend(objects_out)
            out.append('\t</Objects>')
        else:
            out.append('\t<Objects />')
        out.append('</NodeCanvas>')

        parent = os.path.dirname(os.path.abspath(path))
        if parent:
            os.makedirs(parent, exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write("\n".join(out) + "\n")
        return path


# ==================== DesertPlateau expressed as builder calls ====================

def build_desertplateau(g, frequency=None, manifest_overrides=None, tile_req_overrides=None):
    """Issue the exact sequence of g.node()/g.port()/g.connect() calls that
    reproduce LandformDesertPlateau.xml, sourcing field/port/connection
    VALUES from one parse of the shipped file. `frequency`, when given,
    overrides source Node ID=5's (the primary Perlin) Frequency field.
    `manifest_overrides`/`tile_req_overrides` optionally override the
    landformManifest / worldTileReq node's fields for a variant.
    """
    tpl = g._tpl
    src_nodes = tpl["nodes"]
    src_conns = tpl["connections"]
    mo = manifest_overrides or {}
    tro = tile_req_overrides or {}

    port_map = {}  # old port id (str) -> _Port

    for sn in src_nodes:
        type_ = sn["type"]
        kwargs = {}
        floatranges = {}
        for entry in sn["ordered"]:
            if entry[0] == "scalar":
                _, _tag, name, text = entry
                kwargs[name] = text
            elif entry[0] == "variable":
                _, name, obj = entry
                kwargs[name] = obj["values"] if obj is not None else []
            elif entry[0] == "floatrange":
                _, name, mn, mx = entry
                floatranges[name] = (mn, mx)

        if type_ == "landformManifest":
            node = g.manifest(
                id_=mo.get("id", kwargs.get("Id")),
                display_name=mo.get("display_name", kwargs.get("DisplayName", "")),
                is_custom=mo.get("is_custom", kwargs.get("IsCustom") == "true"),
                revision_version=int(kwargs.get("RevisionVersion", 1)),
                time_created=int(kwargs.get("TimeCreated", 0)),
                is_experimental=kwargs.get("IsExperimental") == "true",
                is_internal=kwargs.get("IsInternal") == "true",
                is_edited=kwargs.get("IsEdited") == "true",
                display_name_has_direction=kwargs.get("DisplayNameHasDirection") == "true",
                pos=sn["pos"],
            )
        elif type_ == "worldTileReq":
            node = g.tile_req(
                topology=kwargs.get("Topology", "Inland"),
                commonness=tro.get("commonness", kwargs.get("Commonness")),
                cave_chance=kwargs.get("CaveChance"),
                hilliness=tro.get("hilliness", floatranges.get("HillinessRequirement")),
                road=floatranges.get("RoadRequirement"),
                river=floatranges.get("RiverRequirement"),
                elevation=floatranges.get("ElevationRequirement"),
                avg_temperature=tro.get("avg_temperature", floatranges.get("AvgTemperatureRequirement")),
                rainfall=tro.get("rainfall", floatranges.get("RainfallRequirement")),
                swampiness=floatranges.get("SwampinessRequirement"),
                biome_transitions=floatranges.get("BiomeTransitionsRequirement"),
                topology_value=floatranges.get("TopologyValueRequirement"),
                depth_in_cave_system=floatranges.get("DepthInCaveSystemRequirement"),
                map_size=floatranges.get("MapSizeRequirement"),
                allow_settlements=kwargs.get("AllowSettlements") != "false",
                allow_sites=kwargs.get("AllowSites") != "false",
                pos=sn["pos"],
            )
        else:
            node = g.node(type_, sn["name"], pos=sn["pos"], **kwargs)
            if frequency is not None and sn["old_id"] == "5" and type_ == "gridPerlin":
                for i, f in enumerate(node.fields):
                    if f[0] == "scalar" and f[2] == "Frequency":
                        node.fields[i] = ("scalar", f[1], "Frequency", frequency)

        for p in sn["ports"]:
            if p["dynamic"] == "True":
                direction = p["sub"].get("direction", (None, "In"))[1]
            elif p["name"].endswith("OutputKnob"):
                direction = "Out"
            elif p["name"].endswith("InputKnob"):
                direction = "In"
            else:
                direction = None
            newp = g.port(node, p["name"], direction=direction, dynamic=(p["dynamic"] == "True"))
            port_map[p["old_id"]] = newp

    for a, b in src_conns:
        g.connect(port_map[a], port_map[b])

    return g


# ================================== selftest ==================================

def _norm(v):
    if v is None:
        return None
    try:
        return round(float(v), 9)
    except (TypeError, ValueError):
        return v


def _collect_node_signatures(fg, collect_scalar_fields):
    """(scalar multiset, floatrange multiset, variable multiset) for one FileGraph."""
    scalars = Counter()
    franges = Counter()
    variables = Counter()
    for _nid, ninfo in fg.nodes.items():
        ntype = ninfo["type"]
        fields = defaultdict(list)
        frs = defaultdict(list)
        vars_ = defaultdict(list)
        collect_scalar_fields(ninfo["el"], fields, frs, vars_)
        for (tag, name), values in fields.items():
            if name in ("RandSeed", "TimeCreated"):
                continue
            for v in values:
                scalars[(ntype, tag, name, _norm(v))] += 1
        for name, pairs in frs.items():
            for mn, mx in pairs:
                franges[(ntype, name, _norm(mn), _norm(mx))] += 1
        for name, refids in vars_.items():
            for refid in refids:
                vals = _read_objects(fg.root).get(refid, {}).get("values", [])
                variables[(ntype, name, tuple(_norm(v) for v in vals))] += 1
    return scalars, franges, variables


def _connection_signature(fg):
    sig = Counter()
    for a, b, bad in fg.resolved_edges():
        if bad:
            continue
        pn, cn = fg.port_owner[a], fg.port_owner[b]
        key = (
            f'{fg.nodes[pn]["type"]}.{fg.port_name[a]}',
            f'{fg.nodes[cn]["type"]}.{fg.port_name[b]}',
        )
        sig[key] += 1
    return sig


def run_selftest():
    census = _load_gl_schema_census()

    g = Graph()
    build_desertplateau(g)
    tmp_path = os.path.join(tempfile.gettempdir(), "gl_emit_selftest_desertplateau.xml")
    g.write(tmp_path)

    orig = census.FileGraph(SOURCE_DESERTPLATEAU)
    emitted = census.FileGraph(tmp_path)

    checks = []

    orig_types = Counter(n["type"] for n in orig.nodes.values())
    emit_types = Counter(n["type"] for n in emitted.nodes.values())
    checks.append((
        "node-type multiset",
        orig_types == emit_types,
        f"{sum(orig_types.values())} vs {sum(emit_types.values())} nodes, "
        f"{len(orig_types)} vs {len(emit_types)} distinct types",
    ))

    o_scal, o_fr, o_var = _collect_node_signatures(orig, census.collect_scalar_fields)
    e_scal, e_fr, e_var = _collect_node_signatures(emitted, census.collect_scalar_fields)
    fields_ok = (o_scal == e_scal) and (o_fr == e_fr) and (o_var == e_var)
    checks.append((
        "field values (scalar+FloatRange+Variable, excl. RandSeed/TimeCreated/pos/ID)",
        fields_ok,
        f"scalar_eq={o_scal == e_scal} ({len(o_scal)} vs {len(e_scal)} distinct) "
        f"floatrange_eq={o_fr == e_fr} variable_eq={o_var == e_var}",
    ))

    o_ports, e_ports = len(orig.port_owner), len(emitted.port_owner)
    checks.append(("port count", o_ports == e_ports, f"{o_ports} vs {e_ports}"))

    o_conn = _connection_signature(orig)
    e_conn = _connection_signature(emitted)
    o_total, e_total = sum(o_conn.values()), sum(e_conn.values())
    checks.append((
        "connection set (srcType.port -> dstType.port multiset)",
        o_conn == e_conn,
        f"{o_total} vs {e_total} resolved edges (orig has 35 total incl. anomalies), equal={o_conn == e_conn}",
    ))

    try:
        ET.parse(tmp_path)
        reparse_ok = True
        reparse_detail = tmp_path
    except ET.ParseError as e:
        reparse_ok = False
        reparse_detail = str(e)
    checks.append(("emitted file re-parses with xml.etree", reparse_ok, reparse_detail))

    passed = sum(1 for _, ok, _ in checks if ok)
    total = len(checks)
    for label, ok, detail in checks:
        print(f"  [{'PASS' if ok else 'FAIL'}] {label}: {detail}")
    print(f"SELFTEST {'PASS' if passed == total else 'FAIL'} {passed}/{total}")
    return passed == total


# ==================================== CLI ====================================

def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--selftest", action="store_true", help="rebuild DesertPlateau via the builder and census-compare it to the source")
    ap.add_argument("--variant", action="store_true", help="emit a DesertPlateau variant with a parametrized Perlin Frequency")
    ap.add_argument("--frequency", type=float, default=0.025, help="Frequency for the primary Perlin node (source Node ID=5)")
    ap.add_argument("--id", dest="landform_id", default=None, help="new landformManifest Id / DisplayName")
    ap.add_argument("--out", default=None, help="output path for --variant")
    args = ap.parse_args()

    if args.selftest:
        ok = run_selftest()
        sys.exit(0 if ok else 1)

    if args.variant:
        if not args.landform_id or not args.out:
            print("ERROR: --variant requires --id and --out", file=sys.stderr)
            sys.exit(2)
        g = Graph()
        build_desertplateau(
            g,
            frequency=args.frequency,
            manifest_overrides={
                "id": args.landform_id,
                "display_name": args.landform_id,
                "is_custom": True,
            },
            tile_req_overrides={
                "commonness": 1.0,
                "hilliness": (0.0, 6.0),
                "rainfall": (0.0, 10000.0),
                "avg_temperature": (-100.0, 100.0),
            },
        )
        path = g.write(args.out)
        print(f"Wrote {path}")
        sys.exit(0)

    ap.print_help()
    sys.exit(1)


if __name__ == "__main__":
    main()
